// Generated by scripts/build-card-catalog.cjs; do not edit by hand.
window.FIELD_NOTE_CARDS = [
  {
    "id": "[\"clinical\",\"EMS Systems\",\"Accidental Death and Disability (1966) is famously known as:\"]",
    "kind": "clinical",
    "deck": "EMS Operations",
    "front": "Accidental Death and Disability (1966) is famously known as:",
    "legacy": "EMS Systems|Accidental Death and Disability (1966) is famously known as:"
  },
  {
    "id": "[\"clinical\",\"EMS Systems\",\"Which EMS level is trained in IV therapy and limited advanced meds?\"]",
    "kind": "clinical",
    "deck": "EMS Operations",
    "front": "Which EMS level is trained in IV therapy and limited advanced meds?",
    "legacy": "EMS Systems|Which EMS level is trained in IV therapy and limited advanced meds?"
  },
  {
    "id": "[\"clinical\",\"Safety\",\"What is the primary way to prevent disease transmission?\"]",
    "kind": "clinical",
    "deck": "EMS Operations",
    "front": "What is the primary way to prevent disease transmission?",
    "legacy": "Safety|What is the primary way to prevent disease transmission?"
  },
  {
    "id": "[\"clinical\",\"Legal\",\"What element of neglect is violated if you hand off care of a patient to a lesser trained healthcare professional?\"]",
    "kind": "clinical",
    "deck": "EMS Operations",
    "front": "What element of neglect is violated if you hand off care of a patient to a lesser trained healthcare professional?",
    "legacy": "Legal|What element of neglect is violated if you hand off care of a patient to a lesser trained healthcare professional?"
  },
  {
    "id": "[\"clinical\",\"Communications\",\"In SBAR, what does 'B' stand for?\"]",
    "kind": "clinical",
    "deck": "EMS Operations",
    "front": "In SBAR, what does 'B' stand for?",
    "legacy": "Communications|In SBAR, what does 'B' stand for?"
  },
  {
    "id": "[\"clinical\",\"Lifting\",\"Which lifting technique uses the legs and an upright back?\"]",
    "kind": "clinical",
    "deck": "EMS Operations",
    "front": "Which lifting technique uses the legs and an upright back?",
    "legacy": "Lifting|Which lifting technique uses the legs and an upright back?"
  },
  {
    "id": "[\"clinical\",\"EMS Systems\",\"Which document establishes the 'Scope of Practice' for an AEMT within a specific state?\"]",
    "kind": "clinical",
    "deck": "EMS Operations",
    "front": "Which document establishes the 'Scope of Practice' for an AEMT within a specific state?",
    "legacy": "EMS Systems|Which document establishes the 'Scope of Practice' for an AEMT within a specific state?"
  },
  {
    "id": "[\"clinical\",\"Legal\",\"A patient refuses care and is able to answer questions but has slurred speech with repetitive questioning. You should treat this patient under which of the following:\"]",
    "kind": "clinical",
    "deck": "EMS Operations",
    "front": "A patient refuses care and is able to answer questions but has slurred speech with repetitive questioning. You should treat this patient under which of the following:",
    "legacy": "Legal|A patient refuses care and is able to answer questions but has slurred speech with repetitive questioning. You should treat this patient under which of the following:"
  },
  {
    "id": "[\"clinical\",\"Legal\",\"What is the difference between Libel and Slander?\"]",
    "kind": "clinical",
    "deck": "EMS Operations",
    "front": "What is the difference between Libel and Slander?",
    "legacy": "Legal|What is the difference between Libel and Slander?"
  },
  {
    "id": "[\"clinical\",\"Wellness\",\"In the 'Five Stages of Grief,' which stage involves a patient trying to make a deal to postpone the inevitable?\"]",
    "kind": "clinical",
    "deck": "EMS Operations",
    "front": "In the 'Five Stages of Grief,' which stage involves a patient trying to make a deal to postpone the inevitable?",
    "legacy": "Wellness|In the 'Five Stages of Grief,' which stage involves a patient trying to make a deal to postpone the inevitable?"
  },
  {
    "id": "[\"clinical\",\"EMS Systems\",\"Which federal document provides the 'National EMS Scope of Practice Model' that states use to create their laws?\"]",
    "kind": "clinical",
    "deck": "EMS Operations",
    "front": "Which federal document provides the 'National EMS Scope of Practice Model' that states use to create their laws?",
    "legacy": "EMS Systems|Which federal document provides the 'National EMS Scope of Practice Model' that states use to create their laws?"
  },
  {
    "id": "[\"clinical\",\"EMS Systems\",\"AEMT care is typically required to be provided under the license of a:\"]",
    "kind": "clinical",
    "deck": "EMS Operations",
    "front": "AEMT care is typically required to be provided under the license of a:",
    "legacy": "EMS Systems|AEMT care is typically required to be provided under the license of a:"
  },
  {
    "id": "[\"clinical\",\"Legal\",\"Assault is defined legally as:\"]",
    "kind": "clinical",
    "deck": "EMS Operations",
    "front": "Assault is defined legally as:",
    "legacy": "Legal|Assault is defined legally as:"
  },
  {
    "id": "[\"clinical\",\"Patho\",\"What is the primary product of anaerobic metabolism?\"]",
    "kind": "clinical",
    "deck": "Pathophysiology",
    "front": "What is the primary product of anaerobic metabolism?",
    "legacy": "Patho|What is the primary product of anaerobic metabolism?"
  },
  {
    "id": "[\"clinical\",\"Patho\",\"Shock caused by widespread vasodilation is categorized as:\"]",
    "kind": "clinical",
    "deck": "Pathophysiology",
    "front": "Shock caused by widespread vasodilation is categorized as:",
    "legacy": "Patho|Shock caused by widespread vasodilation is categorized as:"
  },
  {
    "id": "[\"clinical\",\"Patho\",\"A patient hypoventilating from an opioid OD is likely in:\"]",
    "kind": "clinical",
    "deck": "Pathophysiology",
    "front": "A patient hypoventilating from an opioid OD is likely in:",
    "legacy": "Patho|A patient hypoventilating from an opioid OD is likely in:"
  },
  {
    "id": "[\"clinical\",\"Patho\",\"Kussmaul respirations in DKA are an attempt to compensate for:\"]",
    "kind": "clinical",
    "deck": "Pathophysiology",
    "front": "Kussmaul respirations in DKA are an attempt to compensate for:",
    "legacy": "Patho|Kussmaul respirations in DKA are an attempt to compensate for:"
  },
  {
    "id": "[\"clinical\",\"Patho\",\"Which of the following is the primary chemical buffer system in the human body?\"]",
    "kind": "clinical",
    "deck": "Pathophysiology",
    "front": "Which of the following is the primary chemical buffer system in the human body?",
    "legacy": "Patho|Which of the following is the primary chemical buffer system in the human body?"
  },
  {
    "id": "[\"clinical\",\"Patho\",\"A hyperventilating patient with an EtCO2 of 22 is in:\"]",
    "kind": "clinical",
    "deck": "Pathophysiology",
    "front": "A hyperventilating patient with an EtCO2 of 22 is in:",
    "legacy": "Patho|A hyperventilating patient with an EtCO2 of 22 is in:"
  },
  {
    "id": "[\"clinical\",\"Patho\",\"What is the normal pH range of human arterial blood?\"]",
    "kind": "clinical",
    "deck": "Pathophysiology",
    "front": "What is the normal pH range of human arterial blood?",
    "legacy": "Patho|What is the normal pH range of human arterial blood?"
  },
  {
    "id": "[\"clinical\",\"Patho\",\"A COPD patient is retaining CO2. This results in an increase of which ion in the blood?\"]",
    "kind": "clinical",
    "deck": "Pathophysiology",
    "front": "A COPD patient is retaining CO2. This results in an increase of which ion in the blood?",
    "legacy": "Patho|A COPD patient is retaining CO2. This results in an increase of which ion in the blood?"
  },
  {
    "id": "[\"clinical\",\"Patho\",\"Which organ system is responsible for the 'Long-term' compensation of acid-base imbalances?\"]",
    "kind": "clinical",
    "deck": "Pathophysiology",
    "front": "Which organ system is responsible for the 'Long-term' compensation of acid-base imbalances?",
    "legacy": "Patho|Which organ system is responsible for the 'Long-term' compensation of acid-base imbalances?"
  },
  {
    "id": "[\"clinical\",\"Patho\",\"In a state of Acidosis, the heart becomes:\"]",
    "kind": "clinical",
    "deck": "Pathophysiology",
    "front": "In a state of Acidosis, the heart becomes:",
    "legacy": "Patho|In a state of Acidosis, the heart becomes:"
  },
  {
    "id": "[\"clinical\",\"Patho\",\"The Bicarbonate Buffer System manages pH by balancing which two components?\"]",
    "kind": "clinical",
    "deck": "Pathophysiology",
    "front": "The Bicarbonate Buffer System manages pH by balancing which two components?",
    "legacy": "Patho|The Bicarbonate Buffer System manages pH by balancing which two components?"
  },
  {
    "id": "[\"clinical\",\"Cardiovascular\",\"A 70-year-old male presents with extreme dyspnea, waking up gasping for air. Sitting bolt-upright, pink, frothy sputum. BP 190/104. Interventions? (Select all that apply)\"]",
    "kind": "clinical",
    "deck": "Medical",
    "front": "A 70-year-old male presents with extreme dyspnea, waking up gasping for air. Sitting bolt-upright, pink, frothy sputum. BP 190/104. Interventions? (Select all that apply)",
    "legacy": "Cardiovascular|A 70-year-old male presents with extreme dyspnea, waking up gasping for air. Sitting bolt-upright, pink, frothy sputum. BP 190/104. Interventions? (Select all that apply)"
  },
  {
    "id": "[\"clinical\",\"Cardiovascular\",\"Worsening fatigue, JVD, and bilateral pedal edema in a COPD patient indicates:\"]",
    "kind": "clinical",
    "deck": "Medical",
    "front": "Worsening fatigue, JVD, and bilateral pedal edema in a COPD patient indicates:",
    "legacy": "Cardiovascular|Worsening fatigue, JVD, and bilateral pedal edema in a COPD patient indicates:"
  },
  {
    "id": "[\"clinical\",\"Respiratory\",\"How does CPAP improve oxygenation in pulmonary edema?\"]",
    "kind": "clinical",
    "deck": "Medical",
    "front": "How does CPAP improve oxygenation in pulmonary edema?",
    "legacy": "Respiratory|How does CPAP improve oxygenation in pulmonary edema?"
  },
  {
    "id": "[\"clinical\",\"Neurology\",\"Stroke symptoms that resolve in 45 minutes are:\"]",
    "kind": "clinical",
    "deck": "Medical",
    "front": "Stroke symptoms that resolve in 45 minutes are:",
    "legacy": "Neurology|Stroke symptoms that resolve in 45 minutes are:"
  },
  {
    "id": "[\"clinical\",\"Endocrine\",\"Cushing's Syndrome signs:\"]",
    "kind": "clinical",
    "deck": "Medical",
    "front": "Cushing's Syndrome signs:",
    "legacy": "Endocrine|Cushing's Syndrome signs:"
  },
  {
    "id": "[\"clinical\",\"Cardiovascular\",\"Tearing back pain and unequal BPs in arms indicates:\"]",
    "kind": "clinical",
    "deck": "Medical",
    "front": "Tearing back pain and unequal BPs in arms indicates:",
    "legacy": "Cardiovascular|Tearing back pain and unequal BPs in arms indicates:"
  },
  {
    "id": "[\"clinical\",\"Assessment\",\"Twitching facial nerve (Chvostek's sign) indicates:\"]",
    "kind": "clinical",
    "deck": "Medical",
    "front": "Twitching facial nerve (Chvostek's sign) indicates:",
    "legacy": "Assessment|Twitching facial nerve (Chvostek's sign) indicates:"
  },
  {
    "id": "[\"clinical\",\"Endocrine\",\"Lethargic patient, rapid deep respirations, high glucose. First priority?\"]",
    "kind": "clinical",
    "deck": "Medical",
    "front": "Lethargic patient, rapid deep respirations, high glucose. First priority?",
    "legacy": "Endocrine|Lethargic patient, rapid deep respirations, high glucose. First priority?"
  },
  {
    "id": "[\"clinical\",\"Gynecology\",\"Mittelschmerz refers to:\"]",
    "kind": "clinical",
    "deck": "Medical",
    "front": "Mittelschmerz refers to:",
    "legacy": "Gynecology|Mittelschmerz refers to:"
  },
  {
    "id": "[\"clinical\",\"MOI\",\"Coup-contrecoup injury occurs in which collision?\"]",
    "kind": "clinical",
    "deck": "Trauma",
    "front": "Coup-contrecoup injury occurs in which collision?",
    "legacy": "MOI|Coup-contrecoup injury occurs in which collision?"
  },
  {
    "id": "[\"clinical\",\"Bleeding\",\"Class III Hemorrhage loss percentage?\"]",
    "kind": "clinical",
    "deck": "Trauma",
    "front": "Class III Hemorrhage loss percentage?",
    "legacy": "Bleeding|Class III Hemorrhage loss percentage?"
  },
  {
    "id": "[\"clinical\",\"Chest\",\"Beck's Triad (JVD, muffled sounds, narrow pulse pressure) indicates:\"]",
    "kind": "clinical",
    "deck": "Trauma",
    "front": "Beck's Triad (JVD, muffled sounds, narrow pulse pressure) indicates:",
    "legacy": "Chest|Beck's Triad (JVD, muffled sounds, narrow pulse pressure) indicates:"
  },
  {
    "id": "[\"clinical\",\"Abdominal\",\"Kehr's sign (L shoulder pain) indicates:\"]",
    "kind": "clinical",
    "deck": "Trauma",
    "front": "Kehr's sign (L shoulder pain) indicates:",
    "legacy": "Abdominal|Kehr's sign (L shoulder pain) indicates:"
  },
  {
    "id": "[\"clinical\",\"Ortho\",\"What are the '6 Ps'? (Select all that apply)\"]",
    "kind": "clinical",
    "deck": "Trauma",
    "front": "What are the '6 Ps'? (Select all that apply)",
    "legacy": "Ortho|What are the '6 Ps'? (Select all that apply)"
  },
  {
    "id": "[\"clinical\",\"Bleeding\",\"Trauma 'Lethal Triad' contains: (Select all that apply)\"]",
    "kind": "clinical",
    "deck": "Trauma",
    "front": "Trauma 'Lethal Triad' contains: (Select all that apply)",
    "legacy": "Bleeding|Trauma 'Lethal Triad' contains: (Select all that apply)"
  },
  {
    "id": "[\"clinical\",\"Head/Spine\",\"Cushing's Triad signs:\"]",
    "kind": "clinical",
    "deck": "Trauma",
    "front": "Cushing's Triad signs:",
    "legacy": "Head/Spine|Cushing's Triad signs:"
  },
  {
    "id": "[\"clinical\",\"Environmental\",\"Cold-water drowning patient status:\"]",
    "kind": "clinical",
    "deck": "Trauma",
    "front": "Cold-water drowning patient status:",
    "legacy": "Environmental|Cold-water drowning patient status:"
  },
  {
    "id": "[\"clinical\",\"Environmental\",\"Gas law for 'The Bends':\"]",
    "kind": "clinical",
    "deck": "Trauma",
    "front": "Gas law for 'The Bends':",
    "legacy": "Environmental|Gas law for 'The Bends':"
  },
  {
    "id": "[\"clinical\",\"Soft-Tissue\",\"Crush Syndrome pathophysiology:\"]",
    "kind": "clinical",
    "deck": "Trauma",
    "front": "Crush Syndrome pathophysiology:",
    "legacy": "Soft-Tissue|Crush Syndrome pathophysiology:"
  },
  {
    "id": "[\"clinical\",\"Physics\",\"Kinetic Energy formula:\"]",
    "kind": "clinical",
    "deck": "Trauma",
    "front": "Kinetic Energy formula:",
    "legacy": "Physics|Kinetic Energy formula:"
  },
  {
    "id": "[\"clinical\",\"Soft-Tissue\",\"Burn with red, painful blisters is:\"]",
    "kind": "clinical",
    "deck": "Trauma",
    "front": "Burn with red, painful blisters is:",
    "legacy": "Soft-Tissue|Burn with red, painful blisters is:"
  },
  {
    "id": "[\"clinical\",\"Head/Spine\",\"CPP formula involves:\"]",
    "kind": "clinical",
    "deck": "Trauma",
    "front": "CPP formula involves:",
    "legacy": "Head/Spine|CPP formula involves:"
  },
  {
    "id": "[\"clinical\",\"Chest\",\"Tension Pneumo field priority:\"]",
    "kind": "clinical",
    "deck": "Trauma",
    "front": "Tension Pneumo field priority:",
    "legacy": "Chest|Tension Pneumo field priority:"
  },
  {
    "id": "[\"clinical\",\"Abdominal\",\"Scaphoid abdomen suggests:\"]",
    "kind": "clinical",
    "deck": "Trauma",
    "front": "Scaphoid abdomen suggests:",
    "legacy": "Abdominal|Scaphoid abdomen suggests:"
  },
  {
    "id": "[\"clinical\",\"Ortho\",\"Open pelvic fracture priority:\"]",
    "kind": "clinical",
    "deck": "Trauma",
    "front": "Open pelvic fracture priority:",
    "legacy": "Ortho|Open pelvic fracture priority:"
  },
  {
    "id": "[\"clinical\",\"Shock\",\"Permissive hypotension MAP target:\"]",
    "kind": "clinical",
    "deck": "Trauma",
    "front": "Permissive hypotension MAP target:",
    "legacy": "Shock|Permissive hypotension MAP target:"
  },
  {
    "id": "[\"clinical\",\"Environmental\",\"Heat Stroke hallmark sign:\"]",
    "kind": "clinical",
    "deck": "Trauma",
    "front": "Heat Stroke hallmark sign:",
    "legacy": "Environmental|Heat Stroke hallmark sign:"
  },
  {
    "id": "[\"clinical\",\"Head/Spine\",\"Blown pupil on R indicates:\"]",
    "kind": "clinical",
    "deck": "Trauma",
    "front": "Blown pupil on R indicates:",
    "legacy": "Head/Spine|Blown pupil on R indicates:"
  },
  {
    "id": "[\"clinical\",\"Ortho\",\"Latest 6P sign to develop:\"]",
    "kind": "clinical",
    "deck": "Trauma",
    "front": "Latest 6P sign to develop:",
    "legacy": "Ortho|Latest 6P sign to develop:"
  },
  {
    "id": "[\"clinical\",\"Head/Spine\",\"Adult toes fanning out (sole stroke) is:\"]",
    "kind": "clinical",
    "deck": "Trauma",
    "front": "Adult toes fanning out (sole stroke) is:",
    "legacy": "Head/Spine|Adult toes fanning out (sole stroke) is:"
  },
  {
    "id": "[\"clinical\",\"Head/Spine\",\"Spinal shock definition:\"]",
    "kind": "clinical",
    "deck": "Trauma",
    "front": "Spinal shock definition:",
    "legacy": "Head/Spine|Spinal shock definition:"
  },
  {
    "id": "[\"clinical\",\"Ortho\",\"Greenstick fracture population:\"]",
    "kind": "clinical",
    "deck": "Trauma",
    "front": "Greenstick fracture population:",
    "legacy": "Ortho|Greenstick fracture population:"
  },
  {
    "id": "[\"clinical\",\"Environmental\",\"Mammalian Diving Reflex law:\"]",
    "kind": "clinical",
    "deck": "Trauma",
    "front": "Mammalian Diving Reflex law:",
    "legacy": "Environmental|Mammalian Diving Reflex law:"
  },
  {
    "id": "[\"clinical\",\"Obstetrics\",\"Painless, bright red 3rd trimester bleeding is:\"]",
    "kind": "clinical",
    "deck": "OB/GYN",
    "front": "Painless, bright red 3rd trimester bleeding is:",
    "legacy": "Obstetrics|Painless, bright red 3rd trimester bleeding is:"
  },
  {
    "id": "[\"clinical\",\"Obstetrics\",\"Eclampsia differentiator:\"]",
    "kind": "clinical",
    "deck": "OB/GYN",
    "front": "Eclampsia differentiator:",
    "legacy": "Obstetrics|Eclampsia differentiator:"
  },
  {
    "id": "[\"clinical\",\"Obstetrics\",\"Stuck shoulders during delivery:\"]",
    "kind": "clinical",
    "deck": "OB/GYN",
    "front": "Stuck shoulders during delivery:",
    "legacy": "Obstetrics|Stuck shoulders during delivery:"
  },
  {
    "id": "[\"clinical\",\"Neonatal\",\"Neonatal 2-rescuer CPR ratio:\"]",
    "kind": "clinical",
    "deck": "Pediatrics",
    "front": "Neonatal 2-rescuer CPR ratio:",
    "legacy": "Neonatal|Neonatal 2-rescuer CPR ratio:"
  },
  {
    "id": "[\"clinical\",\"Neonatal\",\"Neonatal HR 54 after 30s PPV. Action?\"]",
    "kind": "clinical",
    "deck": "Pediatrics",
    "front": "Neonatal HR 54 after 30s PPV. Action?",
    "legacy": "Neonatal|Neonatal HR 54 after 30s PPV. Action?"
  },
  {
    "id": "[\"clinical\",\"Pediatrics\",\"PAT Triangle components: (Select all that apply)\"]",
    "kind": "clinical",
    "deck": "Pediatrics",
    "front": "PAT Triangle components: (Select all that apply)",
    "legacy": "Pediatrics|PAT Triangle components: (Select all that apply)"
  },
  {
    "id": "[\"clinical\",\"Pediatrics\",\"Drooling, high fever, tripod position in 3yo:\"]",
    "kind": "clinical",
    "deck": "Pediatrics",
    "front": "Drooling, high fever, tripod position in 3yo:",
    "legacy": "Pediatrics|Drooling, high fever, tripod position in 3yo:"
  },
  {
    "id": "[\"clinical\",\"Pediatrics\",\"Seal-bark cough in infant:\"]",
    "kind": "clinical",
    "deck": "Pediatrics",
    "front": "Seal-bark cough in infant:",
    "legacy": "Pediatrics|Seal-bark cough in infant:"
  },
  {
    "id": "[\"clinical\",\"Pediatrics\",\"Sunken fontanelle sign:\"]",
    "kind": "clinical",
    "deck": "Pediatrics",
    "front": "Sunken fontanelle sign:",
    "legacy": "Pediatrics|Sunken fontanelle sign:"
  },
  {
    "id": "[\"clinical\",\"Obstetrics\",\"Prolapsed cord management:\"]",
    "kind": "clinical",
    "deck": "OB/GYN",
    "front": "Prolapsed cord management:",
    "legacy": "Obstetrics|Prolapsed cord management:"
  },
  {
    "id": "[\"clinical\",\"Terminology\",\"Medical term for 'a heart rate below 60 beats per minute.'\"]",
    "kind": "clinical",
    "deck": "Terminology",
    "front": "Medical term for 'a heart rate below 60 beats per minute.'",
    "legacy": "Terminology|Medical term for 'a heart rate below 60 beats per minute.'"
  },
  {
    "id": "[\"clinical\",\"Terminology\",\"Medical term for 'a heart rate above 100 beats per minute.'\"]",
    "kind": "clinical",
    "deck": "Terminology",
    "front": "Medical term for 'a heart rate above 100 beats per minute.'",
    "legacy": "Terminology|Medical term for 'a heart rate above 100 beats per minute.'"
  },
  {
    "id": "[\"clinical\",\"Terminology\",\"Medical term for 'difficulty or labored breathing.'\"]",
    "kind": "clinical",
    "deck": "Terminology",
    "front": "Medical term for 'difficulty or labored breathing.'",
    "legacy": "Terminology|Medical term for 'difficulty or labored breathing.'"
  },
  {
    "id": "[\"clinical\",\"Terminology\",\"Medical term for 'the absence of breathing.'\"]",
    "kind": "clinical",
    "deck": "Terminology",
    "front": "Medical term for 'the absence of breathing.'",
    "legacy": "Terminology|Medical term for 'the absence of breathing.'"
  },
  {
    "id": "[\"clinical\",\"Terminology\",\"Medical term for 'vomiting blood.'\"]",
    "kind": "clinical",
    "deck": "Terminology",
    "front": "Medical term for 'vomiting blood.'",
    "legacy": "Terminology|Medical term for 'vomiting blood.'"
  },
  {
    "id": "[\"clinical\",\"Terminology\",\"Medical term for 'blood in the urine.'\"]",
    "kind": "clinical",
    "deck": "Terminology",
    "front": "Medical term for 'blood in the urine.'",
    "legacy": "Terminology|Medical term for 'blood in the urine.'"
  },
  {
    "id": "[\"clinical\",\"Terminology\",\"Medical term for 'enlargement of the liver.'\"]",
    "kind": "clinical",
    "deck": "Terminology",
    "front": "Medical term for 'enlargement of the liver.'",
    "legacy": "Terminology|Medical term for 'enlargement of the liver.'"
  },
  {
    "id": "[\"clinical\",\"Terminology\",\"Medical term for 'inflammation of the gallbladder.'\"]",
    "kind": "clinical",
    "deck": "Terminology",
    "front": "Medical term for 'inflammation of the gallbladder.'",
    "legacy": "Terminology|Medical term for 'inflammation of the gallbladder.'"
  },
  {
    "id": "[\"clinical\",\"Terminology\",\"Medical term for 'excessive sweating.'\"]",
    "kind": "clinical",
    "deck": "Terminology",
    "front": "Medical term for 'excessive sweating.'",
    "legacy": "Terminology|Medical term for 'excessive sweating.'"
  },
  {
    "id": "[\"clinical\",\"Terminology\",\"Medical term for 'blood in the chest cavity.'\"]",
    "kind": "clinical",
    "deck": "Terminology",
    "front": "Medical term for 'blood in the chest cavity.'",
    "legacy": "Terminology|Medical term for 'blood in the chest cavity.'"
  },
  {
    "id": "[\"clinical\",\"Terminology\",\"Medical term for 'low levels of oxygen in the tissues.'\"]",
    "kind": "clinical",
    "deck": "Terminology",
    "front": "Medical term for 'low levels of oxygen in the tissues.'",
    "legacy": "Terminology|Medical term for 'low levels of oxygen in the tissues.'"
  },
  {
    "id": "[\"clinical\",\"Terminology\",\"Medical term for 'bluish discoloration of the skin due to low oxygen.'\"]",
    "kind": "clinical",
    "deck": "Terminology",
    "front": "Medical term for 'bluish discoloration of the skin due to low oxygen.'",
    "legacy": "Terminology|Medical term for 'bluish discoloration of the skin due to low oxygen.'"
  },
  {
    "id": "[\"clinical\",\"Terminology\",\"Medical term for 'a new surgical opening in the stomach.'\"]",
    "kind": "clinical",
    "deck": "Terminology",
    "front": "Medical term for 'a new surgical opening in the stomach.'",
    "legacy": "Terminology|Medical term for 'a new surgical opening in the stomach.'"
  },
  {
    "id": "[\"clinical\",\"Terminology\",\"Medical term for 'the muscle layer of the heart.'\"]",
    "kind": "clinical",
    "deck": "Terminology",
    "front": "Medical term for 'the muscle layer of the heart.'",
    "legacy": "Terminology|Medical term for 'the muscle layer of the heart.'"
  },
  {
    "id": "[\"clinical\",\"Terminology\",\"Medical term for 'any disease of the kidneys.'\"]",
    "kind": "clinical",
    "deck": "Terminology",
    "front": "Medical term for 'any disease of the kidneys.'",
    "legacy": "Terminology|Medical term for 'any disease of the kidneys.'"
  },
  {
    "id": "[\"clinical\",\"Terminology\",\"Medical term for 'excessive production of urine.'\"]",
    "kind": "clinical",
    "deck": "Terminology",
    "front": "Medical term for 'excessive production of urine.'",
    "legacy": "Terminology|Medical term for 'excessive production of urine.'"
  },
  {
    "id": "[\"clinical\",\"Terminology\",\"Medical term for 'difficulty breathing when lying flat.'\"]",
    "kind": "clinical",
    "deck": "Terminology",
    "front": "Medical term for 'difficulty breathing when lying flat.'",
    "legacy": "Terminology|Medical term for 'difficulty breathing when lying flat.'"
  },
  {
    "id": "[\"clinical\",\"Terminology\",\"Medical term for 'a respiratory rate that is slower than normal.'\"]",
    "kind": "clinical",
    "deck": "Terminology",
    "front": "Medical term for 'a respiratory rate that is slower than normal.'",
    "legacy": "Terminology|Medical term for 'a respiratory rate that is slower than normal.'"
  },
  {
    "id": "[\"clinical\",\"Terminology\",\"Medical term for 'a respiratory rate that is faster than normal.'\"]",
    "kind": "clinical",
    "deck": "Terminology",
    "front": "Medical term for 'a respiratory rate that is faster than normal.'",
    "legacy": "Terminology|Medical term for 'a respiratory rate that is faster than normal.'"
  },
  {
    "id": "[\"clinical\",\"Terminology\",\"Medical term for 'excessive or profuse bleeding.'\"]",
    "kind": "clinical",
    "deck": "Terminology",
    "front": "Medical term for 'excessive or profuse bleeding.'",
    "legacy": "Terminology|Medical term for 'excessive or profuse bleeding.'"
  },
  {
    "id": "[\"clinical\",\"Pharmacology\",\"Standard adult dose of Epinephrine 1:1,000 for anaphylaxis? (e.g., 0.5 mg)\"]",
    "kind": "clinical",
    "deck": "Medical",
    "front": "Standard adult dose of Epinephrine 1:1,000 for anaphylaxis? (e.g., 0.5 mg)",
    "legacy": "Pharmacology|Standard adult dose of Epinephrine 1:1,000 for anaphylaxis? (e.g., 0.5 mg)"
  },
  {
    "id": "[\"clinical\",\"Terminology\",\"Medical term for 'Shortness of Breath.'\"]",
    "kind": "clinical",
    "deck": "Terminology",
    "front": "Medical term for 'Shortness of Breath.'",
    "legacy": "Terminology|Medical term for 'Shortness of Breath.'"
  },
  {
    "id": "[\"clinical\",\"Respiratory\",\"Target EtCO2 range for respiratory distress?\"]",
    "kind": "clinical",
    "deck": "Medical",
    "front": "Target EtCO2 range for respiratory distress?",
    "legacy": "Respiratory|Target EtCO2 range for respiratory distress?"
  },
  {
    "id": "[\"clinical\",\"Patho\",\"A sudden drop in cardiac output due to a massive Pulmonary Embolism (PE) is a classic example of which type of shock?\"]",
    "kind": "clinical",
    "deck": "Pathophysiology",
    "front": "A sudden drop in cardiac output due to a massive Pulmonary Embolism (PE) is a classic example of which type of shock?",
    "legacy": "Patho|A sudden drop in cardiac output due to a massive Pulmonary Embolism (PE) is a classic example of which type of shock?"
  },
  {
    "id": "[\"clinical\",\"Patho\",\"What is the primary intracellular cation in the human body?\"]",
    "kind": "clinical",
    "deck": "Pathophysiology",
    "front": "What is the primary intracellular cation in the human body?",
    "legacy": "Patho|What is the primary intracellular cation in the human body?"
  },
  {
    "id": "[\"clinical\",\"Patho\",\"What cellular process occurs when cells are forced to switch to metabolism without a sufficient oxygen supply?\"]",
    "kind": "clinical",
    "deck": "Pathophysiology",
    "front": "What cellular process occurs when cells are forced to switch to metabolism without a sufficient oxygen supply?",
    "legacy": "Patho|What cellular process occurs when cells are forced to switch to metabolism without a sufficient oxygen supply?"
  },
  {
    "id": "[\"clinical\",\"Patho\",\"An accumulation of lactic acid in the blood leads to which specific acid-base condition?\"]",
    "kind": "clinical",
    "deck": "Pathophysiology",
    "front": "An accumulation of lactic acid in the blood leads to which specific acid-base condition?",
    "legacy": "Patho|An accumulation of lactic acid in the blood leads to which specific acid-base condition?"
  },
  {
    "id": "[\"clinical\",\"Patho\",\"What is the primary chemical buffer system used by the human body to maintain pH balance?\"]",
    "kind": "clinical",
    "deck": "Pathophysiology",
    "front": "What is the primary chemical buffer system used by the human body to maintain pH balance?",
    "legacy": "Patho|What is the primary chemical buffer system used by the human body to maintain pH balance?"
  },
  {
    "id": "[\"clinical\",\"Patho\",\"Low serum calcium levels (hypocalcemia) can lead to involuntary muscle spasms, a condition known as?\"]",
    "kind": "clinical",
    "deck": "Pathophysiology",
    "front": "Low serum calcium levels (hypocalcemia) can lead to involuntary muscle spasms, a condition known as?",
    "legacy": "Patho|Low serum calcium levels (hypocalcemia) can lead to involuntary muscle spasms, a condition known as?"
  },
  {
    "id": "[\"clinical\",\"Patho\",\"What is the primary underlying vascular mechanism that leads to septic shock?\"]",
    "kind": "clinical",
    "deck": "Pathophysiology",
    "front": "What is the primary underlying vascular mechanism that leads to septic shock?",
    "legacy": "Patho|What is the primary underlying vascular mechanism that leads to septic shock?"
  },
  {
    "id": "[\"clinical\",\"Cardiology\",\"List the components of Virchow's Triad.\"]",
    "kind": "clinical",
    "deck": "Medical",
    "front": "List the components of Virchow's Triad.",
    "legacy": "Cardiology|List the components of Virchow's Triad."
  },
  {
    "id": "[\"clinical\",\"Respiratory\",\"Describe the 'Shark Fin' waveform on a capnogram.\"]",
    "kind": "clinical",
    "deck": "Medical",
    "front": "Describe the 'Shark Fin' waveform on a capnogram.",
    "legacy": "Respiratory|Describe the 'Shark Fin' waveform on a capnogram."
  },
  {
    "id": "[\"clinical\",\"Neuro\",\"Differentiate between Decorticate and Decerebrate posturing.\"]",
    "kind": "clinical",
    "deck": "Medical",
    "front": "Differentiate between Decorticate and Decerebrate posturing.",
    "legacy": "Neuro|Differentiate between Decorticate and Decerebrate posturing."
  },
  {
    "id": "[\"clinical\",\"OBPeds\",\"What is the clinical definition of Eclampsia?\"]",
    "kind": "clinical",
    "deck": "OB/GYN",
    "front": "What is the clinical definition of Eclampsia?",
    "legacy": "OBPeds|What is the clinical definition of Eclampsia?"
  },
  {
    "id": "[\"clinical\",\"Cardiology\",\"Explain the Frank-Starling Law of the Heart.\"]",
    "kind": "clinical",
    "deck": "Medical",
    "front": "Explain the Frank-Starling Law of the Heart.",
    "legacy": "Cardiology|Explain the Frank-Starling Law of the Heart."
  },
  {
    "id": "[\"clinical\",\"Patho\",\"Describe the transition from Aerobic to Anaerobic metabolism during shock.\"]",
    "kind": "clinical",
    "deck": "Pathophysiology",
    "front": "Describe the transition from Aerobic to Anaerobic metabolism during shock.",
    "legacy": "Patho|Describe the transition from Aerobic to Anaerobic metabolism during shock."
  },
  {
    "id": "[\"clinical\",\"Respiratory\",\"Define 'Ventilation-Perfusion (V/Q) Mismatch'.\"]",
    "kind": "clinical",
    "deck": "Medical",
    "front": "Define 'Ventilation-Perfusion (V/Q) Mismatch'.",
    "legacy": "Respiratory|Define 'Ventilation-Perfusion (V/Q) Mismatch'."
  },
  {
    "id": "[\"clinical\",\"Cardiology\",\"What is 'Cor Pulmonale'?\"]",
    "kind": "clinical",
    "deck": "Medical",
    "front": "What is 'Cor Pulmonale'?",
    "legacy": "Cardiology|What is 'Cor Pulmonale'?"
  },
  {
    "id": "[\"clinical\",\"Physician\",\"Wolff-Parkinson-White (WPW) Syndrome — identify the accessory pathway.\"]",
    "kind": "clinical",
    "deck": "Medical",
    "front": "Wolff-Parkinson-White (WPW) Syndrome — identify the accessory pathway.",
    "legacy": "Physician|Wolff-Parkinson-White (WPW) Syndrome — identify the accessory pathway."
  },
  {
    "id": "[\"clinical\",\"Physician\",\"What is HELLP Syndrome and what is the definitive treatment?\"]",
    "kind": "clinical",
    "deck": "Medical",
    "front": "What is HELLP Syndrome and what is the definitive treatment?",
    "legacy": "Physician|What is HELLP Syndrome and what is the definitive treatment?"
  },
  {
    "id": "[\"clinical\",\"Physician\",\"What is Pheochromocytoma?\"]",
    "kind": "clinical",
    "deck": "Medical",
    "front": "What is Pheochromocytoma?",
    "legacy": "Physician|What is Pheochromocytoma?"
  },
  {
    "id": "[\"clinical\",\"Physician\",\"Describe the pathophysiology of Rhabdomyolysis.\"]",
    "kind": "clinical",
    "deck": "Medical",
    "front": "Describe the pathophysiology of Rhabdomyolysis.",
    "legacy": "Physician|Describe the pathophysiology of Rhabdomyolysis."
  },
  {
    "id": "[\"clinical\",\"Physician\",\"What is Aortic Stenosis murmur?\"]",
    "kind": "clinical",
    "deck": "Medical",
    "front": "What is Aortic Stenosis murmur?",
    "legacy": "Physician|What is Aortic Stenosis murmur?"
  },
  {
    "id": "[\"clinical\",\"Physician\",\"What is Horner's Syndrome triad?\"]",
    "kind": "clinical",
    "deck": "Medical",
    "front": "What is Horner's Syndrome triad?",
    "legacy": "Physician|What is Horner's Syndrome triad?"
  },
  {
    "id": "[\"clinical\",\"Physician\",\"Why do ACE Inhibitors cause a dry cough?\"]",
    "kind": "clinical",
    "deck": "Medical",
    "front": "Why do ACE Inhibitors cause a dry cough?",
    "legacy": "Physician|Why do ACE Inhibitors cause a dry cough?"
  },
  {
    "id": "[\"clinical\",\"Physician\",\"What is the Anion Gap formula?\"]",
    "kind": "clinical",
    "deck": "Medical",
    "front": "What is the Anion Gap formula?",
    "legacy": "Physician|What is the Anion Gap formula?"
  },
  {
    "id": "[\"terms\",\"prefix\",\"Bradycardia\"]",
    "kind": "terms",
    "deck": "prefix",
    "front": "Bradycardia",
    "legacy": "prefix|Bradycardia"
  },
  {
    "id": "[\"terms\",\"prefix\",\"Tachycardia\"]",
    "kind": "terms",
    "deck": "prefix",
    "front": "Tachycardia",
    "legacy": "prefix|Tachycardia"
  },
  {
    "id": "[\"terms\",\"prefix\",\"Hypertension\"]",
    "kind": "terms",
    "deck": "prefix",
    "front": "Hypertension",
    "legacy": "prefix|Hypertension"
  },
  {
    "id": "[\"terms\",\"prefix\",\"Hypoglycemia\"]",
    "kind": "terms",
    "deck": "prefix",
    "front": "Hypoglycemia",
    "legacy": "prefix|Hypoglycemia"
  },
  {
    "id": "[\"terms\",\"prefix\",\"Hyperglycemia\"]",
    "kind": "terms",
    "deck": "prefix",
    "front": "Hyperglycemia",
    "legacy": "prefix|Hyperglycemia"
  },
  {
    "id": "[\"terms\",\"prefix\",\"Dyspnea\"]",
    "kind": "terms",
    "deck": "prefix",
    "front": "Dyspnea",
    "legacy": "prefix|Dyspnea"
  },
  {
    "id": "[\"terms\",\"prefix\",\"Apnea\"]",
    "kind": "terms",
    "deck": "prefix",
    "front": "Apnea",
    "legacy": "prefix|Apnea"
  },
  {
    "id": "[\"terms\",\"prefix\",\"Tachypnea\"]",
    "kind": "terms",
    "deck": "prefix",
    "front": "Tachypnea",
    "legacy": "prefix|Tachypnea"
  },
  {
    "id": "[\"terms\",\"prefix\",\"Bradypnea\"]",
    "kind": "terms",
    "deck": "prefix",
    "front": "Bradypnea",
    "legacy": "prefix|Bradypnea"
  },
  {
    "id": "[\"terms\",\"prefix\",\"Aphasia\"]",
    "kind": "terms",
    "deck": "prefix",
    "front": "Aphasia",
    "legacy": "prefix|Aphasia"
  },
  {
    "id": "[\"terms\",\"prefix\",\"Antibiotic\"]",
    "kind": "terms",
    "deck": "prefix",
    "front": "Antibiotic",
    "legacy": "prefix|Antibiotic"
  },
  {
    "id": "[\"terms\",\"prefix\",\"Anticoagulant\"]",
    "kind": "terms",
    "deck": "prefix",
    "front": "Anticoagulant",
    "legacy": "prefix|Anticoagulant"
  },
  {
    "id": "[\"terms\",\"prefix\",\"Antihypertensive\"]",
    "kind": "terms",
    "deck": "prefix",
    "front": "Antihypertensive",
    "legacy": "prefix|Antihypertensive"
  },
  {
    "id": "[\"terms\",\"prefix\",\"Antipyretic\"]",
    "kind": "terms",
    "deck": "prefix",
    "front": "Antipyretic",
    "legacy": "prefix|Antipyretic"
  },
  {
    "id": "[\"terms\",\"prefix\",\"Antiseptic\"]",
    "kind": "terms",
    "deck": "prefix",
    "front": "Antiseptic",
    "legacy": "prefix|Antiseptic"
  },
  {
    "id": "[\"terms\",\"prefix\",\"Antitussive\"]",
    "kind": "terms",
    "deck": "prefix",
    "front": "Antitussive",
    "legacy": "prefix|Antitussive"
  },
  {
    "id": "[\"terms\",\"prefix\",\"Bilateral\"]",
    "kind": "terms",
    "deck": "prefix",
    "front": "Bilateral",
    "legacy": "prefix|Bilateral"
  },
  {
    "id": "[\"terms\",\"prefix\",\"Unilateral\"]",
    "kind": "terms",
    "deck": "prefix",
    "front": "Unilateral",
    "legacy": "prefix|Unilateral"
  },
  {
    "id": "[\"terms\",\"prefix\",\"Contralateral\"]",
    "kind": "terms",
    "deck": "prefix",
    "front": "Contralateral",
    "legacy": "prefix|Contralateral"
  },
  {
    "id": "[\"terms\",\"prefix\",\"Ipsilateral\"]",
    "kind": "terms",
    "deck": "prefix",
    "front": "Ipsilateral",
    "legacy": "prefix|Ipsilateral"
  },
  {
    "id": "[\"terms\",\"prefix\",\"Hypercapnia\"]",
    "kind": "terms",
    "deck": "prefix",
    "front": "Hypercapnia",
    "legacy": "prefix|Hypercapnia"
  },
  {
    "id": "[\"terms\",\"prefix\",\"Hypocapnia\"]",
    "kind": "terms",
    "deck": "prefix",
    "front": "Hypocapnia",
    "legacy": "prefix|Hypocapnia"
  },
  {
    "id": "[\"terms\",\"prefix\",\"Hyperkalemia\"]",
    "kind": "terms",
    "deck": "prefix",
    "front": "Hyperkalemia",
    "legacy": "prefix|Hyperkalemia"
  },
  {
    "id": "[\"terms\",\"prefix\",\"Hypokalemia\"]",
    "kind": "terms",
    "deck": "prefix",
    "front": "Hypokalemia",
    "legacy": "prefix|Hypokalemia"
  },
  {
    "id": "[\"terms\",\"prefix\",\"Hypothermia\"]",
    "kind": "terms",
    "deck": "prefix",
    "front": "Hypothermia",
    "legacy": "prefix|Hypothermia"
  },
  {
    "id": "[\"terms\",\"suffix\",\"Cardiology\"]",
    "kind": "terms",
    "deck": "suffix",
    "front": "Cardiology",
    "legacy": "suffix|Cardiology"
  },
  {
    "id": "[\"terms\",\"suffix\",\"Neurology\"]",
    "kind": "terms",
    "deck": "suffix",
    "front": "Neurology",
    "legacy": "suffix|Neurology"
  },
  {
    "id": "[\"terms\",\"suffix\",\"Hematology\"]",
    "kind": "terms",
    "deck": "suffix",
    "front": "Hematology",
    "legacy": "suffix|Hematology"
  },
  {
    "id": "[\"terms\",\"suffix\",\"Pathology\"]",
    "kind": "terms",
    "deck": "suffix",
    "front": "Pathology",
    "legacy": "suffix|Pathology"
  },
  {
    "id": "[\"terms\",\"suffix\",\"Radiology\"]",
    "kind": "terms",
    "deck": "suffix",
    "front": "Radiology",
    "legacy": "suffix|Radiology"
  },
  {
    "id": "[\"terms\",\"suffix\",\"Oncology\"]",
    "kind": "terms",
    "deck": "suffix",
    "front": "Oncology",
    "legacy": "suffix|Oncology"
  },
  {
    "id": "[\"terms\",\"suffix\",\"Pulmonology\"]",
    "kind": "terms",
    "deck": "suffix",
    "front": "Pulmonology",
    "legacy": "suffix|Pulmonology"
  },
  {
    "id": "[\"terms\",\"suffix\",\"Nephrology\"]",
    "kind": "terms",
    "deck": "suffix",
    "front": "Nephrology",
    "legacy": "suffix|Nephrology"
  },
  {
    "id": "[\"terms\",\"suffix\",\"Gastroenterology\"]",
    "kind": "terms",
    "deck": "suffix",
    "front": "Gastroenterology",
    "legacy": "suffix|Gastroenterology"
  },
  {
    "id": "[\"terms\",\"suffix\",\"Endocrinology\"]",
    "kind": "terms",
    "deck": "suffix",
    "front": "Endocrinology",
    "legacy": "suffix|Endocrinology"
  },
  {
    "id": "[\"terms\",\"suffix\",\"Anesthesiology\"]",
    "kind": "terms",
    "deck": "suffix",
    "front": "Anesthesiology",
    "legacy": "suffix|Anesthesiology"
  },
  {
    "id": "[\"terms\",\"suffix\",\"Dermatitis\"]",
    "kind": "terms",
    "deck": "suffix",
    "front": "Dermatitis",
    "legacy": "suffix|Dermatitis"
  },
  {
    "id": "[\"terms\",\"suffix\",\"Gastritis\"]",
    "kind": "terms",
    "deck": "suffix",
    "front": "Gastritis",
    "legacy": "suffix|Gastritis"
  },
  {
    "id": "[\"terms\",\"suffix\",\"Hepatitis\"]",
    "kind": "terms",
    "deck": "suffix",
    "front": "Hepatitis",
    "legacy": "suffix|Hepatitis"
  },
  {
    "id": "[\"terms\",\"suffix\",\"Bronchitis\"]",
    "kind": "terms",
    "deck": "suffix",
    "front": "Bronchitis",
    "legacy": "suffix|Bronchitis"
  },
  {
    "id": "[\"terms\",\"suffix\",\"Peritonitis\"]",
    "kind": "terms",
    "deck": "suffix",
    "front": "Peritonitis",
    "legacy": "suffix|Peritonitis"
  },
  {
    "id": "[\"terms\",\"suffix\",\"Meningitis\"]",
    "kind": "terms",
    "deck": "suffix",
    "front": "Meningitis",
    "legacy": "suffix|Meningitis"
  },
  {
    "id": "[\"terms\",\"suffix\",\"Arthritis\"]",
    "kind": "terms",
    "deck": "suffix",
    "front": "Arthritis",
    "legacy": "suffix|Arthritis"
  },
  {
    "id": "[\"terms\",\"suffix\",\"Colitis\"]",
    "kind": "terms",
    "deck": "suffix",
    "front": "Colitis",
    "legacy": "suffix|Colitis"
  },
  {
    "id": "[\"terms\",\"suffix\",\"Cystitis\"]",
    "kind": "terms",
    "deck": "suffix",
    "front": "Cystitis",
    "legacy": "suffix|Cystitis"
  },
  {
    "id": "[\"terms\",\"suffix\",\"Phlebitis\"]",
    "kind": "terms",
    "deck": "suffix",
    "front": "Phlebitis",
    "legacy": "suffix|Phlebitis"
  },
  {
    "id": "[\"terms\",\"suffix\",\"Appendectomy\"]",
    "kind": "terms",
    "deck": "suffix",
    "front": "Appendectomy",
    "legacy": "suffix|Appendectomy"
  },
  {
    "id": "[\"terms\",\"suffix\",\"Splenectomy\"]",
    "kind": "terms",
    "deck": "suffix",
    "front": "Splenectomy",
    "legacy": "suffix|Splenectomy"
  },
  {
    "id": "[\"terms\",\"suffix\",\"Hysterectomy\"]",
    "kind": "terms",
    "deck": "suffix",
    "front": "Hysterectomy",
    "legacy": "suffix|Hysterectomy"
  },
  {
    "id": "[\"terms\",\"suffix\",\"Mastectomy\"]",
    "kind": "terms",
    "deck": "suffix",
    "front": "Mastectomy",
    "legacy": "suffix|Mastectomy"
  },
  {
    "id": "[\"terms\",\"suffix\",\"Cholecystectomy\"]",
    "kind": "terms",
    "deck": "suffix",
    "front": "Cholecystectomy",
    "legacy": "suffix|Cholecystectomy"
  },
  {
    "id": "[\"terms\",\"suffix\",\"Gastrectomy\"]",
    "kind": "terms",
    "deck": "suffix",
    "front": "Gastrectomy",
    "legacy": "suffix|Gastrectomy"
  },
  {
    "id": "[\"terms\",\"suffix\",\"Nephrectomy\"]",
    "kind": "terms",
    "deck": "suffix",
    "front": "Nephrectomy",
    "legacy": "suffix|Nephrectomy"
  },
  {
    "id": "[\"terms\",\"suffix\",\"Craniotomy\"]",
    "kind": "terms",
    "deck": "suffix",
    "front": "Craniotomy",
    "legacy": "suffix|Craniotomy"
  },
  {
    "id": "[\"terms\",\"suffix\",\"Tracheotomy\"]",
    "kind": "terms",
    "deck": "suffix",
    "front": "Tracheotomy",
    "legacy": "suffix|Tracheotomy"
  },
  {
    "id": "[\"terms\",\"suffix\",\"Colostomy\"]",
    "kind": "terms",
    "deck": "suffix",
    "front": "Colostomy",
    "legacy": "suffix|Colostomy"
  },
  {
    "id": "[\"terms\",\"suffix\",\"Tracheostomy\"]",
    "kind": "terms",
    "deck": "suffix",
    "front": "Tracheostomy",
    "legacy": "suffix|Tracheostomy"
  },
  {
    "id": "[\"terms\",\"suffix\",\"Hepatomegaly\"]",
    "kind": "terms",
    "deck": "suffix",
    "front": "Hepatomegaly",
    "legacy": "suffix|Hepatomegaly"
  },
  {
    "id": "[\"terms\",\"suffix\",\"Cardiomegaly\"]",
    "kind": "terms",
    "deck": "suffix",
    "front": "Cardiomegaly",
    "legacy": "suffix|Cardiomegaly"
  },
  {
    "id": "[\"terms\",\"suffix\",\"Splenomegaly\"]",
    "kind": "terms",
    "deck": "suffix",
    "front": "Splenomegaly",
    "legacy": "suffix|Splenomegaly"
  },
  {
    "id": "[\"terms\",\"suffix\",\"Lymphadenopathy\"]",
    "kind": "terms",
    "deck": "suffix",
    "front": "Lymphadenopathy",
    "legacy": "suffix|Lymphadenopathy"
  },
  {
    "id": "[\"terms\",\"suffix\",\"Encephalopathy\"]",
    "kind": "terms",
    "deck": "suffix",
    "front": "Encephalopathy",
    "legacy": "suffix|Encephalopathy"
  },
  {
    "id": "[\"terms\",\"suffix\",\"Retinopathy\"]",
    "kind": "terms",
    "deck": "suffix",
    "front": "Retinopathy",
    "legacy": "suffix|Retinopathy"
  },
  {
    "id": "[\"terms\",\"suffix\",\"Myopathy\"]",
    "kind": "terms",
    "deck": "suffix",
    "front": "Myopathy",
    "legacy": "suffix|Myopathy"
  },
  {
    "id": "[\"terms\",\"suffix\",\"Neuropathy\"]",
    "kind": "terms",
    "deck": "suffix",
    "front": "Neuropathy",
    "legacy": "suffix|Neuropathy"
  },
  {
    "id": "[\"terms\",\"suffix\",\"Nephropathy\"]",
    "kind": "terms",
    "deck": "suffix",
    "front": "Nephropathy",
    "legacy": "suffix|Nephropathy"
  },
  {
    "id": "[\"terms\",\"suffix\",\"Cyanosis\"]",
    "kind": "terms",
    "deck": "suffix",
    "front": "Cyanosis",
    "legacy": "suffix|Cyanosis"
  },
  {
    "id": "[\"terms\",\"suffix\",\"Osteoporosis\"]",
    "kind": "terms",
    "deck": "suffix",
    "front": "Osteoporosis",
    "legacy": "suffix|Osteoporosis"
  },
  {
    "id": "[\"terms\",\"suffix\",\"Arteriosclerosis\"]",
    "kind": "terms",
    "deck": "suffix",
    "front": "Arteriosclerosis",
    "legacy": "suffix|Arteriosclerosis"
  },
  {
    "id": "[\"terms\",\"suffix\",\"Nephrosis\"]",
    "kind": "terms",
    "deck": "suffix",
    "front": "Nephrosis",
    "legacy": "suffix|Nephrosis"
  },
  {
    "id": "[\"terms\",\"suffix\",\"Stenosis\"]",
    "kind": "terms",
    "deck": "suffix",
    "front": "Stenosis",
    "legacy": "suffix|Stenosis"
  },
  {
    "id": "[\"terms\",\"suffix\",\"Sclerosis\"]",
    "kind": "terms",
    "deck": "suffix",
    "front": "Sclerosis",
    "legacy": "suffix|Sclerosis"
  },
  {
    "id": "[\"terms\",\"suffix\",\"Kyphosis\"]",
    "kind": "terms",
    "deck": "suffix",
    "front": "Kyphosis",
    "legacy": "suffix|Kyphosis"
  },
  {
    "id": "[\"terms\",\"suffix\",\"Lordosis\"]",
    "kind": "terms",
    "deck": "suffix",
    "front": "Lordosis",
    "legacy": "suffix|Lordosis"
  },
  {
    "id": "[\"terms\",\"suffix\",\"Scoliosis\"]",
    "kind": "terms",
    "deck": "suffix",
    "front": "Scoliosis",
    "legacy": "suffix|Scoliosis"
  },
  {
    "id": "[\"terms\",\"suffix\",\"Leukocytosis\"]",
    "kind": "terms",
    "deck": "suffix",
    "front": "Leukocytosis",
    "legacy": "suffix|Leukocytosis"
  },
  {
    "id": "[\"terms\",\"root\",\"Pneumothorax\"]",
    "kind": "terms",
    "deck": "root",
    "front": "Pneumothorax",
    "legacy": "root|Pneumothorax"
  },
  {
    "id": "[\"terms\",\"root\",\"Hemoptysis\"]",
    "kind": "terms",
    "deck": "root",
    "front": "Hemoptysis",
    "legacy": "root|Hemoptysis"
  },
  {
    "id": "[\"terms\",\"root\",\"Hematemesis\"]",
    "kind": "terms",
    "deck": "root",
    "front": "Hematemesis",
    "legacy": "root|Hematemesis"
  },
  {
    "id": "[\"terms\",\"root\",\"Myocardial Infarction\"]",
    "kind": "terms",
    "deck": "root",
    "front": "Myocardial Infarction",
    "legacy": "root|Myocardial Infarction"
  },
  {
    "id": "[\"terms\",\"root\",\"Cerebrovascular Accident\"]",
    "kind": "terms",
    "deck": "root",
    "front": "Cerebrovascular Accident",
    "legacy": "root|Cerebrovascular Accident"
  },
  {
    "id": "[\"terms\",\"root\",\"Gastroesophageal Reflux\"]",
    "kind": "terms",
    "deck": "root",
    "front": "Gastroesophageal Reflux",
    "legacy": "root|Gastroesophageal Reflux"
  },
  {
    "id": "[\"terms\",\"root\",\"Leukocyte\"]",
    "kind": "terms",
    "deck": "root",
    "front": "Leukocyte",
    "legacy": "root|Leukocyte"
  },
  {
    "id": "[\"terms\",\"root\",\"Erythrocyte\"]",
    "kind": "terms",
    "deck": "root",
    "front": "Erythrocyte",
    "legacy": "root|Erythrocyte"
  },
  {
    "id": "[\"terms\",\"root\",\"Thrombocytopenia\"]",
    "kind": "terms",
    "deck": "root",
    "front": "Thrombocytopenia",
    "legacy": "root|Thrombocytopenia"
  },
  {
    "id": "[\"terms\",\"root\",\"Otitis Media\"]",
    "kind": "terms",
    "deck": "root",
    "front": "Otitis Media",
    "legacy": "root|Otitis Media"
  },
  {
    "id": "[\"terms\",\"root\",\"Nephritis\"]",
    "kind": "terms",
    "deck": "root",
    "front": "Nephritis",
    "legacy": "root|Nephritis"
  },
  {
    "id": "[\"terms\",\"root\",\"Gastroscopy\"]",
    "kind": "terms",
    "deck": "root",
    "front": "Gastroscopy",
    "legacy": "root|Gastroscopy"
  },
  {
    "id": "[\"terms\",\"root\",\"Bronchoscopy\"]",
    "kind": "terms",
    "deck": "root",
    "front": "Bronchoscopy",
    "legacy": "root|Bronchoscopy"
  },
  {
    "id": "[\"terms\",\"root\",\"Colonoscopy\"]",
    "kind": "terms",
    "deck": "root",
    "front": "Colonoscopy",
    "legacy": "root|Colonoscopy"
  },
  {
    "id": "[\"terms\",\"root\",\"Arthroscopy\"]",
    "kind": "terms",
    "deck": "root",
    "front": "Arthroscopy",
    "legacy": "root|Arthroscopy"
  },
  {
    "id": "[\"terms\",\"root\",\"Laparoscopy\"]",
    "kind": "terms",
    "deck": "root",
    "front": "Laparoscopy",
    "legacy": "root|Laparoscopy"
  },
  {
    "id": "[\"terms\",\"root\",\"Cystoscopy\"]",
    "kind": "terms",
    "deck": "root",
    "front": "Cystoscopy",
    "legacy": "root|Cystoscopy"
  },
  {
    "id": "[\"terms\",\"root\",\"Electrocardiogram\"]",
    "kind": "terms",
    "deck": "root",
    "front": "Electrocardiogram",
    "legacy": "root|Electrocardiogram"
  },
  {
    "id": "[\"terms\",\"root\",\"Electroencephalogram\"]",
    "kind": "terms",
    "deck": "root",
    "front": "Electroencephalogram",
    "legacy": "root|Electroencephalogram"
  },
  {
    "id": "[\"terms\",\"root\",\"Mammogram\"]",
    "kind": "terms",
    "deck": "root",
    "front": "Mammogram",
    "legacy": "root|Mammogram"
  },
  {
    "id": "[\"terms\",\"root\",\"Angiogram\"]",
    "kind": "terms",
    "deck": "root",
    "front": "Angiogram",
    "legacy": "root|Angiogram"
  },
  {
    "id": "[\"terms\",\"root\",\"Myelogram\"]",
    "kind": "terms",
    "deck": "root",
    "front": "Myelogram",
    "legacy": "root|Myelogram"
  },
  {
    "id": "[\"terms\",\"root\",\"Cephalgia\"]",
    "kind": "terms",
    "deck": "root",
    "front": "Cephalgia",
    "legacy": "root|Cephalgia"
  },
  {
    "id": "[\"terms\",\"root\",\"Neuralgia\"]",
    "kind": "terms",
    "deck": "root",
    "front": "Neuralgia",
    "legacy": "root|Neuralgia"
  },
  {
    "id": "[\"terms\",\"root\",\"Myalgia\"]",
    "kind": "terms",
    "deck": "root",
    "front": "Myalgia",
    "legacy": "root|Myalgia"
  }
];
