'use strict';
const PEER_PREFIX='ej-fieldnotes-live-', bank=(window.STUDY_CLINICAL_CARDS||[]).filter(q=>Array.isArray(q.options)&&q.options.length>=2&&Array.isArray(q.answer)&&q.answer.length===1);
let host=null,player={peer:null,conn:null,name:'',index:-1},lastResults=[],draftQuestions=[];
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function view(id){document.querySelectorAll('.ic-view').forEach(v=>v.classList.remove('active'));$('#ic-'+id).classList.add('active');}
function sub(prefix,id){document.querySelectorAll('#ic-'+prefix+' > [id]').forEach(x=>x.hidden=true);$('#'+id).hidden=false;}
function cleanup(){if(host){host.destroy();host=null}if(player.peer){player.peer.destroy();player.peer=null;player.conn=null}}
document.querySelectorAll('[data-go="home"]').forEach(b=>b.onclick=()=>{cleanup();view('home')});
$('#ic-host-open').onclick=()=>view('builder');
const sections=[...new Set(bank.map(q=>q.section).filter(Boolean))].sort();sections.forEach(x=>$('#host-section').add(new Option(x,x)));
function refreshCats(){const sec=$('#host-section').value,cats=[...new Set(bank.filter(q=>sec==='All'||q.section===sec).map(q=>q.category).filter(Boolean))].sort();$('#host-category').innerHTML='<option value="All">All categories</option>';cats.forEach(x=>$('#host-category').add(new Option(x,x)));refreshStatus()}
function filteredBank(){const s=$('#host-section').value,c=$('#host-category').value;return bank.filter(q=>(s==='All'||q.section===s)&&(c==='All'||q.category===c))}
function refreshStatus(){const n=filteredBank().length;$('#bank-status').textContent=n+' live-ready multiple-choice questions available.'}
$('#host-section').onchange=refreshCats;$('#host-category').onchange=refreshStatus;refreshCats();
function shuffled(a){a=[...a];for(let i=a.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function makeDraft(q){return {text:q.q||'',answers:[...(q.options||[])],correct:Math.max(0,(q.options||[]).indexOf(Array.isArray(q.answer)?q.answer[0]:q.answer)),rationale:q.rationale||'',category:q.category||'Custom'}}
function renderEditor(){const list=$('#editor-list');list.innerHTML=draftQuestions.map((q,i)=>'<article class="ic-edit-card" data-i="'+i+'"><div class="ic-edit-head"><strong>Question '+(i+1)+'</strong><button type="button" class="ic-remove" data-remove="'+i+'">Remove</button></div><label>Question<textarea data-field="text">'+esc(q.text)+'</textarea></label><div class="ic-answer-edit">'+q.answers.map((a,k)=>'<label class="ic-answer-row"><input type="radio" name="correct-'+i+'" value="'+k+'" '+(q.correct===k?'checked':'')+' aria-label="Correct answer"><span>'+String.fromCharCode(65+k)+'</span><input data-answer="'+k+'" value="'+esc(a)+'"></label>').join('')+'</div><label>Rationale<textarea data-field="rationale">'+esc(q.rationale)+'</textarea></label></article>').join('');list.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{if(draftQuestions.length<=1){$('#editor-error').textContent='A review needs at least one question.';return}draftQuestions.splice(+b.dataset.remove,1);renderEditor()});list.querySelectorAll('.ic-edit-card').forEach(card=>{const i=+card.dataset.i;card.querySelectorAll('[data-field]').forEach(x=>x.oninput=()=>draftQuestions[i][x.dataset.field]=x.value);card.querySelectorAll('[data-answer]').forEach(x=>x.oninput=()=>draftQuestions[i].answers[+x.dataset.answer]=x.value);card.querySelectorAll('input[type=radio]').forEach(x=>x.onchange=()=>draftQuestions[i].correct=+x.value)})}
$('#host-start').onclick=()=>{const pool=filteredBank(),n=Math.min(+$('#host-count').value,pool.length);if(!n)return;draftQuestions=shuffled(pool).slice(0,n).map(makeDraft);$('#editor-error').textContent='';renderEditor();view('editor')};
$('#editor-back').onclick=()=>view('builder');
$('#editor-add').onclick=()=>{draftQuestions.push({text:'',answers:['','','',''],correct:0,rationale:'',category:'Custom'});renderEditor();setTimeout(()=>document.querySelector('.ic-edit-card:last-child textarea')?.focus(),0)};
$('#editor-launch').onclick=()=>{const invalid=draftQuestions.find(q=>!q.text.trim()||q.answers.length<2||q.answers.some(a=>!a.trim())||q.correct<0||q.correct>=q.answers.length);if(invalid){$('#editor-error').textContent='Each question needs wording, all answer choices, and one correct answer.';return}const qs=draftQuestions.map(q=>({text:q.text.trim(),answers:q.answers.map(a=>a.trim()),correct:q.correct,rationale:q.rationale.trim(),category:q.category||'Custom'}));host=new Host(qs,+$('#host-time').value,$('#host-points').checked);view('host');host.open()};
class Host{
 constructor(qs,time,points){this.qs=qs;this.time=time;this.points=points;this.players=new Map();this.i=-1;this.phase='lobby';this.timer=null;this.stats=qs.map(()=>({answers:[],correct:0}));}
 open(){sub('host','host-status');this.pin=String(Math.floor(100000+Math.random()*900000));this.peer=new Peer(PEER_PREFIX+this.pin);this.peer.on('open',()=>this.lobby());this.peer.on('connection',c=>this.connect(c));this.peer.on('error',e=>{$('#host-status').innerHTML='<h2>Connection problem</h2><p>'+esc(e.type)+'</p><button class="mode-btn" data-retry>Try again</button>';$('#host-status [data-retry]').onclick=()=>location.reload()})}
 connect(c){c.on('data',d=>this.message(c,d));c.on('close',()=>{this.players.delete(c.connectionId);this.renderPlayers()})}
 message(c,d){if(!d||typeof d!=='object')return;if(d.t==='join'){let name=String(d.name||'Learner').trim().slice(0,20),base=name,n=2,names=new Set([...this.players.values()].map(p=>p.name.toLowerCase()));while(names.has(name.toLowerCase()))name=base.slice(0,16)+' '+n++;this.players.set(c.connectionId,{conn:c,name,score:0,choice:null,ms:0});c.send({t:'welcome',name});this.renderPlayers()}else if(d.t==='a'&&this.phase==='question'&&d.i===this.i){const p=this.players.get(c.connectionId);if(!p||p.choice!==null)return;p.choice=+d.c;p.ms=Date.now()-this.started;$('#hq-answered').textContent=[...this.players.values()].filter(x=>x.choice!==null).length}}
 broadcast(d){for(const p of this.players.values())if(p.conn.open)p.conn.send(d)}
 lobby(){sub('host','host-lobby');$('#host-pin').textContent=this.pin;const qr=qrcode(0,'M');qr.addData(location.href.split('#')[0]+'?join='+this.pin);qr.make();$('#host-qr').innerHTML=qr.createSvgTag({cellSize:3,margin:2});this.renderPlayers();$('#host-begin').onclick=()=>this.question(0)}
 renderPlayers(){$('#host-players').innerHTML=[...this.players.values()].map(p=>'<span>'+esc(p.name)+'</span>').join('');$('#host-count-num').textContent=this.players.size;$('#host-begin').disabled=!this.players.size}
 question(i){this.i=i;this.phase='question';for(const p of this.players.values()){p.choice=null;p.ms=0}const q=this.qs[i];this.started=Date.now();this.broadcast({t:'q',i,n:this.qs.length,text:q.text,answers:q.answers,time:this.time});sub('host','host-question');$('#hq-progress').textContent='Question '+(i+1)+' of '+this.qs.length;$('#hq-text').textContent=q.text;$('#hq-answered').textContent='0';$('#hq-options').innerHTML=q.answers.map((a,k)=>'<div class="ic-option">'+String.fromCharCode(65+k)+'. '+esc(a)+'</div>').join('');$('#hq-reveal').onclick=()=>this.reveal();clearInterval(this.timer);if(this.time){let end=this.started+this.time*1000;const tick=()=>{let left=Math.max(0,Math.ceil((end-Date.now())/1000));$('#hq-timer').textContent=left+' sec';if(!left)this.reveal()};tick();this.timer=setInterval(tick,250)}else $('#hq-timer').textContent='Instructor paced'}
 reveal(){if(this.phase!=='question')return;this.phase='reveal';clearInterval(this.timer);const q=this.qs[this.i],ps=[...this.players.values()],counts=q.answers.map((_,k)=>ps.filter(p=>p.choice===k).length);let correct=0;ps.forEach(p=>{const ok=p.choice===q.correct;if(ok){correct++;p.score+=this.points?Math.max(500,1000-Math.floor(p.ms/Math.max(1,this.time*1000)*500)):1}p.conn.open&&p.conn.send({t:'reveal',ok,correct:q.correct,rationale:q.rationale,score:p.score,points:this.points})});this.stats[this.i]={answers:counts,correct,total:ps.length};sub('host','host-reveal');$('#hr-progress').textContent='Question '+(this.i+1)+' results';$('#hr-text').textContent=q.text;$('#hr-options').innerHTML=q.answers.map((a,k)=>'<div class="ic-option '+(k===q.correct?'correct':'wrong')+'">'+String.fromCharCode(65+k)+'. '+esc(a)+' <span class="count">'+counts[k]+'</span></div>').join('');$('#hr-rationale').innerHTML='<strong>Why:</strong> '+esc(q.rationale||'No rationale provided.');$('#hr-next').textContent=this.i===this.qs.length-1?'Finish Review':'Next Question';$('#hr-next').onclick=()=>this.i===this.qs.length-1?this.end():this.question(this.i+1)}
 end(){this.phase='end';const ps=[...this.players.values()];this.broadcast({t:'end'});lastResults=ps.map(p=>({name:p.name,score:p.score}));sub('host','host-end');const total=this.stats.reduce((a,s)=>a+s.total,0),correct=this.stats.reduce((a,s)=>a+s.correct,0);$('#host-summary').innerHTML='<p><strong>'+ps.length+'</strong> learners · <strong>'+this.qs.length+'</strong> questions · <strong>'+(total?Math.round(correct/total*100):0)+'%</strong> class accuracy</p>'+this.stats.map((s,i)=>'<p>Q'+(i+1)+': '+(s.total?Math.round(s.correct/s.total*100):0)+'% correct — '+esc(this.qs[i].category)+'</p>').join('');$('#download-results').onclick=()=>this.csv()}
 csv(){let rows=[['Learner',this.points?'Score':'Correct Answers'],...lastResults.map(x=>[x.name,x.score])];let blob=new Blob([rows.map(r=>r.map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(',')).join('\n')],{type:'text/csv'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='field-notes-live-review.csv';a.click();URL.revokeObjectURL(a.href)}
 destroy(){clearInterval(this.timer);if(this.peer)this.peer.destroy()}
}
function join(){const pin=$('#join-pin').value.replace(/\D/g,''),name=$('#join-name').value.trim();if(pin.length!==6||!name){$('#join-error').textContent='Enter a six-digit code and your name.';return}cleanup();player.name=name;player.peer=new Peer();player.peer.on('open',()=>{const c=player.peer.connect(PEER_PREFIX+pin,{reliable:true});player.conn=c;c.on('open',()=>c.send({t:'join',name}));c.on('data',playerMsg);c.on('close',()=>{view('player');sub('player','player-dropped')})});player.peer.on('error',e=>{$('#join-error').textContent=e.type==='peer-unavailable'?'Session not found. Check the code.':'Could not connect. Check your internet connection.'})}
$('#join-btn').onclick=join;$('#join-name').onkeydown=e=>{if(e.key==='Enter')join()};
function playerMsg(d){if(!d||typeof d!=='object')return;view('player');if(d.t==='welcome'){player.name=d.name;$('#player-name').textContent=d.name;sub('player','player-wait')}else if(d.t==='q'){player.index=d.i;sub('player','player-question');$('#pq-progress').textContent='Question '+(d.i+1)+' of '+d.n;$('#pq-text').textContent=d.text;$('#pq-timer').textContent=d.time?d.time+' sec':'Take your time';$('#pq-options').innerHTML=d.answers.map((a,k)=>'<button class="ic-option player" data-c="'+k+'">'+String.fromCharCode(65+k)+'. '+esc(a)+'</button>').join('');$('#pq-options').querySelectorAll('button').forEach(b=>b.onclick=()=>{if(player.conn&&player.conn.open){player.conn.send({t:'a',i:player.index,c:+b.dataset.c});sub('player','player-locked')}})}else if(d.t==='reveal'){sub('player','player-result');$('#pr-verdict').textContent=d.ok?'Correct ✓':'Not this one';$('#pr-detail').textContent=d.points?'Current score: '+d.score:'The correct answer is shown on the instructor screen.';$('#pr-rationale').innerHTML='<strong>Why:</strong> '+esc(d.rationale||'Review the answer with your instructor.')}else if(d.t==='end'){sub('player','player-end');$('#pe-score').textContent='Thanks for reviewing, '+player.name+'.'}}
const params=new URLSearchParams(location.search);if(params.get('join')){$('#join-pin').value=params.get('join').replace(/\D/g,'').slice(0,6);$('#join-name').focus()}
