/* Explicit local-file transfer. Only student progress keys are restored. */
(()=>{'use strict';const keys=['field_notes_study_v1','field_notes_cards_v1','field_notes_finding_v1','field_notes_order_v1','field_notes_quick_v1','field_notes_plan_v1','field_notes_badges_v1','field_notes_streak_v1'];const host=document.getElementById('progress-backup');if(!host)return;const node=(tag,text)=>{const n=document.createElement(tag);if(text)n.textContent=text;return n;};
host.append(node('h3','💾 Back Up My Progress'),node('p','Download a progress file, keep it in Files or your own cloud drive, and restore it on another device. This is a manual backup, not automatic syncing. It includes student progress, badges, streaks, and study plans; live instructor quizzes are separate.'));
const status=node('p');status.setAttribute('role','status');const download=node('button','Download Backup');download.type='button';download.className='study-button';download.onclick=()=>{try{const data={};for(const key of keys){const text=localStorage.getItem(key);if(text!==null){const value=JSON.parse(text);if(value?.version===1)data[key]=value;}}const blob=new Blob([JSON.stringify({app:'eric-field-notes-progress',version:1,createdAt:new Date().toISOString(),data},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=node('a');a.href=url;a.download='field-notes-progress-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);status.textContent='Backup downloaded. Save this file so you can restore it later.';}catch{status.textContent='Could not read saved progress. Your existing data has not been changed.';}};
const input=node('input');input.type='file';input.accept='.json,application/json';input.id='progress-backup-file';const label=node('label','Choose a saved backup to restore');label.htmlFor=input.id;const restore=node('button','Restore Backup');restore.type='button';restore.className='study-button';restore.disabled=true;let pending;
input.onchange=async()=>{restore.disabled=true;pending=null;const f=input.files[0];if(!f)return;try{if(f.size>5*1024*1024)throw Error();const raw=JSON.parse(await f.text());if(raw.app!=='eric-field-notes-progress'||raw.version!==1||!raw.data||Array.isArray(raw.data)||typeof raw.data!=='object')throw Error();const entries=Object.entries(raw.data);if(!entries.length||entries.some(([k,v])=>!keys.includes(k)||!v||Array.isArray(v)||typeof v!=='object'||v.version!==1))throw Error();pending=entries;restore.disabled=false;status.textContent=`Ready to restore ${entries.length} saved progress sections. Restoring replaces those sections on this device.`;}catch{status.textContent='This is not a supported progress backup. Nothing was changed.';}};
restore.onclick=()=>{if(!pending||!confirm('Replace the saved progress sections on this device with this backup? Download your current progress first if you want to keep it.'))return;const old=new Map();try{for(const [key]of pending)old.set(key,localStorage.getItem(key));for(const [key,value]of pending)localStorage.setItem(key,JSON.stringify(value));status.textContent='Progress restored. Reloading your dashboard…';location.reload();}catch{try{for(const [key,value]of old)if(value===null)localStorage.removeItem(key);else localStorage.setItem(key,value);}catch{}status.textContent='Restore could not finish. Storage may be unavailable or full. Please keep your backup file.';}};
host.append(download,label,input,restore,status);
})();
