(()=>{
 'use strict';
 const KEY='field_notes_quick_v1',items=window.QUICK_STUDY_ITEMS||[],byId=new Map(items.map(x=>[x.id,x])),challenges=(window.CHANGE_FINDING_CASES||[]).filter(c=>['effective-cough','adult-pulse','pediatric-rate','infant-response'].includes(c.id)),caseMap=new Map(challenges.map(c=>[c.id,c]));
 const $=id=>document.getElementById(id),blank=()=>({version:1,records:{},history:[],session:null});let state=blank(),running=false,available=true,lastTick=0;
 const allowedConfidence=v=>['confident','unsure','guessing'].includes(v);
 function validStep(t,level){return t&&(['question','card'].includes(t.kind)?byId.has(t.id)&&(level==='AEMT'||byId.get(t.id).minLevel==='EMT'):t.kind==='challenge'&&caseMap.has(t.id)&&[0,1].includes(t.variant));}
 try{const raw=JSON.parse(localStorage.getItem(KEY));if(raw?.version===1){for(const [key,r]of Object.entries(raw.records||{}))if(r&&allowedConfidence(r.confidence)&&[true,false,null].includes(r.correct))state.records[key]=r;state.history=Array.isArray(raw.history)?raw.history.filter(h=>h&&Number.isFinite(h.date)&&Number.isInteger(h.graded)&&Number.isInteger(h.correct)).slice(-50):[];const s=raw.session;if(s&&['EMT','AEMT'].includes(s.level)&&Array.isArray(s.queue)&&s.queue.length===8&&new Set(s.queue.map(key)).size===8&&s.queue.every(t=>validStep(t,s.level))&&Number.isInteger(s.index)&&s.index>=0&&s.index<8&&Number.isFinite(s.remaining)&&s.remaining>=0&&s.remaining<=600000&&s.responses&&typeof s.responses==='object'){s.draft=s.draft&&typeof s.draft==='object'?s.draft:{};
 const clean={};for(const t of s.queue){const r=s.responses[key(t)],v=view(t);if(r&&allowedConfidence(r.confidence)&&(t.kind==='card'||Number.isInteger(r.choice)&&r.choice>=0&&r.choice<v.choices.length)){clean[key(t)]={confidence:r.confidence,choice:t.kind==='card'?null:r.choice,correct:t.kind==='card'?null:r.choice===v.correct,date:Number.isFinite(r.date)?r.date:Date.now(),level:s.level,...(typeof r.recall==='boolean'?{recall:r.recall}:{})};}}s.responses=clean;state.session=s;}}}catch(e){if(!(e instanceof SyntaxError))available=false;}
 function key(t){return t.kind+':'+t.id+(t.kind==='challenge'?':'+t.variant:'');}
 function save(){try{localStorage.setItem(KEY,JSON.stringify(state));available=true;}catch{available=false;}$('quick-storage').textContent=available?'Saved in this browser on this device.':'This browser cannot save progress. You can still study.';}
 function current(){return state.session?.queue[state.session.index];}
 function view(t){if(t.kind==='challenge'){const c=caseMap.get(t.id),v=c.variants[t.variant];return {front:c.prompt,scene:c.scene,finding:v.finding,choices:c.choices,correct:v.correct,answer:c.choices[v.correct],note:v.note,sources:[{label:c.source.label,url:c.source.url}],scope:items[0].scope};}return byId.get(t.id);}
 function externalPriority(x){try{const quiz=JSON.parse(localStorage.getItem('field_notes_study_v1'));if(Array.isArray(quiz?.missed)&&quiz.missed.some(k=>{try{return JSON.parse(k)[3]===x.front;}catch{return false;}}))return 2;const s=JSON.parse(localStorage.getItem('field_notes_cards_v1'));const ids=(window.FIELD_NOTE_CARDS||[]).filter(c=>c.front===x.front).map(c=>c.id);return ids.some(id=>{const r=s?.records?.[id];return r&&(r.difficult===true||(['again','hard'].includes(r.rating)&&r.difficult!==false)||r.due<=Date.now());})?1:0;}catch{return 0;}}
 function priority(t){const r=state.records[key(t)];return (r?.correct===false&&r.confidence==='confident'?5:r?.correct===false||r?.recall===false?4:r?.due<=Date.now()?3:!r?2:0)+externalPriority(byId.get(t.id)||{});}
 function shuffle(a){return a.map(x=>({x,n:Math.random()})).sort((a,b)=>a.n-b.n).map(o=>o.x);}
 function start(){if(state.session&&!confirm('Replace your unfinished short session?'))return;const level=$('quick-level').value,eligible=items.filter(x=>level==='AEMT'||x.minLevel==='EMT');let qs=shuffle(eligible.map(x=>({kind:'question',id:x.id}))).sort((a,b)=>priority(b)-priority(a)).slice(0,3);if(level==='AEMT'&&!qs.some(t=>byId.get(t.id).minLevel==='AEMT'))qs[2]={kind:'question',id:shuffle(eligible.filter(x=>x.minLevel==='AEMT'))[0].id};const cards=shuffle(eligible.filter(x=>!qs.some(q=>q.id===x.id)).map(x=>({kind:'card',id:x.id}))).sort((a,b)=>priority(b)-priority(a)).slice(0,3);const c=shuffle(challenges)[0];state.session={level,queue:[...qs,...cards,{kind:'challenge',id:c.id,variant:0},{kind:'challenge',id:c.id,variant:1}],index:0,remaining:600000,responses:{},draft:{}};save();resume();}
 function clock(){const ms=state.session?.remaining??600000,s=Math.ceil(ms/1000);$('quick-clock').textContent=Math.floor(s/60)+':'+String(s%60).padStart(2,'0');}
 function tick(){if(!running||!state.session)return;const now=Date.now();state.session.remaining=Math.max(0,state.session.remaining-(now-lastTick));lastTick=now;clock();if(state.session.remaining===0)$('quick-time-status').textContent='Your 10-minute budget is reached. Finish this item or choose Finish Early.';}
 function pause(){tick();running=false;save();}
 function resume(){if(!state.session)return;running=true;lastTick=Date.now();$('quick-setup').hidden=true;$('quick-summary').hidden=true;$('quick-session').hidden=false;render();}
 function render(){const s=state.session,t=current(),v=view(t),r=s.responses[key(t)],draft=s.draft||{};$('quick-step').textContent=`${s.level} · ${s.index+1}/8 · ${t.kind==='card'?'Recall card':t.kind==='challenge'?'Change One Finding':'Practice question'}`;$('quick-front').textContent=v.front;$('quick-scene').textContent=v.scene||'';$('quick-finding').hidden=!v.finding;$('quick-finding').textContent=v.finding||'';$('quick-options').replaceChildren();
 if(t.kind!=='card')v.choices.forEach((choice,i)=>{const label=document.createElement('label'),input=document.createElement('input');input.type='radio';input.name='quick-answer';input.value=i;input.checked=(r?.choice??draft.choice)===i;input.disabled=!!r;input.onchange=()=>{s.draft={...s.draft,choice:i};save();};label.append(input,document.createTextNode(' '+choice));$('quick-options').append(label);});
 document.querySelectorAll('input[name="confidence"]').forEach(n=>{n.checked=n.value===(r?.confidence??draft.confidence);n.disabled=!!r;n.onchange=()=>{s.draft={...s.draft,confidence:n.value};save();};});
 $('quick-error').textContent='';$('quick-submit').hidden=!!r;$('quick-submit').textContent=t.kind==='card'?'Reveal Answer':'Check Answer';$('quick-feedback').hidden=!r;
 if(r){$('quick-result').textContent=t.kind==='card'?'Compare your recall with the answer':r.correct?'✓ Correct':'Review the deciding clue';$('quick-answer').textContent='Answer: '+v.answer;$('quick-note').textContent=v.note;$('quick-sources').replaceChildren();for(const src of [...v.sources,v.scope]){const a=document.createElement('a');a.textContent=src.label;a.href=src.url;a.target='_blank';a.rel='noopener noreferrer';$('quick-sources').append(a);}$('quick-card-rating').hidden=t.kind!=='card';$('quick-known').setAttribute('aria-pressed',String(r.recall===true));$('quick-difficult').setAttribute('aria-pressed',String(r.recall===false));$('quick-next').disabled=t.kind==='card'&&typeof r.recall!=='boolean';}clock();}
 function submit(){const s=state.session,t=current(),v=view(t),d=s.draft||{};if(!allowedConfidence(d.confidence)||(t.kind!=='card'&&!Number.isInteger(d.choice))){$('quick-error').textContent='Choose your answer and confidence before checking. For cards, choose confidence before revealing.';return;}if(s.responses[key(t)])return;const r={confidence:d.confidence,choice:t.kind==='card'?null:d.choice,correct:t.kind==='card'?null:d.choice===v.correct,date:Date.now(),level:s.level};s.responses[key(t)]=r;state.records[key(t)]={...r,due:Date.now()+(r.correct===false?600000:86400000)};save();render();dashboard();}
 function rate(recall){const t=current(),r=state.session.responses[key(t)];if(t.kind!=='card'||!r)return;r.recall=recall;state.records[key(t)]={...r,due:Date.now()+(recall?86400000:600000)};save();render();dashboard();}
 function finish(){if(!state.session)return;pause();const s=state.session,rs=Object.values(s.responses),graded=rs.filter(r=>typeof r.correct==='boolean'),h={date:Date.now(),level:s.level,graded:graded.length,correct:graded.filter(r=>r.correct).length,tried:rs.length,confidentErrors:graded.filter(r=>!r.correct&&r.confidence==='confident').length};state.history.push(h);state.history=state.history.slice(-50);state.session=null;save();$('quick-session').hidden=true;$('quick-summary').hidden=false;$('quick-summary-text').textContent=`${h.tried}/8 items tried · ${h.correct}/${h.graded} scored answers correct · ${h.confidentErrors} confident mistakes. Card recall is self-rated.`;$('quick-confident-errors').textContent=h.confidentErrors?'Review the confident mistakes below on your next visit.':'Keep checking both your answer and your confidence.';dashboard();}
 function dashboard(){const errors=Object.entries(state.records).filter(([,r])=>r.correct===false&&r.confidence==='confident');$('quick-dashboard').replaceChildren();if(!errors.length)$('quick-dashboard').textContent='No current confident mistakes from short sessions.';for(const [k,r]of errors){let title='Clinical challenge';const q=items.find(x=>k==='question:'+x.id);if(q)title=q.front;else for(const c of challenges)if(k.startsWith('challenge:'+c.id+':'))title=c.title;const p=document.createElement('p');p.textContent=`${r.level} · ${title} — revisit this confident mistake`;$('quick-dashboard').append(p);}$('quick-resume').hidden=!state.session;}
 $('quick-start').onclick=start;$('quick-resume').onclick=resume;$('quick-submit').onclick=submit;$('quick-known').onclick=()=>rate(true);$('quick-difficult').onclick=()=>rate(false);$('quick-next').onclick=()=>{tick();if(state.session.index===7||state.session.remaining===0){finish();return;}state.session.index++;state.session.draft={};save();render();};$('quick-exit').onclick=()=>{pause();$('quick-session').hidden=true;$('quick-setup').hidden=false;dashboard();};$('quick-finish').onclick=finish;$('quick-another').onclick=()=>{$('quick-summary').hidden=true;$('quick-setup').hidden=false;$('quick-time-status').textContent='';clock();};
 document.addEventListener('visibilitychange',()=>{if(document.hidden){pause();}else if(state.session&&!$('quick-session').hidden){running=true;lastTick=Date.now();}});window.addEventListener('beforeunload',pause);setInterval(()=>{tick();if(running)save();},1000);
 try{document.body.classList.toggle('dark-mode',localStorage.getItem('ems_theme')==='dark');}catch{}save();dashboard();clock();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
})();
