(()=>{
 'use strict';
 const E=window.StudyPlanEngine,KEY='field_notes_plan_v1',$=id=>document.getElementById(id);
 const now=new Date(),today=now.getFullYear()+'-'+String(now.getMonth()+1).padStart(2,'0')+'-'+String(now.getDate()).padStart(2,'0');
 const defaults=()=>({title:'My Study Plan',start:today,exam:E.dateString(E.dateValue(today)+7*86400000),minutes:60,block:25,weekdays:[0,1,2,3,4,5,6],topics:[{name:'',priority:2}]});
 let state={version:1,form:defaults(),plan:null},available=true,editing=null;
 function safeForm(f){return f&&typeof f.title==='string'&&f.title.length<=100&&typeof f.start==='string'&&typeof f.exam==='string'&&Number.isFinite(f.minutes)&&Number.isFinite(f.block)&&Array.isArray(f.weekdays)&&f.weekdays.every(d=>Number.isInteger(d)&&d>=0&&d<=6)&&Array.isArray(f.topics)&&f.topics.length>=1&&f.topics.length<=20&&f.topics.every(t=>t&&typeof t.name==='string'&&t.name.length<=100&&[1,2,3].includes(t.priority));}
 try{const raw=JSON.parse(localStorage.getItem(KEY));if(raw?.version===1){if(safeForm(raw.form))state.form=raw.form;if(E.validatePlan(raw.plan))state.plan=raw.plan;}}catch(e){if(!(e instanceof SyntaxError))available=false;}
 function save(){try{localStorage.setItem(KEY,JSON.stringify(state));available=true;}catch{available=false;}$('plan-storage').textContent=available?'Your inputs, plan and completed blocks are saved in this browser on this device.':'This browser cannot save your plan. You can still build, print and export it.';}
 function readForm(){return {title:$('plan-name').value.trim(),start:$('plan-start').value,exam:$('plan-exam').value,minutes:Number($('plan-minutes').value),block:Number($('plan-block').value),weekdays:[...document.querySelectorAll('input[name="plan-day"]:checked')].map(n=>Number(n.value)),topics:[...$('plan-topics').children].map(row=>({name:row.querySelector('input').value.trim(),priority:Number(row.querySelector('select').value)}))};}
 function topicRows(){const holder=$('plan-topics');holder.replaceChildren();state.form.topics.forEach((topic,i)=>{const row=document.createElement('div');row.className='plan-topic';const label=document.createElement('label');label.textContent='Topic '+(i+1);const input=document.createElement('input');input.id='plan-topic-'+i;input.maxLength=100;input.placeholder='Chapter, skill, or subject';input.value=topic.name;label.htmlFor=input.id;label.append(input);const priorityLabel=document.createElement('label');priorityLabel.textContent='Priority';const select=document.createElement('select');select.id='plan-priority-'+i;priorityLabel.htmlFor=select.id;for(const [value,text]of [[3,'High'],[2,'Medium'],[1,'Low']]){const o=document.createElement('option');o.value=value;o.textContent=text;select.append(o);}select.value=topic.priority;priorityLabel.append(select);const remove=document.createElement('button');remove.type='button';remove.textContent='Remove';remove.setAttribute('aria-label','Remove topic '+(i+1));remove.disabled=state.form.topics.length===1;remove.onclick=()=>{state.form=readForm();state.form.topics.splice(i,1);topicRows();save();};row.append(label,priorityLabel,remove);holder.append(row);});$('plan-add-topic').disabled=state.form.topics.length>=20;}
 function loadForm(){const f=state.form;for(const [id,value]of [['plan-name',f.title],['plan-start',f.start],['plan-exam',f.exam],['plan-minutes',f.minutes],['plan-block',f.block]])$(id).value=value;document.querySelectorAll('input[name="plan-day"]').forEach(n=>n.checked=f.weekdays.includes(Number(n.value)));$('plan-start').min=today;$('plan-exam').min=E.dateString(E.dateValue(today)+86400000);topicRows();}
 function displayDate(s){return new Intl.DateTimeFormat(undefined,{weekday:'short',month:'short',day:'numeric',year:'numeric',timeZone:'UTC'}).format(new Date(E.dateValue(s)));}
 function summary(){const p=state.plan;if(!p)return;const complete=p.tasks.filter(t=>t.done).length,total=p.tasks.reduce((n,t)=>n+t.minutes,0);$('plan-summary').textContent=`Exam: ${displayDate(p.config.exam)} · ${p.tasks.length} blocks · ${total} study minutes · ${complete}/${p.tasks.length} complete.`;
 const missing=p.config.topics.map((t,i)=>({name:t.name,count:p.tasks.filter(s=>s.topicId==='topic-'+i).length})).filter(t=>t.count<3);$('plan-warning').textContent=missing.length?'Time or spacing is limited. Topics below the preparation + two-review goal: '+missing.map(t=>`${t.name} (${t.count}/3 blocks)`).join('; ')+'. Add study days or time, reduce topics, or revise your plan.':'Every topic has preparation and two reviews on separate study days. This is a schedule, not a prediction of exam readiness.';}
 function renderPlan(){const p=state.plan;$('plan-output').hidden=!p;if(!p)return;$('plan-output-title').textContent=p.config.title;summary();$('plan-days').replaceChildren();for(const date of E.dates(p.config)){const tasks=p.tasks.filter(t=>t.date===date);if(!tasks.length)continue;const day=document.createElement('section');day.className='plan-day';const h=document.createElement('h3');h.textContent=displayDate(date);const budget=document.createElement('p');budget.className='help';budget.textContent=`${E.used(p.tasks,date)} of ${p.config.minutes} available minutes, including breaks.`;day.append(h,budget);for(const task of tasks){const row=document.createElement('div');row.className='plan-task'+(task.done?' done':'');row.dataset.id=task.id;const label=document.createElement('label'),check=document.createElement('input');check.type='checkbox';check.checked=task.done;check.setAttribute('aria-label','Complete '+task.topic+' on '+date);check.onchange=()=>{task.done=check.checked;row.classList.toggle('done',task.done);summary();save();};const content=document.createElement('div');content.className='plan-task-content';const title=document.createElement('strong');title.className='plan-task-title';title.textContent=task.topic+' · '+task.minutes+' min';const method=document.createElement('small');method.textContent=(task.phase==='prepare'?'Preparation':'Review')+' — '+task.method;content.append(title,method);const directions=document.createElement('ol');directions.className='plan-directions';directions.setAttribute('aria-label','Instructions for '+task.topic);for(const step of E.instructions(task)){const li=document.createElement('li');li.textContent=`${step.minutes} min — ${step.text}`;directions.append(li);}content.append(directions);if(task.notes){const notes=document.createElement('span');notes.className='plan-task-notes';notes.textContent=task.notes;content.append(notes);}label.append(check);const edit=document.createElement('button');edit.type='button';edit.textContent='Edit';edit.setAttribute('aria-label','Edit '+task.topic+' on '+date);edit.onclick=()=>openEditor(task.id);row.append(label,content,edit);day.append(row);if(tasks.indexOf(task)<tasks.length-1){const pause=document.createElement('p');pause.className='plan-break help';pause.textContent='5-minute break: step away from the material before the next block.';day.append(pause);}}$('plan-days').append(day);}}
 function openEditor(id){editing=id;const p=state.plan,t=p.tasks.find(t=>t.id===id);$('plan-editor-title').textContent='Edit: '+t.topic;$('plan-edit-date').replaceChildren();for(const date of E.dates(p.config)){const o=document.createElement('option');o.value=date;o.textContent=displayDate(date);$('plan-edit-date').append(o);}$('plan-edit-date').value=t.date;$('plan-edit-minutes').value=t.minutes;$('plan-edit-method').value=t.method;$('plan-edit-notes').value=t.notes;$('plan-edit-error').textContent='';$('plan-editor').showModal();}
 $('plan-form').onsubmit=event=>{event.preventDefault();state.form=readForm();save();$('plan-error').textContent='';const config={...state.form,topics:state.form.topics.filter(t=>t.name)};try{if(E.dateValue(config.start)<E.dateValue(today))throw new Error('Choose today or a future start date for a new plan.');E.validateConfig(config);if(state.plan&&!confirm('Replace your existing plan and its completed-block progress? Your new inputs will be used.'))return;state.plan=E.generate(config,'plan-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,8));save();renderPlan();$('plan-output').scrollIntoView({block:'start',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});}catch(e){$('plan-error').textContent=e.message;}};
 $('plan-form').oninput=()=>{state.form=readForm();save();};$('plan-form').onchange=()=>{state.form=readForm();save();};
 $('plan-add-topic').onclick=()=>{state.form=readForm();if(state.form.topics.length>=20)return;state.form.topics.push({name:'',priority:2});topicRows();save();$('plan-topics').lastElementChild.querySelector('input').focus();};
 $('plan-edit-form').onsubmit=event=>{event.preventDefault();const p=JSON.parse(JSON.stringify(state.plan)),t=p.tasks.find(t=>t.id===editing);t.date=$('plan-edit-date').value;t.minutes=Number($('plan-edit-minutes').value);t.method=$('plan-edit-method').value;t.notes=$('plan-edit-notes').value.trim();$('plan-edit-error').textContent='';if(E.used(p.tasks,t.date)>p.config.minutes){$('plan-edit-error').textContent='This day would exceed your available time, including breaks. Choose another day or shorten a block.';return;}if(!E.validatePlan(p)){$('plan-edit-error').textContent='Keep this topic on separate days, with preparation before reviews, and use valid block lengths.';return;}state.plan=p;save();renderPlan();$('plan-editor').close();};
 $('plan-edit-cancel').onclick=()=>$('plan-editor').close();
 $('plan-print').onclick=()=>window.print();$('plan-calendar').onclick=()=>{try{const content=E.calendar(state.plan),blob=new Blob([content],{type:'text/calendar;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='my-study-plan.ics';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);$('plan-export-status').textContent='Calendar file downloaded. Import it into your calendar; events are all-day reminders. Completed blocks are excluded. Re-importing depends on how your calendar handles existing events.';}catch(e){$('plan-export-status').textContent=e.message;}};
 try{document.body.classList.toggle('dark-mode',localStorage.getItem('ems_theme')==='dark');}catch{}
 $('plan-theme').onclick=()=>{const dark=document.body.classList.toggle('dark-mode');try{localStorage.setItem('ems_theme',dark?'dark':'light');}catch{}};
 loadForm();renderPlan();save();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
})();
