const TERM_DECKS = [

  /* ============================================================
     PREFIXES (25 cards)
     ============================================================ */
  { cat: "prefix", term: "Bradycardia", sub: "Prefix + Root + Suffix",
    def: "Abnormally slow heart rate (typically under 60 bpm).",
    breakdown: "<span>brady-</span> = slow • <span>cardi</span> = heart • <span>-ia</span> = condition" },
  { cat: "prefix", term: "Tachycardia", sub: "Prefix + Root + Suffix",
    def: "Abnormally fast heart rate (typically over 100 bpm).",
    breakdown: "<span>tachy-</span> = fast • <span>cardi</span> = heart • <span>-ia</span> = condition" },
  { cat: "prefix", term: "Hypertension", sub: "Prefix + Root + Suffix",
    def: "High blood pressure.",
    breakdown: "<span>hyper-</span> = high • <span>tens</span> = pressure • <span>-ion</span> = process" },
  { cat: "prefix", term: "Hypoglycemia", sub: "Prefix + Root + Suffix",
    def: "Low blood sugar.",
    breakdown: "<span>hypo-</span> = low • <span>glyc</span> = sugar • <span>-emia</span> = blood condition" },
  { cat: "prefix", term: "Hyperglycemia", sub: "Prefix + Root + Suffix",
    def: "High blood sugar.",
    breakdown: "<span>hyper-</span> = high • <span>glyc</span> = sugar • <span>-emia</span> = blood condition" },
  { cat: "prefix", term: "Dyspnea", sub: "Prefix + Suffix",
    def: "Difficulty breathing or shortness of breath.",
    breakdown: "<span>dys-</span> = difficult • <span>-pnea</span> = breathing" },
  { cat: "prefix", term: "Apnea", sub: "Prefix + Suffix",
    def: "Absence of breathing.",
    breakdown: "<span>a-</span> = without • <span>-pnea</span> = breathing" },
  { cat: "prefix", term: "Tachypnea", sub: "Prefix + Suffix",
    def: "Abnormally rapid breathing.",
    breakdown: "<span>tachy-</span> = fast • <span>-pnea</span> = breathing" },
  { cat: "prefix", term: "Bradypnea", sub: "Prefix + Suffix",
    def: "Abnormally slow breathing.",
    breakdown: "<span>brady-</span> = slow • <span>-pnea</span> = breathing" },
  { cat: "prefix", term: "Aphasia", sub: "Prefix + Root + Suffix",
    def: "Loss of ability to understand or express speech.",
    breakdown: "<span>a-</span> = without • <span>phas</span> = speech • <span>-ia</span> = condition" },
  { cat: "prefix", term: "Antibiotic", sub: "Prefix + Root + Suffix",
    def: "A medication that kills or inhibits bacteria.",
    breakdown: "<span>anti-</span> = against • <span>biot</span> = life • <span>-ic</span> = pertaining to" },
  { cat: "prefix", term: "Anticoagulant", sub: "Prefix + Root + Suffix",
    def: "A substance that prevents blood clotting.",
    breakdown: "<span>anti-</span> = against • <span>coagul</span> = clotting • <span>-ant</span> = agent" },
  { cat: "prefix", term: "Antihypertensive", sub: "Prefix + Root + Suffix",
    def: "A medication that lowers blood pressure.",
    breakdown: "<span>anti-</span> = against • <span>hyper-</span> = high • <span>tens</span> = pressure • <span>-ive</span> = agent" },
  { cat: "prefix", term: "Antipyretic", sub: "Prefix + Root + Suffix",
    def: "A medication that reduces fever.",
    breakdown: "<span>anti-</span> = against • <span>pyret</span> = fever • <span>-ic</span> = pertaining to" },
  { cat: "prefix", term: "Antiseptic", sub: "Prefix + Root + Suffix",
    def: "A substance that inhibits the growth of microorganisms on living tissue.",
    breakdown: "<span>anti-</span> = against • <span>sept</span> = infection • <span>-ic</span> = pertaining to" },
  { cat: "prefix", term: "Antitussive", sub: "Prefix + Root + Suffix",
    def: "A medication that suppresses coughing.",
    breakdown: "<span>anti-</span> = against • <span>tuss</span> = cough • <span>-ive</span> = agent" },
  { cat: "prefix", term: "Bilateral", sub: "Prefix + Root + Suffix",
    def: "Relating to or affecting both sides of the body.",
    breakdown: "<span>bi-</span> = two • <span>later</span> = side • <span>-al</span> = pertaining to" },
  { cat: "prefix", term: "Unilateral", sub: "Prefix + Root + Suffix",
    def: "Relating to or affecting one side of the body.",
    breakdown: "<span>uni-</span> = one • <span>later</span> = side • <span>-al</span> = pertaining to" },
  { cat: "prefix", term: "Contralateral", sub: "Prefix + Root + Suffix",
    def: "Relating to the opposite side of the body.",
    breakdown: "<span>contra-</span> = opposite • <span>later</span> = side • <span>-al</span> = pertaining to" },
  { cat: "prefix", term: "Ipsilateral", sub: "Prefix + Root + Suffix",
    def: "Relating to the same side of the body.",
    breakdown: "<span>ipsi-</span> = same • <span>later</span> = side • <span>-al</span> = pertaining to" },
  { cat: "prefix", term: "Hypercapnia", sub: "Prefix + Root + Suffix",
    def: "Excessive carbon dioxide in the bloodstream.",
    breakdown: "<span>hyper-</span> = high • <span>capn</span> = carbon dioxide • <span>-ia</span> = condition" },
  { cat: "prefix", term: "Hypocapnia", sub: "Prefix + Root + Suffix",
    def: "Abnormally low carbon dioxide in the bloodstream.",
    breakdown: "<span>hypo-</span> = low • <span>capn</span> = carbon dioxide • <span>-ia</span> = condition" },
  { cat: "prefix", term: "Hyperkalemia", sub: "Prefix + Root + Suffix",
    def: "Abnormally high potassium in the blood.",
    breakdown: "<span>hyper-</span> = high • <span>kal</span> = potassium • <span>-emia</span> = blood condition" },
  { cat: "prefix", term: "Hypokalemia", sub: "Prefix + Root + Suffix",
    def: "Abnormally low potassium in the blood.",
    breakdown: "<span>hypo-</span> = low • <span>kal</span> = potassium • <span>-emia</span> = blood condition" },
  { cat: "prefix", term: "Hypothermia", sub: "Prefix + Root + Suffix",
    def: "Abnormally low body temperature.",
    breakdown: "<span>hypo-</span> = low • <span>therm</span> = heat • <span>-ia</span> = condition" },

  /* ============================================================
     SUFFIXES (50 cards)
     ============================================================ */
  { cat: "suffix", term: "Cardiology", sub: "Root + Suffix",
    def: "The study of the heart.",
    breakdown: "<span>cardi</span> = heart • <span>-ology</span> = study of" },
  { cat: "suffix", term: "Neurology", sub: "Root + Suffix",
    def: "The study of the nervous system.",
    breakdown: "<span>neur</span> = nerve • <span>-ology</span> = study of" },
  { cat: "suffix", term: "Hematology", sub: "Root + Suffix",
    def: "The study of blood, blood-forming organs, and blood diseases.",
    breakdown: "<span>hemat</span> = blood • <span>-ology</span> = study of" },
  { cat: "suffix", term: "Pathology", sub: "Root + Suffix",
    def: "The study of disease — its causes, nature, and effects.",
    breakdown: "<span>path</span> = disease • <span>-ology</span> = study of" },
  { cat: "suffix", term: "Radiology", sub: "Root + Suffix",
    def: "The study and use of medical imaging (X-rays, CT, MRI).",
    breakdown: "<span>radi</span> = radiation • <span>-ology</span> = study of" },
  { cat: "suffix", term: "Oncology", sub: "Root + Suffix",
    def: "The study and treatment of tumors and cancer.",
    breakdown: "<span>onc</span> = tumor • <span>-ology</span> = study of" },
  { cat: "suffix", term: "Pulmonology", sub: "Root + Suffix",
    def: "The study of the lungs and respiratory system.",
    breakdown: "<span>pulmon</span> = lung • <span>-ology</span> = study of" },
  { cat: "suffix", term: "Nephrology", sub: "Root + Suffix",
    def: "The study of kidney function and kidney disease.",
    breakdown: "<span>nephr</span> = kidney • <span>-ology</span> = study of" },
  { cat: "suffix", term: "Gastroenterology", sub: "Root + Root + Suffix",
    def: "The study of the stomach and intestines.",
    breakdown: "<span>gastr</span> = stomach • <span>enter</span> = intestine • <span>-ology</span> = study of" },
  { cat: "suffix", term: "Endocrinology", sub: "Root + Root + Suffix",
    def: "The study of hormones and endocrine glands.",
    breakdown: "<span>endo-</span> = within • <span>crin</span> = secrete • <span>-ology</span> = study of" },
  { cat: "suffix", term: "Anesthesiology", sub: "Prefix + Root + Suffix",
    def: "The branch of medicine dealing with anesthesia and pain management.",
    breakdown: "<span>an-</span> = without • <span>esthesia</span> = sensation • <span>-ology</span> = study of" },
  { cat: "suffix", term: "Dermatitis", sub: "Root + Suffix",
    def: "Inflammation of the skin.",
    breakdown: "<span>dermat</span> = skin • <span>-itis</span> = inflammation" },
  { cat: "suffix", term: "Gastritis", sub: "Root + Suffix",
    def: "Inflammation of the stomach lining.",
    breakdown: "<span>gastr</span> = stomach • <span>-itis</span> = inflammation" },
  { cat: "suffix", term: "Hepatitis", sub: "Root + Suffix",
    def: "Inflammation of the liver.",
    breakdown: "<span>hepat</span> = liver • <span>-itis</span> = inflammation" },
  { cat: "suffix", term: "Bronchitis", sub: "Root + Suffix",
    def: "Inflammation of the bronchial tubes.",
    breakdown: "<span>bronch</span> = bronchus • <span>-itis</span> = inflammation" },
  { cat: "suffix", term: "Peritonitis", sub: "Root + Suffix",
    def: "Inflammation of the peritoneum (abdominal lining).",
    breakdown: "<span>periton</span> = peritoneum • <span>-itis</span> = inflammation" },
  { cat: "suffix", term: "Meningitis", sub: "Root + Suffix",
    def: "Inflammation of the meninges (membranes around the brain and spinal cord).",
    breakdown: "<span>mening</span> = meninges • <span>-itis</span> = inflammation" },
  { cat: "suffix", term: "Arthritis", sub: "Root + Suffix",
    def: "Inflammation of one or more joints.",
    breakdown: "<span>arthr</span> = joint • <span>-itis</span> = inflammation" },
  { cat: "suffix", term: "Colitis", sub: "Root + Suffix",
    def: "Inflammation of the colon.",
    breakdown: "<span>col</span> = colon • <span>-itis</span> = inflammation" },
  { cat: "suffix", term: "Cystitis", sub: "Root + Suffix",
    def: "Inflammation of the bladder.",
    breakdown: "<span>cyst</span> = bladder • <span>-itis</span> = inflammation" },
  { cat: "suffix", term: "Phlebitis", sub: "Root + Suffix",
    def: "Inflammation of a vein.",
    breakdown: "<span>phleb</span> = vein • <span>-itis</span> = inflammation" },
  { cat: "suffix", term: "Appendectomy", sub: "Root + Suffix",
    def: "Surgical removal of the appendix.",
    breakdown: "<span>append</span> = appendix • <span>-ectomy</span> = surgical removal" },
  { cat: "suffix", term: "Splenectomy", sub: "Root + Suffix",
    def: "Surgical removal of the spleen.",
    breakdown: "<span>splen</span> = spleen • <span>-ectomy</span> = surgical removal" },
  { cat: "suffix", term: "Hysterectomy", sub: "Root + Suffix",
    def: "Surgical removal of the uterus.",
    breakdown: "<span>hyster</span> = uterus • <span>-ectomy</span> = surgical removal" },
  { cat: "suffix", term: "Mastectomy", sub: "Root + Suffix",
    def: "Surgical removal of a breast.",
    breakdown: "<span>mast</span> = breast • <span>-ectomy</span> = surgical removal" },
  { cat: "suffix", term: "Cholecystectomy", sub: "Root + Root + Suffix",
    def: "Surgical removal of the gallbladder.",
    breakdown: "<span>chole</span> = bile • <span>cyst</span> = bladder • <span>-ectomy</span> = surgical removal" },
  { cat: "suffix", term: "Gastrectomy", sub: "Root + Suffix",
    def: "Surgical removal of part or all of the stomach.",
    breakdown: "<span>gastr</span> = stomach • <span>-ectomy</span> = surgical removal" },
  { cat: "suffix", term: "Nephrectomy", sub: "Root + Suffix",
    def: "Surgical removal of a kidney.",
    breakdown: "<span>nephr</span> = kidney • <span>-ectomy</span> = surgical removal" },
  { cat: "suffix", term: "Craniotomy", sub: "Root + Suffix",
    def: "Surgical opening of the skull.",
    breakdown: "<span>crani</span> = skull • <span>-otomy</span> = surgical incision" },
  { cat: "suffix", term: "Tracheotomy", sub: "Root + Suffix",
    def: "Surgical incision into the trachea to create an airway.",
    breakdown: "<span>trache</span> = windpipe • <span>-otomy</span> = surgical incision" },
  { cat: "suffix", term: "Colostomy", sub: "Root + Suffix",
    def: "Surgical creation of an opening from the colon through the abdominal wall.",
    breakdown: "<span>col</span> = colon • <span>-ostomy</span> = surgical opening" },
  { cat: "suffix", term: "Tracheostomy", sub: "Root + Suffix",
    def: "Surgical creation of a stoma in the trachea for breathing.",
    breakdown: "<span>trache</span> = windpipe • <span>-ostomy</span> = surgical opening" },
  { cat: "suffix", term: "Hepatomegaly", sub: "Root + Suffix",
    def: "Enlargement of the liver.",
    breakdown: "<span>hepat</span> = liver • <span>-megaly</span> = enlargement" },
  { cat: "suffix", term: "Cardiomegaly", sub: "Root + Suffix",
    def: "Enlargement of the heart.",
    breakdown: "<span>cardi</span> = heart • <span>-megaly</span> = enlargement" },
  { cat: "suffix", term: "Splenomegaly", sub: "Root + Suffix",
    def: "Enlargement of the spleen.",
    breakdown: "<span>splen</span> = spleen • <span>-megaly</span> = enlargement" },
  { cat: "suffix", term: "Lymphadenopathy", sub: "Root + Root + Suffix",
    def: "Disease or swelling of the lymph nodes.",
    breakdown: "<span>lymph</span> = lymph • <span>aden</span> = gland • <span>-pathy</span> = disease" },
  { cat: "suffix", term: "Encephalopathy", sub: "Root + Suffix",
    def: "Any disease or disorder of the brain.",
    breakdown: "<span>encephal</span> = brain • <span>-pathy</span> = disease" },
  { cat: "suffix", term: "Retinopathy", sub: "Root + Suffix",
    def: "Disease of the retina — often related to diabetes.",
    breakdown: "<span>retin</span> = retina • <span>-pathy</span> = disease" },
  { cat: "suffix", term: "Myopathy", sub: "Root + Suffix",
    def: "Disease of muscle tissue.",
    breakdown: "<span>my</span> = muscle • <span>-pathy</span> = disease" },
  { cat: "suffix", term: "Neuropathy", sub: "Root + Suffix",
    def: "Disease or damage to nerves.",
    breakdown: "<span>neur</span> = nerve • <span>-pathy</span> = disease" },
  { cat: "suffix", term: "Nephropathy", sub: "Root + Suffix",
    def: "Disease of the kidney.",
    breakdown: "<span>nephr</span> = kidney • <span>-pathy</span> = disease" },
  { cat: "suffix", term: "Cyanosis", sub: "Root + Suffix",
    def: "Bluish discoloration of the skin due to lack of oxygen.",
    breakdown: "<span>cyan</span> = blue • <span>-osis</span> = condition" },
  { cat: "suffix", term: "Osteoporosis", sub: "Root + Suffix",
    def: "Condition of porous, weakened bones.",
    breakdown: "<span>oste</span> = bone • <span>por</span> = pore • <span>-osis</span> = condition" },
  { cat: "suffix", term: "Arteriosclerosis", sub: "Root + Root + Suffix",
    def: "Hardening and thickening of artery walls.",
    breakdown: "<span>arteri</span> = artery • <span>scler</span> = hard • <span>-osis</span> = condition" },
  { cat: "suffix", term: "Nephrosis", sub: "Root + Suffix",
    def: "Degenerative disease of the kidney tubules.",
    breakdown: "<span>nephr</span> = kidney • <span>-osis</span> = condition" },
  { cat: "suffix", term: "Stenosis", sub: "Root + Suffix",
    def: "Abnormal narrowing of a passage or vessel.",
    breakdown: "<span>sten</span> = narrow • <span>-osis</span> = condition" },
  { cat: "suffix", term: "Sclerosis", sub: "Root + Suffix",
    def: "Abnormal hardening of tissue.",
    breakdown: "<span>scler</span> = hard • <span>-osis</span> = condition" },
  { cat: "suffix", term: "Kyphosis", sub: "Root + Suffix",
    def: "Excessive outward curvature of the upper spine (hunchback).",
    breakdown: "<span>kyph</span> = hump • <span>-osis</span> = condition" },
  { cat: "suffix", term: "Lordosis", sub: "Root + Suffix",
    def: "Excessive inward curvature of the lower spine.",
    breakdown: "<span>lord</span> = curve • <span>-osis</span> = condition" },
  { cat: "suffix", term: "Scoliosis", sub: "Root + Suffix",
    def: "Abnormal lateral curvature of the spine.",
    breakdown: "<span>scoli</span> = crooked • <span>-osis</span> = condition" },
  { cat: "suffix", term: "Leukocytosis", sub: "Root + Root + Suffix",
    def: "Elevated white blood cell count — often indicates infection.",
    breakdown: "<span>leuko</span> = white • <span>cyt</span> = cell • <span>-osis</span> = condition" },

  /* ============================================================
     ROOT WORDS (25 cards)
     ============================================================ */
  { cat: "root", term: "Pneumothorax", sub: "Root + Root",
    def: "Air in the chest cavity causing lung collapse.",
    breakdown: "<span>pneumo</span> = air/lung • <span>thorax</span> = chest" },
  { cat: "root", term: "Hemoptysis", sub: "Root + Suffix",
    def: "Coughing up blood from the respiratory tract.",
    breakdown: "<span>hemo</span> = blood • <span>-ptysis</span> = spitting" },
  { cat: "root", term: "Hematemesis", sub: "Root + Suffix",
    def: "Vomiting blood.",
    breakdown: "<span>hemat</span> = blood • <span>-emesis</span> = vomiting" },
  { cat: "root", term: "Myocardial Infarction", sub: "Root + Root",
    def: "Heart attack — death of heart muscle from lack of blood flow.",
    breakdown: "<span>myo</span> = muscle • <span>cardi</span> = heart • <span>infarct</span> = tissue death" },
  { cat: "root", term: "Cerebrovascular Accident", sub: "Root + Root + Root",
    def: "Stroke — interrupted blood flow to the brain.",
    breakdown: "<span>cerebr</span> = brain • <span>vascul</span> = vessel • <span>accident</span> = event" },
  { cat: "root", term: "Gastroesophageal Reflux", sub: "Root + Root",
    def: "Stomach acid flowing back into the esophagus (GERD).",
    breakdown: "<span>gastr</span> = stomach • <span>esophag</span> = esophagus • <span>reflux</span> = backflow" },
  { cat: "root", term: "Leukocyte", sub: "Root + Root",
    def: "White blood cell — part of the immune system.",
    breakdown: "<span>leuko</span> = white • <span>cyt</span> = cell" },
  { cat: "root", term: "Erythrocyte", sub: "Root + Root",
    def: "Red blood cell — carries oxygen.",
    breakdown: "<span>erythro</span> = red • <span>cyt</span> = cell" },
  { cat: "root", term: "Thrombocytopenia", sub: "Root + Root + Suffix",
    def: "Low platelet count — risk of bleeding.",
    breakdown: "<span>thromb</span> = clot • <span>cyto</span> = cell • <span>-penia</span> = deficiency" },
  { cat: "root", term: "Otitis Media", sub: "Root + Suffix + Root",
    def: "Middle ear infection.",
    breakdown: "<span>ot</span> = ear • <span>-itis</span> = inflammation • <span>media</span> = middle" },
  { cat: "root", term: "Nephritis", sub: "Root + Suffix",
    def: "Inflammation of the kidney.",
    breakdown: "<span>nephr</span> = kidney • <span>-itis</span> = inflammation" },
  { cat: "root", term: "Gastroscopy", sub: "Root + Suffix",
    def: "Visual examination of the stomach using a scope.",
    breakdown: "<span>gastr</span> = stomach • <span>-scopy</span> = visual examination" },
  { cat: "root", term: "Bronchoscopy", sub: "Root + Suffix",
    def: "Visual examination of the airways using a scope.",
    breakdown: "<span>bronch</span> = bronchus • <span>-scopy</span> = visual examination" },
  { cat: "root", term: "Colonoscopy", sub: "Root + Suffix",
    def: "Visual examination of the colon using a scope.",
    breakdown: "<span>colon</span> = colon • <span>-scopy</span> = visual examination" },
  { cat: "root", term: "Arthroscopy", sub: "Root + Suffix",
    def: "Visual examination of a joint using a scope.",
    breakdown: "<span>arthr</span> = joint • <span>-scopy</span> = visual examination" },
  { cat: "root", term: "Laparoscopy", sub: "Root + Suffix",
    def: "Visual examination of the abdomen using a scope.",
    breakdown: "<span>lapar</span> = abdomen • <span>-scopy</span> = visual examination" },
  { cat: "root", term: "Cystoscopy", sub: "Root + Suffix",
    def: "Visual examination of the bladder using a scope.",
    breakdown: "<span>cyst</span> = bladder • <span>-scopy</span> = visual examination" },
  { cat: "root", term: "Electrocardiogram", sub: "Root + Root + Suffix",
    def: "A recording of the heart's electrical activity (ECG/EKG).",
    breakdown: "<span>electro</span> = electricity • <span>cardi</span> = heart • <span>-gram</span> = record" },
  { cat: "root", term: "Electroencephalogram", sub: "Root + Root + Suffix",
    def: "A recording of the brain's electrical activity (EEG).",
    breakdown: "<span>electro</span> = electricity • <span>encephal</span> = brain • <span>-gram</span> = record" },
  { cat: "root", term: "Mammogram", sub: "Root + Suffix",
    def: "An X-ray image of the breast.",
    breakdown: "<span>mamm</span> = breast • <span>-gram</span> = record" },
  { cat: "root", term: "Angiogram", sub: "Root + Suffix",
    def: "An X-ray image of blood vessels using contrast dye.",
    breakdown: "<span>angi</span> = vessel • <span>-gram</span> = record" },
  { cat: "root", term: "Myelogram", sub: "Root + Suffix",
    def: "An X-ray image of the spinal cord using contrast dye.",
    breakdown: "<span>myel</span> = spinal cord • <span>-gram</span> = record" },
  { cat: "root", term: "Cephalgia", sub: "Root + Suffix",
    def: "Headache — pain in the head.",
    breakdown: "<span>cephal</span> = head • <span>-algia</span> = pain" },
  { cat: "root", term: "Neuralgia", sub: "Root + Suffix",
    def: "Sharp pain along a nerve pathway.",
    breakdown: "<span>neur</span> = nerve • <span>-algia</span> = pain" },
  { cat: "root", term: "Myalgia", sub: "Root + Suffix",
    def: "Muscle pain.",
    breakdown: "<span>my</span> = muscle • <span>-algia</span> = pain" },

];
