(()=>{
 'use strict';
 const cases=window.WHAT_FIRST_CASES||[],byId=new Map(cases.map(c=>[c.id,c])),KEY='field_notes_order_v1',levels=['EMT','AEMT','Paramedic'];
 if(!cases.length)return;
 const $=id=>document.getElementById(id),validConfidence=x=>['confident','unsure','guessing'].includes(x),validOrder=(order,c)=>Array.isArray(order)&&order.length===c.steps.length&&new Set(order).size===c.steps.length&&order.every(id=>c.steps.some(s=>s.id===id));
 let state={version:1,level:'EMT',current:cases[0].id,drafts:{},history:[]},available=true,sorter=null;
 try{const raw=JSON.parse(localStorage.getItem(KEY));if(raw?.version===1){if(levels.includes(raw.level))state.level=raw.level;const saved=byId.get(raw.current);state.current=saved?.level===state.level?saved.id:cases.find(c=>c.level===state.level).id;
 for(const c of cases){const d=raw.drafts?.[c.id];if(d&&validOrder(d.order,c)&&(!d.confidence||validConfidence(d.confidence)))state.drafts[c.id]={order:d.order,confidence:d.confidence||'',checked:d.checked===true&&validConfidence(d.confidence)};}
 state.history=Array.isArray(raw.history)?raw.history.filter(h=>h&&byId.has(h.id)&&validOrder(h.order,byId.get(h.id))&&validConfidence(h.confidence)&&Number.isFinite(h.date)).slice(-60).map(h=>({id:h.id,order:h.order,confidence:h.confidence,date:h.date})):[];}}catch(e){if(!(e instanceof SyntaxError))available=false;}
 function save(){try{localStorage.setItem(KEY,JSON.stringify(state));available=true;}catch{available=false;}$('order-storage').textContent=available?'Your order and practice history are saved in this browser on this device.':'This browser cannot save progress. You can still practice.';}
 function current(){return byId.get(state.current);}
 function shuffle(c){const a=c.steps.map(s=>s.id);for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}if(a.every((id,i)=>id===c.steps[i].id))a.push(a.shift());return a;}
 function draft(){const c=current();return state.drafts[c.id]??=( {order:shuffle(c),confidence:'',checked:false} );}
 function outcome(c,order){return c.dependencies.filter(([before,after])=>order.indexOf(before)>order.indexOf(after));}
 function move(from,to){const d=draft();if(d.checked||to<0||to>=d.order.length)return;const [id]=d.order.splice(from,1);d.order.splice(to,0,id);save();renderList();$('order-move-status').textContent=`Moved ${current().steps.find(s=>s.id===id).text} to position ${to+1}.`;}
 function renderList(){if(sorter){sorter.destroy();sorter=null;}const c=current(),d=draft();$('order-list').replaceChildren();d.order.forEach((id,i)=>{const step=c.steps.find(s=>s.id===id),row=document.createElement('li');row.dataset.id=id;const grip=document.createElement('span');grip.className='order-grip';grip.textContent='⋮⋮';grip.setAttribute('aria-hidden','true');const n=document.createElement('span');n.className='order-number';n.textContent=i+1;const text=document.createElement('span');text.className='order-text';text.textContent=step.text;const arrows=document.createElement('span');arrows.className='order-arrows';[-1,1].forEach(dir=>{const b=document.createElement('button');b.type='button';b.textContent=dir===-1?'↑':'↓';b.setAttribute('aria-label',`Move step ${i+1} ${dir===-1?'up':'down'}`);b.disabled=d.checked||i+dir<0||i+dir>=d.order.length;b.onclick=()=>{move(i,i+dir);const buttons=$('order-list').children[i+dir].querySelectorAll('button'),preferred=buttons[dir===-1?0:1];(preferred.disabled?[...buttons].find(b=>!b.disabled):preferred)?.focus();};arrows.append(b);});row.append(grip,n,text,arrows);$('order-list').append(row);});
 if(window.Sortable&&!d.checked)sorter=new Sortable($('order-list'),{handle:'.order-grip',animation:matchMedia('(prefers-reduced-motion: reduce)').matches?0:150,onEnd:()=>{d.order=[...$('order-list').children].map(n=>n.dataset.id);save();renderList();$('order-move-status').textContent='Your action order was updated.';}});}
 function picker(){$('order-level').value=state.level;$('order-case').replaceChildren();for(const c of cases.filter(c=>c.level===state.level)){const o=document.createElement('option');o.value=c.id;o.textContent=c.title;$('order-case').append(o);}$('order-case').value=state.current;}
 function render(){const c=current(),d=draft();picker();$('order-category').textContent=`${c.level==='AEMT'?'Advanced EMT':c.level} · Priority challenge`;$('order-title').textContent=c.title;$('order-scene').textContent=c.scene;$('order-error').textContent='';$('order-move-status').textContent='';renderList();
 document.querySelectorAll('input[name="order-confidence"]').forEach(n=>{n.checked=n.value===d.confidence;n.disabled=d.checked;n.onchange=()=>{d.confidence=n.value;save();};});$('order-check').hidden=d.checked;$('order-feedback').hidden=!d.checked;
 if(d.checked){const wrong=outcome(c,d.order);$('order-result').textContent=wrong.length?'Review the priority links':'✓ Your order respects the priority links';$('order-confidence-note').textContent=wrong.length&&d.confidence==='confident'?'Confidence check: revisit this confident mistake.':`Your confidence: ${d.confidence}.`;
 $('order-deciding').textContent=wrong.length?'Priority to revisit: '+c.steps.find(s=>s.id===wrong[0][0]).text+' Before: '+c.steps.find(s=>s.id===wrong[0][1]).text:'The actions that depend on earlier steps are in the right order.';
 $('order-explanation').replaceChildren();for(const step of c.steps){const li=document.createElement('li'),text=document.createElement('strong'),note=document.createElement('small');text.textContent=step.text;note.textContent=step.note;li.append(text,note);$('order-explanation').append(li);}$('order-parallel').textContent=c.parallel;$('order-sources').replaceChildren();for(const src of [...c.sources,c.scope]){const a=document.createElement('a');a.textContent=src.label;a.href=src.url;a.target='_blank';a.rel='noopener noreferrer';$('order-sources').append(a);}$('order-checked').textContent='References checked '+c.checkedOn;}
 dashboard();save();}
 function dashboard(){const eligible=cases.filter(c=>c.level===state.level),latest=new Map();for(const h of state.history)latest.set(h.id,h);const tried=eligible.filter(c=>latest.has(c.id)),correct=tried.filter(c=>!outcome(c,latest.get(c.id).order).length);$('order-progress').textContent=`${tried.length}/${eligible.length} challenges tried at this level · ${correct.length} latest orders meet all priority links.`;$('order-review').replaceChildren();
 for(const c of eligible){const h=latest.get(c.id);if(!h)continue;const wrong=outcome(c,h.order),row=document.createElement('div');row.className='order-review-item';const p=document.createElement('p');p.textContent=`${c.title} — ${wrong.length?h.confidence==='confident'?'Confident mistake · revisit':'Needs practice':'Priorities met'} · ${new Date(h.date).toLocaleDateString()}`;const b=document.createElement('button');b.type='button';b.textContent='Open Challenge';b.onclick=()=>{state.current=c.id;render();$('order-title').scrollIntoView({block:'start',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});};row.append(p,b);$('order-review').append(row);}}
 $('order-check').onclick=()=>{const d=draft();if(d.checked)return;if(!validConfidence(d.confidence)){$('order-error').textContent='Choose confidence before checking your order.';return;}d.checked=true;window.StudyBadges?.record({type:'activity',id:state.current,date:Date.now()});if(!outcome(current(),d.order).length)window.StudyBadges?.record({type:'order',id:state.current,date:Date.now()});state.history.push({id:state.current,order:[...d.order],confidence:d.confidence,date:Date.now()});state.history=state.history.slice(-60);render();};
 $('order-retry').onclick=()=>{state.drafts[state.current]={order:shuffle(current()),confidence:'',checked:false};render();};
 $('order-level').onchange=()=>{state.level=$('order-level').value;state.current=cases.find(c=>c.level===state.level).id;render();};$('order-case').onchange=()=>{state.current=$('order-case').value;render();};
 function next(dir){const eligible=cases.filter(c=>c.level===state.level),i=eligible.findIndex(c=>c.id===state.current);state.current=eligible[(i+dir+eligible.length)%eligible.length].id;render();}
 $('order-prev').onclick=()=>next(-1);$('order-next').onclick=()=>next(1);
 try{document.body.classList.toggle('dark-mode',localStorage.getItem('ems_theme')==='dark');}catch{}
 $('order-theme').onclick=()=>{const dark=document.body.classList.toggle('dark-mode');try{localStorage.setItem('ems_theme',dark?'dark':'light');}catch{}};
 render();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
})();
