const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),http=require('node:http'),path=require('node:path');
(async()=>{const server=http.createServer((req,res)=>{try{const p=path.join(__dirname,'..',new URL(req.url,'http://localhost').pathname==='/'?'index.html':new URL(req.url,'http://localhost').pathname);res.setHeader('Content-Type',p.endsWith('.js')?'text/javascript':p.endsWith('.css')?'text/css':'text/html');res.end(fs.readFileSync(p));}catch{res.statusCode=404;res.end();}});await new Promise(r=>server.listen(8768,'127.0.0.1',r));const browser=await chromium.launch({executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH,args:['--no-sandbox','--disable-gpu','--no-zygote']});try{
const ctx=await browser.newContext({serviceWorkers:'block'});await ctx.route('**/*',r=>r.request().url().includes('127.0.0.1:8768')?r.continue():r.fulfill({body:'{"items":[]}'}));const p=await ctx.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));const base='http://127.0.0.1:8768/';await p.goto(base);await p.getByRole('button',{name:'Change One Finding',exact:true}).click();await p.waitForFunction(()=>window.CHANGE_FINDING_CASES);const cases=await p.evaluate(()=>CHANGE_FINDING_CASES);assert.equal(cases.length,10);assert.equal(new Set(cases.map(c=>c.id)).size,10);assert.equal(new Set(cases.map(c=>c.category)).size,5);
await p.evaluate(()=>{localStorage.setItem('field_notes_study_v1','quiz-sentinel');localStorage.setItem('field_notes_cards_v1','cards-sentinel');});
for(let i=0;i<10;i++){await p.locator('#challenge-select').selectOption(String(i));assert.equal(await p.locator('#challenge-feedback').isVisible(),false);for(let v=0;v<2;v++){await p.locator(v?'#finding-changed':'#finding-original').click();assert.equal(await p.locator('#challenge-finding').innerText(),cases[i].variants[v].finding);await p.locator('#challenge-choices button').nth(1-cases[i].variants[v].correct).click();assert.match(await p.locator('#challenge-result').innerText(),/Look again/);await p.locator('#challenge-choices button').nth(cases[i].variants[v].correct).click();assert.match(await p.locator('#challenge-result').innerText(),/identified/);assert.equal(await p.locator('#challenge-note').innerText(),cases[i].variants[v].note);assert.equal(await p.locator('#challenge-source').getAttribute('href'),cases[i].source.url);}}
assert.match(await p.locator('#challenge-progress').innerText(),/10\/10 challenges explored/);await p.reload();assert.equal(await p.locator('#challenge-select').inputValue(),'9');assert.equal(await p.locator('#finding-changed').getAttribute('aria-pressed'),'true');assert.equal(await p.locator('#challenge-feedback').isVisible(),true);assert.equal(await p.evaluate(()=>localStorage.getItem('field_notes_study_v1')),'quiz-sentinel');assert.equal(await p.evaluate(()=>localStorage.getItem('field_notes_cards_v1')),'cards-sentinel');await p.locator('#challenge-next').click();assert.equal(await p.locator('#challenge-select').inputValue(),'0');await p.locator('#challenge-prev').click();assert.equal(await p.locator('#challenge-select').inputValue(),'9');
await p.locator('#challenge-theme').click();assert.equal(await p.locator('body').evaluate(n=>n.classList.contains('dark-mode')),true);await p.reload();assert.equal(await p.locator('body').evaluate(n=>n.classList.contains('dark-mode')),true);
for(const width of [1440,390,320]){await p.setViewportSize({width,height:900});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);}await p.setViewportSize({width:1000,height:1000});await p.locator('#challenge-select').selectOption('0');await p.locator('#challenge-choices button').first().click();await p.screenshot({path:'/tmp/change-finding-desktop.png',fullPage:true});
await p.evaluate(()=>localStorage.setItem('field_notes_finding_v1','{bad'));await p.reload();assert.equal(await p.locator('#challenge-select').inputValue(),'0');assert.equal(await p.locator('#challenge-feedback').isVisible(),false);assert.deepEqual(errors,[]);
const blocked=await browser.newContext({serviceWorkers:'block'});await blocked.addInitScript(()=>{Storage.prototype.getItem=()=>{throw new DOMException('Blocked','SecurityError')};Storage.prototype.setItem=()=>{throw new DOMException('Blocked','SecurityError')};});const bp=await blocked.newPage();await bp.goto(base+'change-finding.html');await bp.locator('#challenge-choices button').first().click();assert.match(await bp.locator('#challenge-storage').innerText(),/cannot save/);assert.equal(await bp.locator('#challenge-feedback').isVisible(),true);
const offline=await browser.newContext({serviceWorkers:'allow'});await offline.route('**/*',r=>r.request().url().includes('127.0.0.1:8768')?r.continue():r.fulfill({body:'{}'}));const op=await offline.newPage();await op.goto(base);await op.evaluate(()=>navigator.serviceWorker.ready);await op.waitForFunction(()=>navigator.serviceWorker.controller);await offline.setOffline(true);await op.goto(base+'change-finding.html');await op.locator('#challenge-choices button').first().click();assert.equal(await op.locator('#challenge-feedback').isVisible(),true);
console.log('PASS: all 20 findings, correct/incorrect feedback, source links, navigation, resume, separate progress, dark/mobile layouts, corrupt/blocked storage, and offline challenge loading.');
}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1});
