const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),http=require('node:http'),path=require('node:path');
(async()=>{
 const server=http.createServer((req,res)=>{try{const name=new URL(req.url,'http://localhost').pathname;const file=path.join(__dirname,'..',name==='/'?'index.html':name);res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':file.endsWith('.svg')?'image/svg+xml':file.endsWith('.xml')?'application/xml':'text/html');res.end(fs.readFileSync(file));}catch{res.statusCode=404;res.end();}});
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}/`;let browser;
 try{
 browser=await chromium.launch({executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH,args:['--no-sandbox','--disable-gpu','--no-zygote']});
 const context=await browser.newContext({serviceWorkers:'block',timezoneId:'America/Chicago'});await context.route('**/*',r=>r.request().url().startsWith(base)?r.continue():r.fulfill({body:'{}'}));const p=await context.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));
 const pages=JSON.parse(fs.readFileSync(path.join(__dirname,'..','connection-trails-content.json'))).map(t=>t.slug+'.html');
 await p.goto(base+'#study');await p.getByRole('link',{name:/The Connection Trails Follow science/}).click();assert.equal(await p.locator('.trail-cover').count(),15);
 await p.locator('#trail-complaint').selectOption('dyspnea');assert.equal(await p.locator('.trail-cover:visible').count(),9);assert.match(await p.locator('#trail-library-count').innerText(),/9 of 15/);assert.equal(await p.locator('.trail-cover[href="cellular-energy-ischemic-stroke.html"]').isVisible(),false);
 await p.locator('#trail-complaint').selectOption('toxic-exposure');assert.equal(await p.locator('.trail-cover:visible').count(),1);assert.equal(await p.locator('.trail-library-group:visible').count(),1);assert.equal(await p.locator('.trail-cover[href="hemoglobin-carbon-monoxide.html"]').isVisible(),true);
 await p.locator('#trail-complaint').selectOption('all');assert.equal(await p.locator('.trail-cover:visible').count(),15);
 for(const width of [320,390,1440]){await p.setViewportSize({width,height:900});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'library overflow');}
 for(const file of pages){
  await p.goto(base+file);assert.equal(await p.locator('.trail-step:visible').count(),1);assert.equal(await p.locator('.trail-step:visible [data-level="emt"]').isVisible(),true);assert.equal(await p.locator('.trail-map [aria-current="step"]').count(),1);
  for(const level of ['emt','aemt','paramedic']){await p.locator('#trail-level').selectOption(level);assert.equal(await p.locator(`.trail-step:visible [data-level="${level}"]`).isVisible(),true);assert.equal(await p.locator('.trail-step:visible .trail-depth:visible').count(),1);assert.equal(await p.locator('.trail-map li:visible').count(),level==='emt'?3:6);assert.equal(await p.locator('.trail-treatment .trail-depth:visible').count(),1);assert.match(await p.locator('.trail-treatment .trail-depth:visible').innerText(),new RegExp(level==='emt'?'EMT':level==='aemt'?'AEMT':'Paramedic')); for(const width of [320,390,1440]){await p.setViewportSize({width,height:900});for(const dark of [false,true]){await p.evaluate(d=>document.body.classList.toggle('dark-mode',d),dark);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,`${file} ${level} ${width} ${dark}`);}}}
  await p.getByRole('button',{name:'Start with the patient',exact:true}).click();assert.equal(await p.locator('#stone-6').isVisible(),true);assert.match(await p.locator('.trail-map li:visible').first().innerText(),/^1/);assert.equal(await p.locator('#trail-prev').isDisabled(),true);await p.locator('#trail-next').click();assert.equal(await p.locator('#stone-5').isVisible(),true);await p.goBack();assert.equal(await p.locator('#stone-6').isVisible(),true);
  await p.goto(base+file+'#step=3&level=aemt&direction=patient');assert.equal(await p.locator('#stone-3').isVisible(),true);assert.equal(await p.locator('#trail-level').inputValue(),'aemt');assert.match(await p.locator('#trail-position').innerText(),/Stop 4 of 6/);
  await p.locator('#stone-3 button[data-correct="false"]').first().click();assert.match(await p.locator('#stone-3 [role="status"]').innerText(),/Revisit/);assert.match(await p.locator('#trail-check-status').innerText(),/0 of 6/);
  await p.locator('#stone-3 button[data-correct="true"]').click();assert.match(await p.locator('#trail-check-status').innerText(),/1 of 6/);
  await p.emulateMedia({media:'print'});assert.equal(await p.locator('.trail-step:visible').count(),6);assert.equal(await p.locator('.trail-depth:visible').count(),21);await p.emulateMedia({media:'screen'});
 }
 await p.goto(base+pages[0]);await p.evaluate(()=>localStorage.removeItem(StudyStreak.storageKey));await p.reload();await p.locator('#trail-level').selectOption('paramedic');
 for(let i=1;i<=5;i++){await p.locator(`.trail-map a[href^="#step=${i}&"]`).click();await p.locator(`#stone-${i} button[data-correct="true"]`).click();}assert.equal(await p.evaluate(()=>Object.values(StudyStreak.getState().days).some(d=>d.challenge)),false);
 await p.locator('.trail-map a[href^="#step=6&"]').click();await p.locator('#stone-6 .trail-check:visible button[data-correct="true"]').click();assert.equal(await p.evaluate(()=>Object.values(StudyStreak.getState().days).some(d=>d.challenge)),true);await p.goto(base+'#my-progress');assert.match(await p.locator('#study-streak').innerText(),/Daily goal completed/);
 await p.goto(base+pages[3]);await p.evaluate(()=>localStorage.removeItem(StudyStreak.storageKey));await p.reload();
 for(const i of [1,3]){await p.locator(`.trail-map a[href^="#step=${i}&"]`).click();await p.locator(`#stone-${i} .trail-check:visible button[data-correct="true"]`).click();}
 assert.equal(await p.evaluate(()=>Object.values(StudyStreak.getState().days).some(d=>d.challenge)),false);
 await p.locator('.trail-map a[href^="#step=6&"]').click();await p.locator('#stone-6 .trail-check:visible button[data-correct="true"]').click();assert.equal(await p.evaluate(()=>Object.values(StudyStreak.getState().days).some(d=>d.challenge)),true);
 await p.locator('#trail-level').selectOption('paramedic');assert.match(await p.locator('#trail-check-status').innerText(),/0 of 6/);assert.equal(await p.locator('#stone-6 [data-check-level="paramedic"]').isVisible(),true);
 await p.locator('.trail-treatment .trail-depth:visible a[href="#source-4"]').click();assert.equal(await p.locator('#trail-level').inputValue(),'paramedic');assert.equal(await p.locator('#stone-6').isVisible(),true);await p.locator('#trail-level').selectOption('emt');await p.getByRole('button',{name:'Start with the patient',exact:true}).click();assert.match(await p.locator('#trail-position').innerText(),/Stop 1 of 3/);await p.locator('#trail-next').click();assert.equal(await p.locator('#stone-3').isVisible(),true);await p.locator('#trail-next').click();assert.equal(await p.locator('#stone-1').isVisible(),true);
 await p.goto(base+pages[3]+'#step=2&level=emt');assert.equal(await p.locator('#stone-1').isVisible(),true);assert.match(await p.locator('#trail-position').innerText(),/Stop 1 of 3/);
 await p.goto(base+pages[4]+'#step=6&level=paramedic');await p.setViewportSize({width:390,height:900});await p.screenshot({path:'/tmp/cell-paramedic-mobile.png',fullPage:true});await p.setViewportSize({width:1440,height:1000});await p.screenshot({path:'/tmp/cell-paramedic-desktop.png',fullPage:true});
 await p.goto(base+'cellular-energy-ischemic-stroke.html');await p.setViewportSize({width:390,height:900});await p.screenshot({path:'/tmp/new-stroke-mobile.png',fullPage:true});await p.goto(base+'alveolar-cells-surfactant-ards.html#step=6&level=paramedic');await p.setViewportSize({width:1440,height:1000});await p.screenshot({path:'/tmp/new-ards-paramedic.png',fullPage:true});
 await p.goto(base+pages[0]);await p.setViewportSize({width:390,height:900});await p.evaluate(()=>document.body.classList.remove('dark-mode'));await p.screenshot({path:'/tmp/trail-mobile.png',fullPage:true});await p.setViewportSize({width:1440,height:1000});await p.screenshot({path:'/tmp/trail-desktop.png',fullPage:true});
 const noJS=await browser.newContext({javaScriptEnabled:false});const np=await noJS.newPage();await np.goto(base+'connection-trails.html');assert.equal(await np.locator('.trail-cover:visible').count(),15);assert.equal(await np.locator('#trail-library-controls').isVisible(),false);for(const file of pages){await np.goto(base+file);assert.equal(await np.locator('.trail-step:visible').count(),6);assert.equal(await np.locator('.trail-depth:visible').count(),21);}await noJS.close();
 const blocked=await browser.newContext({serviceWorkers:'block'});await blocked.addInitScript(()=>Object.defineProperty(window,'localStorage',{get(){throw new Error('blocked');}}));const bp=await blocked.newPage();await bp.goto(base+pages[2]);await bp.locator('#trail-level').selectOption('paramedic');await bp.locator('#trail-next').click();assert.equal(await bp.locator('#stone-2').isVisible(),true);await bp.locator('#stone-2 button[data-correct="true"]').click();assert.match(await bp.locator('#trail-check-status').innerText(),/1 of 6/);await blocked.close();
 const offline=await browser.newContext({serviceWorkers:'allow'});await offline.route('**/*',r=>r.request().url().startsWith(base)?r.continue():r.fulfill({body:'{}'}));const op=await offline.newPage();await op.goto(base+'connection-trails.html');await op.evaluate(()=>navigator.serviceWorker.ready);await op.waitForFunction(()=>navigator.serviceWorker.controller);await offline.setOffline(true);for(const file of pages){await op.goto(base+file);await op.locator('#trail-next').click();assert.equal(await op.locator('#stone-3').isVisible(),true);}await offline.close();assert.deepEqual(errors,[]);
 console.log('PASS: fifteen sourced trails, chief-complaint filtering, EMT/AEMT/Paramedic views, forward/reverse navigation, history/deep links, reasoning feedback, three/six-check level-specific streak gates and advanced treatment checks, print, no-JS reading, blocked storage, mobile/dark layouts, and offline pages.');
 }finally{await browser?.close();server.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
