// Binary recall, legacy migration, exact review queues, schedule, resume, and storage isolation.
const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),http=require('node:http'),path=require('node:path');
(async()=>{
 const server=http.createServer((req,res)=>{try{const p=path.join(__dirname,'..',new URL(req.url,'http://localhost').pathname==='/'?'index.html':new URL(req.url,'http://localhost').pathname);res.setHeader('Content-Type',p.endsWith('.js')?'text/javascript':p.endsWith('.css')?'text/css':'text/html');res.end(fs.readFileSync(p));}catch{res.statusCode=404;res.end();}});
 await new Promise(r=>server.listen(8766,'127.0.0.1',r));
 const browser=await chromium.launch({executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH,args:['--no-sandbox','--disable-gpu','--no-zygote']});
 try{
 const context=await browser.newContext({serviceWorkers:'block'});await context.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.fulfill({body:'{}'}));
 const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));const base='http://127.0.0.1:8766/';
 await page.addInitScript(()=>{window.testNow=Date.now();Date.now=()=>window.testNow;});await page.goto(base+'#my-progress');
 await page.locator('.card-progress-details>summary').click();
 const cards=await page.evaluate(()=>({c:FIELD_NOTE_CARDS.filter(c=>c.kind==='clinical').slice(0,6),t:FIELD_NOTE_CARDS.find(c=>c.kind==='terms')}));const id=cards.c[0].id;
 // Existing difficult, known, bookmarks, and four-rating records all become understandable binary states.
 await page.evaluate(({c,t})=>{const records={};records[c[0].id]={bookmark:true};records[c[1].id]={known:true};records[c[2].id]={rating:'hard',due:Date.now()+86400000,interval:1,reviewedAt:Date.now()};records[c[3].id]={rating:'easy',due:Date.now()+4*86400000,interval:4,reviewedAt:Date.now()};records[c[4].id]={known:false,difficult:true};records[c[5].id]={bookmark:true,known:true};records[t.id]={difficult:true};localStorage.setItem('field_notes_cards_v1',JSON.stringify({version:1,records,sessions:{},history:[],migrated:{clinical:true,terms:true}}));localStorage.setItem('field_notes_study_v1',JSON.stringify({version:1,missed:['keep'],bookmarks:['keep'],history:[],session:null}));},cards);await page.reload();await page.locator('.card-progress-details>summary').click();
 let state=await page.evaluate(()=>CardStudy.getState());assert.equal(state.records[id].difficult,true);assert.equal(state.records[cards.c[1].id].known,true);assert.equal(state.records[cards.c[2].id].rating,'again');assert.equal(state.records[cards.c[3].id].rating,'good');assert.equal(state.records[cards.c[5].id].known,true);
 const quiz=await page.evaluate(()=>localStorage.getItem('field_notes_study_v1'));
 assert.equal(await page.locator('#card-study-dashboard').getByRole('link',{name:'Card Bookmarks',exact:true}).count(),0);
 await page.locator('#card-study-dashboard section').first().locator('.card-review-list summary').click();assert(await page.locator('#card-study-dashboard section').first().locator('.card-review-item').count()>=4);assert.match(await page.locator('#card-study-dashboard').innerText(),/Don’t Know/);
 await page.goto(base+'flashcards.html?card='+encodeURIComponent(id));assert.equal(await page.getByRole('button',{name:'Know',exact:true}).isDisabled(),true);assert.equal(await page.getByRole('button',{name:'Don’t Know',exact:true}).isDisabled(),true);
 await page.getByRole('button',{name:'Reveal / Hide Answer'}).click();assert.equal(await page.locator('.card-rating-panel').isVisible(),false);assert.equal(await page.getByRole('button',{name:'Easy',exact:true}).count(),0);assert.equal(await page.getByRole('button',{name:'Bookmark Card',exact:true}).count(),0);
 const now=await page.evaluate(()=>Date.now());await page.getByRole('button',{name:'Don’t Know',exact:true}).click();state=await page.evaluate(()=>CardStudy.getState());assert.equal(state.records[id].due,now+600000);assert.equal(state.records[id].known,false);assert.equal(state.sessions.clinical,undefined);
 await page.goto(base+'flashcards.html?mode=due');state=await page.evaluate(()=>CardStudy.getState());assert(!state.sessions.clinical?.keys.includes(id));
 await page.evaluate(()=>{const s=CardStudy.getState();delete s.sessions.clinical;localStorage.setItem(CardStudy.storageKey,JSON.stringify(s));});
 await page.goto(base+'flashcards.html?mode=difficult');state=await page.evaluate(()=>CardStudy.getState());assert(state.sessions.clinical.keys.includes(id));assert(!state.sessions.clinical.keys.includes(cards.c[3].id));
 await page.getByRole('button',{name:'🔀 Shuffle',exact:true}).click();await page.getByRole('button',{name:'Reveal / Hide Answer'}).click();const session=await page.evaluate(()=>CardStudy.getState().sessions.clinical);await page.getByRole('button',{name:'Save & Exit'}).click();await page.goto(base+'flashcards.html?resume=1');assert.deepEqual(await page.evaluate(()=>CardStudy.getState().sessions.clinical),session);assert.equal(await page.getByRole('button',{name:'Know',exact:true}).isEnabled(),true);
 await page.evaluate(()=>{const s=CardStudy.getState();delete s.sessions.clinical;localStorage.setItem(CardStudy.storageKey,JSON.stringify(s));});
 // Consecutive successful recall expands the interval; a miss resets the progression.
 for(const days of [1,3,7,14,30,30]){await page.goto(base+'flashcards.html?card='+encodeURIComponent(id));await page.getByRole('button',{name:'Reveal / Hide Answer'}).click();const n=await page.evaluate(()=>Date.now());await page.getByRole('button',{name:'Know',exact:true}).click();state=await page.evaluate(()=>CardStudy.getState());assert.equal(state.records[id].interval,days);assert.equal(state.records[id].due,n+days*86400000);assert.equal(state.records[id].difficult,false);}
 await page.goto(base+'flashcards.html?card='+encodeURIComponent(id));await page.getByRole('button',{name:'Reveal / Hide Answer'}).click();await page.getByRole('button',{name:'Don’t Know',exact:true}).click();assert.equal((await page.evaluate(()=>CardStudy.getState())).records[id].knowStreak,0);
 await page.goto(base+'#resources');await page.locator('#resource-print-collection').selectOption('difficult');await page.locator('#resource-preview').click();assert((await page.locator('#resource-print-sheet').innerText()).includes(cards.c[0].front));await page.locator('#resource-close').click();
 await page.goto(base+'terminology-decks.html?card='+encodeURIComponent(cards.t.id));await page.getByRole('button',{name:'Reveal / Hide Answer'}).click();await page.getByRole('button',{name:'Know',exact:true}).click();state=await page.evaluate(()=>CardStudy.getState());assert.equal(state.records[cards.t.id].known,true);assert.equal(state.records[id].difficult,true);assert.equal(await page.evaluate(()=>localStorage.getItem('field_notes_study_v1')),quiz);
 // Review due gates on the saved timestamp, not how recently a list was rendered.
 await page.goto(base);await page.evaluate(id=>{const s=CardStudy.getState();s.records[id].due=Date.now()-1;delete s.sessions.clinical;localStorage.setItem(CardStudy.storageKey,JSON.stringify(s));},id);await page.goto(base+'flashcards.html?mode=due');assert((await page.evaluate(()=>CardStudy.getState())).sessions.clinical.keys.includes(id));
 for(const width of [1440,390,320]){await page.setViewportSize({width,height:950});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);const boxes=await page.locator('.card-navigation').evaluate(n=>{const p=n.querySelector('.card-prev').getBoundingClientRect(),c=n.querySelector('.card-mark-actions').getBoundingClientRect(),q=n.querySelector('.card-next').getBoundingClientRect();return {left:p.right<=c.left,right:c.right<=q.left};});assert.deepEqual(boxes,{left:true,right:true});}
 await page.screenshot({path:'/tmp/binary-cards-mobile.png',fullPage:true});
 page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'Reset Card Progress',exact:true}).click();state=await page.evaluate(()=>CardStudy.getState());assert.equal(state.records[id],undefined);assert.equal(state.records[cards.t.id].known,true);
 // Oldest legacy saved work also survives.
 await page.goto(base);await page.evaluate(({c,t})=>{localStorage.removeItem(CardStudy.storageKey);localStorage.setItem('clinical-flashcards-progress-v4',JSON.stringify({known:{[c[0].legacy]:true},review:{}}));localStorage.setItem('terminology-decks-progress-v1',JSON.stringify({known:{},review:{[t.legacy]:true}}));},cards);await page.reload();await page.reload();state=await page.evaluate(()=>CardStudy.getState());assert.equal(state.records[id].known,true);assert.equal(state.records[cards.t.id].difficult,true);
 const blocked=await browser.newContext({serviceWorkers:'block'});await blocked.addInitScript(()=>{Storage.prototype.getItem=function(){throw new DOMException('Blocked','SecurityError')};Storage.prototype.setItem=function(){throw new DOMException('Blocked','SecurityError')};});await blocked.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.fulfill({body:'{}'}));const bp=await blocked.newPage();await bp.goto(base+'terminology-decks.html');assert.match(await bp.locator('.card-storage-warning').innerText(),/cannot save/);await bp.getByRole('button',{name:'Reveal / Hide Answer'}).click();await bp.getByRole('button',{name:'Know',exact:true}).click();assert.equal((await bp.evaluate(()=>CardStudy.getState())).history.length,1);
 const offline=await browser.newContext({serviceWorkers:'allow'});await offline.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.fulfill({body:'{}'}));const op=await offline.newPage();await op.goto(base);await op.evaluate(()=>navigator.serviceWorker.ready);await op.waitForFunction(()=>navigator.serviceWorker.controller);await offline.setOffline(true);for(const file of ['flashcards.html','terminology-decks.html']){await op.goto(base+file);await op.waitForFunction(()=>window.CardStudy);assert.equal(await op.locator('.card-study-toolbar').isVisible(),true);}
 assert.deepEqual(errors,[]);console.log('PASS: binary choices, migration, review list, scheduling and reset, shuffle/reveal resume, printing, score isolation, navigation/mobile, blocked storage, offline.');
 }finally{await browser.close();server.close();}
})().catch(e=>{console.error(e);process.exitCode=1});
