const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),http=require('node:http'),path=require('node:path');
(async()=>{
 const root=path.join(__dirname,'..');const server=http.createServer((req,res)=>{try{const u=new URL(req.url,'http://localhost');const p=path.join(root,u.pathname==='/'?'index.html':u.pathname);res.setHeader('Content-Type',p.endsWith('.js')?'text/javascript':p.endsWith('.css')?'text/css':p.endsWith('.svg')?'image/svg+xml':'text/html');res.end(fs.readFileSync(p));}catch{res.statusCode=404;res.end();}});await new Promise(r=>server.listen(8798,'127.0.0.1',r));const base='http://127.0.0.1:8798/';
 const browser=await chromium.launch({executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH,args:['--no-sandbox','--disable-gpu','--no-zygote']});
 try{
 const context=await browser.newContext({serviceWorkers:'block'});await context.route('**/*',r=>r.request().url().startsWith(base)?r.continue():r.fulfill({body:'{}'}));const p=await context.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));
 await p.goto(base+'#study');await p.getByRole('link',{name:/Anatomy Explorer Explore/}).click();assert.match(p.url(),/anatomy-explorer.html/);assert.equal(await p.locator('a[href="anatomy/"]').count(),1);await p.getByRole('link',{name:/The Heart: Inside Out/}).click();
 await p.locator('#illustration').waitFor({state:'visible'});assert.equal(await p.locator('[data-stage]:visible').count(),1);assert.match(await p.locator('[data-stage]:visible h2').innerText(),/thorax/);
 for(const stage of ['heart','tissue','cell','nucleus']){await p.locator('#next-stage').click();await p.waitForFunction(s=>document.querySelector('[data-stage-link][aria-current="step"]').dataset.stageLink===s,stage);assert.equal(await p.locator('[data-stage]:visible').getAttribute('id'),stage);for(const b of await p.locator('[data-structure]').all()){await b.click();assert.equal(await b.getAttribute('aria-pressed'),'true');assert.equal(await p.locator('#structure-title').innerText(),await b.innerText());}}
 assert.equal(await p.locator('#next-stage').isDisabled(),true);await p.locator('#previous-stage').click();await p.waitForFunction(()=>location.hash==='#cell');await p.locator('#learning-level').selectOption('paramedic');assert.match(await p.locator('[data-stage="cell"] [data-learning-level]:visible').innerText(),/SERCA/);assert.equal(await p.locator('#energy-trail').getAttribute('href'),'mitochondria-heart-failure.html#step=1&level=paramedic');assert.equal(await p.locator('#calcium-trail').getAttribute('href'),'endoplasmic-reticulum-heart-injury.html#step=1&level=paramedic');
 const tp=await context.newPage();await tp.goto(base+await p.locator('#energy-trail').getAttribute('href'));assert.equal(await tp.locator('#trail-level').inputValue(),'paramedic');await tp.close();
 await p.reload();assert.equal(await p.locator('#learning-level').inputValue(),'paramedic');assert.equal(await p.locator('[data-stage]:visible').getAttribute('id'),'cell');
 await p.locator('#zoom-in').click();assert.equal(await p.locator('#zoom-value').innerText(),'120%');await p.locator('#reset-view').click();assert.equal(await p.locator('#zoom-value').innerText(),'100%');
 await p.locator('#heart-canvas').scrollIntoViewIfNeeded();const box=await p.locator('#heart-canvas').boundingBox();await p.mouse.click(box.x+box.width/2,box.y+box.height/2);assert.equal(await p.locator('#structure-title').innerText(),'Nucleus');
 await p.locator('[data-stage-link="tissue"]').focus();await p.keyboard.press('Enter');await p.waitForFunction(()=>location.hash==='#tissue');assert.equal(await p.locator('[data-stage]:visible').getAttribute('id'),'tissue');await p.goBack();assert.equal(await p.locator('[data-stage]:visible').getAttribute('id'),'cell');
 for(const dark of [false,true]){await p.evaluate(d=>document.body.classList.toggle('dark-mode',d),dark);for(const width of [1440,768,390,320]){await p.setViewportSize({width,height:900});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,`${width} dark=${dark}`);}}
 await p.setViewportSize({width:1440,height:1050});await p.locator('#theme-toggle').click();await p.goto(base+'heart-explorer.html');await p.locator('#theme-toggle').click();await p.screenshot({path:'/tmp/heart-desktop.png',fullPage:true});await p.setViewportSize({width:390,height:844});await p.screenshot({path:'/tmp/heart-mobile.png',fullPage:true});
 await p.emulateMedia({media:'print'});assert.equal(await p.locator('[data-stage]:visible').count(),5);assert.equal(await p.locator('[data-learning-level]:visible').count(),15);await p.emulateMedia({media:'screen'});
 const nojs=await browser.newContext({javaScriptEnabled:false});const np=await nojs.newPage();await np.goto(base+'heart-explorer.html');assert.equal(await np.locator('[data-stage]:visible').count(),5);assert.equal(await np.locator('[data-learning-level]:visible').count(),15);assert.equal(await np.locator('#illustration').isVisible(),false);
 const offline=await browser.newContext({serviceWorkers:'allow'});await offline.route('**/*',r=>r.request().url().startsWith(base)?r.continue():r.fulfill({body:'{}'}));const op=await offline.newPage();await op.goto(base+'anatomy-explorer.html');await op.evaluate(()=>navigator.serviceWorker.ready);await op.waitForFunction(()=>navigator.serviceWorker.controller);await offline.setOffline(true);await op.getByRole('link',{name:/The Heart: Inside Out/}).click();await op.locator('#next-stage').click();await op.waitForFunction(()=>location.hash==='#heart');assert.equal(await op.locator('[data-stage]:visible').getAttribute('id'),'heart');await op.reload();assert.equal(await op.locator('[data-stage]:visible').getAttribute('id'),'heart');
 const blocked=await browser.newContext({serviceWorkers:'block'});await blocked.addInitScript(()=>{Storage.prototype.getItem=()=>{throw new Error('blocked')};Storage.prototype.setItem=()=>{throw new Error('blocked')};});const bp=await blocked.newPage();await bp.goto(base+'heart-explorer.html#nucleus');assert.equal(await bp.locator('[data-stage]:visible').getAttribute('id'),'nucleus');await bp.locator('#theme-toggle').click();
 assert.deepEqual(errors,[]);console.log('PASS: dashboard/atlas integration, all stages/structures, cell hotspot, level/deep-link persistence, trail links, keyboard/history, sketch zoom/reset, 320–1440 layouts, print/no-JS, blocked storage and offline navigation/reload.');
 }finally{await browser.close();server.close();}
})().catch(e=>{console.error(e);process.exitCode=1});
