const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),http=require('node:http'),path=require('node:path');
(async()=>{
 const server=http.createServer((req,res)=>{try{const p=path.join(__dirname,'..',new URL(req.url,'http://localhost').pathname==='/'?'index.html':new URL(req.url,'http://localhost').pathname);res.setHeader('Content-Type',p.endsWith('.js')?'text/javascript':p.endsWith('.css')?'text/css':p.endsWith('.png')?'image/png':'text/html');res.end(fs.readFileSync(p));}catch{res.statusCode=404;res.end();}});
 await new Promise(r=>server.listen(8791,'127.0.0.1',r));const base='http://127.0.0.1:8791/';
 const browser=await chromium.launch({executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH,args:['--no-sandbox','--disable-gpu','--no-zygote']});
 try{
  const context=await browser.newContext({serviceWorkers:'block'});await context.route('**/*',r=>r.request().url().startsWith(base)?r.continue():r.fulfill({body:'{"items":[]}'}));
  const p=await context.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(base);
  const tab=async name=>{await p.getByRole('link',{name,exact:true}).click();await p.locator('#'+({'Today':'today','Study':'study','My Progress':'my-progress','Resources':'resources'}[name])).waitFor({state:'visible'});};
  assert.equal(await p.locator('#today').isVisible(),true);assert.equal(await p.locator('#study').isVisible(),false);assert.equal(await p.locator('#today-start').isVisible(),true);
  const ids=await p.evaluate(()=>[...document.querySelectorAll('[id]')].map(n=>n.id));assert.equal(ids.length,new Set(ids).size);
  await tab('Study');await p.getByRole('link',{name:/Practice Questions Review/}).click();assert.equal(await p.locator('#topic-select').isVisible(),true);
  await p.locator('#question-slider').fill('5');await p.getByRole('button',{name:'Review Mode',exact:true}).click();assert.equal(await p.locator('#quiz-area').isVisible(),true);assert.equal(await p.locator('.dashboard-nav').isVisible(),false);
  const question=await p.locator('#question-text').innerText();await p.getByRole('button',{name:'Save & Exit',exact:true}).click();await p.goto(base);assert.equal(await p.locator('#resume-card').isVisible(),true);assert.equal(await p.locator('#today-start').isVisible(),false);
  await p.getByRole('button',{name:'Resume Session',exact:true}).click();assert.equal(await p.locator('#question-text').innerText(),question);
  await p.getByRole('button',{name:'Save & Exit',exact:true}).click();await p.goto(base);p.once('dialog',d=>d.accept());await p.getByRole('button',{name:'Discard Session',exact:true}).click();assert.equal(await p.locator('#today-start').isVisible(),true);
  await tab('My Progress');assert.equal(await p.locator('#study-streak').isVisible(),true);assert.equal(await p.locator('#badge-case').isVisible(),true);await p.getByRole('button',{name:'Progress History',exact:true}).click();assert.equal(await p.locator('#study-dialog').isVisible(),true);await p.locator('#study-dialog').getByRole('button',{name:'Close study tools',exact:true}).click();
  await p.locator('.card-progress-details>summary').click();assert.equal(await p.locator('#card-study-dashboard').isVisible(),true);
  const download=p.waitForEvent('download');await p.getByRole('button',{name:'Download Backup',exact:true}).click();assert.match((await download).suggestedFilename(),/\.json$/);
  await p.evaluate(()=>{const s=CardStudy.getState();const c=FIELD_NOTE_CARDS.find(c=>c.kind==='clinical');s.records[c.id]={known:false,difficult:true};localStorage.setItem(CardStudy.storageKey,JSON.stringify(s));CardStudy.refresh();});
  await tab('Resources');await p.locator('#resource-search').fill('shock');await p.waitForFunction(()=>document.getElementById('resource-results').textContent.length>0);await p.locator('#resource-print-collection').selectOption('difficult');await p.locator('#resource-preview').click();await p.locator('#resource-print-dialog').waitFor({state:'visible'});await p.locator('#resource-close').click();assert.equal(await p.getByRole('link',{name:/Research & Present/}).count(),1);assert.equal(await p.getByRole('button',{name:'Open Instructor Corner'}).isVisible(),true);
  await p.goto(base+'#my-progress');assert.equal(await p.locator('#my-progress').isVisible(),true);await p.goBack();assert.equal(await p.locator('#resources').isVisible(),true);
  for(const dark of [false,true]){await p.evaluate(d=>document.body.classList.toggle('dark-mode',d),dark);for(const width of [1440,768,390,320]){await p.setViewportSize({width,height:900});for(const name of ['Today','Study','My Progress','Resources']){await tab(name);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,`${name} ${width} dark=${dark}`);}await tab('Today');await p.screenshot({path:`/tmp/dashboard-${dark}-${width}.png`,fullPage:true});}}
  const card=await p.evaluate(()=>FIELD_NOTE_CARDS.find(c=>c.kind==='clinical').id);await p.goto(base+'flashcards.html?card='+encodeURIComponent(card));await p.getByRole('button',{name:'Reveal / Hide Answer'}).click();await p.getByRole('button',{name:'Don’t Know',exact:true}).click();await p.goto(base);assert.match(await p.locator('#today-review summary').innerText(),/1 card/);await p.locator('#today-review summary').click();assert.equal(await p.getByRole('link',{name:/Clinical cards 1 card marked/}).isVisible(),true);
  const offline=await browser.newContext({serviceWorkers:'allow'});await offline.route('**/*',r=>r.request().url().startsWith(base)?r.continue():r.fulfill({body:'{}'}));const op=await offline.newPage();await op.goto(base);await op.evaluate(()=>navigator.serviceWorker.ready);await op.waitForFunction(()=>navigator.serviceWorker.controller);await offline.setOffline(true);await op.reload();assert.equal(await op.locator('#today').isVisible(),true);await op.getByRole('link',{name:'Study',exact:true}).click();assert.equal(await op.locator('#study .dashboard-tile').count(),6);
  const blocked=await browser.newContext({serviceWorkers:'block'});await blocked.addInitScript(()=>{Storage.prototype.getItem=()=>{throw new DOMException('Blocked','SecurityError')};Storage.prototype.setItem=()=>{throw new DOMException('Blocked','SecurityError')};});await blocked.route('**/*',r=>r.request().url().startsWith(base)?r.continue():r.fulfill({body:'{}'}));const bp=await blocked.newPage();await bp.goto(base);assert.equal(await bp.locator('#today-start').isVisible(),true);await bp.getByRole('link',{name:'My Progress',exact:true}).click();assert.match(await bp.locator('#study-streak').innerText(),/cannot save/);
  assert.deepEqual(errors,[]);console.log('PASS: navigation/history/deep links, quiz setup/save/resume/discard, progress/history, export, search/print, real card counts, layouts at 320–1440 light/dark, blocked storage, offline dashboard.');
 }finally{await browser.close();server.close();}
})().catch(e=>{console.error(e);process.exitCode=1});
