const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),http=require('node:http'),path=require('node:path');
(async()=>{
 const root=path.join(__dirname,'..');const server=http.createServer((req,res)=>{try{const u=new URL(req.url,'http://localhost');const p=path.join(root,u.pathname==='/'?'index.html':u.pathname);res.setHeader('Content-Type',p.endsWith('.js')?'text/javascript':p.endsWith('.css')?'text/css':p.endsWith('.svg')?'image/svg+xml':'text/html');res.end(fs.readFileSync(p));}catch{res.statusCode=404;res.end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}/`;
 const browser=await chromium.launch({executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH,args:['--no-sandbox','--disable-gpu','--no-zygote']});
 try{
 const context=await browser.newContext({serviceWorkers:'block'});await context.route('**/*',r=>r.request().url().startsWith(base)?r.continue():r.fulfill({body:'{}'}));const p=await context.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'#study');await p.getByRole('link',{name:/Review Games Spot/}).click();assert.match(p.url(),/review-games.html/);await p.waitForFunction(()=>window.StudyStreak&&!document.getElementById('start-game').disabled);
 await p.evaluate(()=>localStorage.setItem('field_notes_study_v1',JSON.stringify({version:1,sentinel:'existing-exam'})));
 const goal=()=>p.evaluate(()=>Object.values(StudyStreak.getState().days).some(d=>d.challenge));assert.equal(await goal(),false);
 const info=()=>p.evaluate(()=>REVIEW_GAME_DATA.cases.find(c=>c.title===document.getElementById('case-title').textContent));
 async function answer(correct){const c=await info(),i=correct?c.mistake:(c.mistake+1)%4;await p.locator(`input[value="${i}"]`).check();assert.equal(await p.locator('#reflection-panel').isVisible(),true);await p.locator('#case-reflection').fill('I would check the underlying assumption.');await p.getByRole('button',{name:'Compare with the debrief →'}).click();assert.equal(await p.locator('#case-debrief').isVisible(),true);assert.equal(await p.locator('#case-lines input:disabled').count(),4);assert.equal(await p.locator('#case-correction').innerText(),c.correction);assert.equal(await p.locator('#level-note').innerText(),c.levels[await p.locator('#game-level').inputValue()]);assert.equal(await p.locator('#case-source').getAttribute('href'),await p.evaluate(key=>REVIEW_GAME_DATA.sources[key].url,c.source));}
 await p.getByRole('button',{name:'Start a round →'}).click();await answer(false);assert.equal(await goal(),false);await p.locator('#next-case').click();await answer(true);assert.equal(await goal(),false);await p.locator('#next-case').click();await answer(true);assert.equal(await goal(),false);await p.locator('#next-case').click();assert.equal(await goal(),true);assert.match(await p.locator('#round-score').innerText(),/2 of 3/);assert.equal(await p.locator('#missed-list li').count(),1);
 await p.locator('#retry-missed').click();await answer(true);await p.locator('#next-case').click();assert.match(await p.locator('#round-score').innerText(),/2 of 3/);assert.equal(await p.locator('#retry-missed').isVisible(),false);assert.match(await p.locator('#retry-status').innerText(),/No missed cases/);
 assert.equal(await p.evaluate(()=>JSON.parse(localStorage.getItem('field_notes_study_v1')).sentinel),'existing-exam');
 for(const level of ['aemt','paramedic']){await p.locator('#new-round').click();await p.locator('#game-level').selectOption(level);await p.locator('#round-length').selectOption('6');await p.locator('#start-game').click();const seen=new Set();for(let n=0;n<6;n++){seen.add((await info()).id);await answer(true);await p.locator('#next-case').click();}assert.equal(seen.size,6);assert.match(await p.locator('#round-score').innerText(),/6 of 6/);}
 await p.reload();assert.equal(await p.locator('#game-setup').isVisible(),true);await p.locator('#start-game').click();await p.locator('#end-round').click();assert.match(await p.locator('#round-score').innerText(),/0 of 0/);assert.equal(await p.locator('#retry-missed').isVisible(),false);
 await p.locator('#new-round').click();await p.locator('#start-game').click();for(const dark of [false,true]){await p.evaluate(d=>document.body.classList.toggle('dark-mode',d),dark);for(const width of [1440,768,390,320]){await p.setViewportSize({width,height:900});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,`${width} dark=${dark}`);}}
 await p.setViewportSize({width:1440,height:1000});await p.evaluate(()=>document.body.classList.remove('dark-mode'));await p.screenshot({path:'/tmp/game-desktop.png',fullPage:true});await p.setViewportSize({width:390,height:844});await answer(false);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await p.screenshot({path:'/tmp/game-mobile.png',fullPage:true});
 await p.reload();await p.locator('#start-game').focus();await p.keyboard.press('Enter');const c=await info();await p.locator(`input[value="${c.mistake}"]`).focus();await p.keyboard.press('Space');await p.locator('#reveal-debrief').focus();await p.keyboard.press('Enter');assert.equal(await p.locator('#case-debrief').isVisible(),true);
 const offline=await browser.newContext({serviceWorkers:'allow'});await offline.route('**/*',r=>r.request().url().startsWith(base)?r.continue():r.fulfill({body:'{}'}));const op=await offline.newPage();await op.goto(base);await op.evaluate(()=>navigator.serviceWorker.ready);await op.waitForFunction(()=>navigator.serviceWorker.controller);await offline.setOffline(true);await op.goto(base+'review-games.html');await op.locator('#start-game').click();await op.locator('input[value="0"]').check();await op.locator('#reveal-debrief').click();assert.equal(await op.locator('#case-debrief').isVisible(),true);
 const blocked=await browser.newContext({serviceWorkers:'block'});await blocked.addInitScript(()=>{Storage.prototype.getItem=()=>{throw new Error('blocked')};Storage.prototype.setItem=()=>{throw new Error('blocked')};});const bp=await blocked.newPage();await bp.goto(base+'review-games.html');await bp.locator('#start-game').click();await bp.locator('input[value="0"]').check();await bp.locator('#reveal-debrief').click();assert.equal(await bp.locator('#case-debrief').isVisible(),true);await bp.locator('#game-theme').click();
 assert.deepEqual(errors,[]);console.log('PASS: Study Hall entry, selection/reflection/debrief, immutable first-pass score, missed retries, all six cases at AEMT/Paramedic depth, reload/early exit, streak threshold, existing exam data, keyboard, 320–1440 light/dark layouts, blocked storage and offline play.');
 }finally{await browser.close();server.close();}
})().catch(e=>{console.error(e);process.exitCode=1});
