const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),http=require('node:http'),path=require('node:path');
(async()=>{const server=http.createServer((req,res)=>{try{const p=path.join(__dirname,'..',new URL(req.url,'http://localhost').pathname==='/'?'index.html':new URL(req.url,'http://localhost').pathname);res.setHeader('Content-Type',p.endsWith('.js')?'text/javascript':p.endsWith('.css')?'text/css':'text/html');res.end(fs.readFileSync(p));}catch{res.statusCode=404;res.end();}});await new Promise(r=>server.listen(8767,'127.0.0.1',r));const browser=await chromium.launch({executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH,args:['--no-sandbox','--disable-gpu','--no-zygote']});try{const context=await browser.newContext({serviceWorkers:'block'});await context.route('**/*',r=>r.request().url().includes('127.0.0.1:8767')?r.continue():r.fulfill({body:'{"items":[]}'}));const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:8767/');
 await page.locator('#resource-search').fill('shock');assert(await page.locator('.resource-result').count()>0);await page.locator('#resource-type').selectOption('clinical');assert.match(await page.locator('.resource-result').first().innerText(),/Clinical Flashcard/);assert.equal(await page.locator('.resource-result details').first().getAttribute('open'),null);await page.locator('.resource-result summary').first().click();assert.equal(await page.locator('.resource-result details').first().getAttribute('open'),'');assert.match(await page.locator('.resource-result a').first().getAttribute('href'),/^flashcards.html\?card=/);
 await page.locator('#resource-type').selectOption('terms');await page.locator('#resource-search').fill('card');assert.match(await page.locator('.resource-result').first().innerText(),/Terminology Card/);
 await page.locator('#resource-search').fill('<script>alert(1)</script>');assert.match(await page.locator('#resource-search-status').innerText(),/No matches/);
 await page.locator('#resource-preview').click();assert.match(await page.locator('#resource-print-status').innerText(),/empty/);
 const seeded=await page.evaluate(()=>{const q=quizData.find(q=>q.chainID)||quizData[0],id=JSON.stringify([q.section||'',q.category||'',q.type,q.q]),c=FIELD_NOTE_CARDS.find(c=>c.kind==='clinical'),t=FIELD_NOTE_CARDS.find(c=>c.kind==='terms');const study={version:1,missed:[id],bookmarks:[id],history:[],session:null};localStorage.setItem('field_notes_study_v1',JSON.stringify(study));const cards=CardStudy.getState();cards.records[c.id]={bookmark:true,difficult:true};cards.records[t.id]={known:true};localStorage.setItem(CardStudy.storageKey,JSON.stringify(cards));return {study:JSON.stringify(study),cards:JSON.stringify(cards),q:q.q};});
 await page.locator('#resource-preview').click();assert.equal(await page.locator('#resource-print-dialog').isVisible(),true);assert.match(await page.locator('#resource-print-sheet').innerText(),/Your answer/);assert(!(await page.locator('#resource-print-sheet').innerText()).includes('Answer:'));await page.emulateMedia({media:'print'});assert.equal(await page.locator('#setup-area').isVisible(),false);assert.equal(await page.locator('#resource-print').isVisible(),false);assert.equal(await page.locator('#resource-print-sheet').isVisible(),true);await page.pdf({path:'/tmp/study-sheet-test.pdf',format:'Letter'});await page.emulateMedia({media:'screen'});await page.locator('#resource-close').click();
 await page.locator('#resource-print-answers').check();await page.locator('#resource-preview').click();assert.match(await page.locator('#resource-print-sheet').innerText(),/Answer:/);await page.locator('#resource-close').click();
 for(const collection of ['question-bookmarks','card-bookmarks','difficult','known']){await page.locator('#resource-print-collection').selectOption(collection);await page.locator('#resource-preview').click();assert.equal(await page.locator('#resource-print-dialog').isVisible(),true);assert(await page.locator('.resource-print-item').count()>0);await page.locator('#resource-close').click();}
 assert.equal(await page.evaluate(()=>localStorage.getItem('field_notes_study_v1')),seeded.study);assert.equal(await page.evaluate(()=>localStorage.getItem(CardStudy.storageKey)),seeded.cards);
 await page.locator('#resource-type').selectOption('questions');await page.locator('#resource-search').fill(seeded.q);await page.getByRole('button',{name:'Practice Question',exact:true}).first().click();assert.equal(await page.locator('#setup-area').isVisible(),false);
 await page.goto('http://127.0.0.1:8767/');for(const width of [1440,390,320]){await page.setViewportSize({width,height:900});await page.locator('#resource-search').fill('shock');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);}
 await page.evaluate(()=>{const q=quizData.find(q=>q.type==='grid');localStorage.setItem('field_notes_study_v1',JSON.stringify({version:1,missed:[JSON.stringify([q.section||'',q.category||'',q.type,q.q])]}));});await page.locator('#resource-print-collection').selectOption('missed');await page.locator('#resource-preview').click();assert.match(await page.locator('#resource-print-sheet').innerText(),/Match each item to:/);await page.locator('#resource-close').click();await page.evaluate(()=>localStorage.setItem('field_notes_study_v1',JSON.stringify({version:1,missed:{bad:true}})));await page.locator('#resource-preview').click();assert.match(await page.locator('#resource-print-status').innerText(),/empty/);
 assert.deepEqual(errors,[]);console.log('PASS: search filters, hidden answers, card links, empty collections, linked case print preview, answer options, print PDF layout, all saved collections, state isolation, question practice, and mobile widths.');}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1});
