const assert=require('node:assert/strict'),E=require('../study-plan-engine.js');
const c={title:'Final, Unit; One',start:'2026-10-05',exam:'2026-10-19',minutes:60,block:25,weekdays:[0,1,2,3,4,5,6],topics:[{name:'Biology',priority:1},{name:'Math',priority:3},{name:'Writing',priority:2}]},p=E.generate(c,'plan-test');assert(E.validatePlan(p));assert.equal(p.tasks.length,9);assert.equal(p.tasks[0].topic,'Math');for(const date of E.dates(c)){assert(E.used(p.tasks,date)<=60);assert(date<c.exam);}for(const t of c.topics){const tasks=p.tasks.filter(x=>x.topic===t.name);assert.equal(tasks.length,3);assert.equal(tasks[0].phase,'prepare');assert.equal(new Set(tasks.map(x=>x.date)).size,3);assert(tasks.slice(1).every(x=>x.date>tasks[0].date));}assert.deepEqual(E.generate(c,'plan-test'),p);assert(p.tasks.filter(t=>t.phase==='review').some(t=>t.date==='2026-10-18'));
for(const minutes of [10,30,60,120])for(const block of [10,25,60].filter(x=>x<=minutes))for(const weekdays of [[1],[1,3,5],[0,1,2,3,4,5,6]]){const plan=E.generate({...c,minutes,block,weekdays},'plan-test');assert(E.validatePlan(plan));assert(plan.tasks.every(t=>weekdays.includes(new Date(E.dateValue(t.date)).getUTCDay())));}
const short=E.generate({...c,exam:'2026-10-06',topics:Array.from({length:5},(_,i)=>({name:'Topic '+i,priority:2}))},'short');assert.equal(short.tasks.length,2);assert(short.tasks.every(t=>t.phase==='prepare'));assert.throws(()=>E.generate({...c,weekdays:[0],exam:'2026-10-06'},'bad'),/No selected weekdays/);assert.throws(()=>E.generate({...c,exam:c.start},'bad'),/before your exam/);assert.throws(()=>E.generate({...c,minutes:10,block:25},'bad'),/blocks/);assert(Number.isNaN(E.dateValue('2026-02-30')));assert.equal(E.dates({...c,start:'2028-02-28',exam:'2028-03-02'}).length,3);assert.equal(E.dates({...c,start:'2026-03-07',exam:'2026-03-12'}).length,5);
const bad=JSON.parse(JSON.stringify(p));bad.tasks[0].minutes=240;assert.equal(E.validatePlan(bad),false);const wrongOrder=JSON.parse(JSON.stringify(p));wrongOrder.tasks.find(t=>t.phase==='review').date=p.tasks[0].date;assert.equal(E.validatePlan(wrongOrder),false);assert.equal(E.validatePlan({...p,id:'unsafe\nBEGIN:VEVENT'}),false);
p.tasks[0].notes='Comma, semi; newline\nbackslash\\ '+('é'.repeat(90));p.tasks[0].done=true;let ics=E.calendar(p,new Date('2026-10-01T12:00:00Z'));assert(ics.includes('DTSTART;VALUE=DATE:202610'));assert(!ics.includes('TZID'));assert(ics.includes('SUMMARY:Final\\, Unit\\; One'));assert(ics.split('\r\n').every(line=>Buffer.byteLength(line,'utf8')<=75));assert(ics.endsWith('END:VCALENDAR\r\n'));assert(ics.includes('SUMMARY:Exam: '));p.tasks[0].done=false;ics=E.calendar(p);assert(ics.replace(/\r\n /g,'').includes('Comma\\, semi\\; newline\\nbackslash\\\\'));p.tasks.forEach(t=>t.done=true);assert.equal((E.calendar(p).match(/BEGIN:VEVENT/g)||[]).length,1);
console.log('PASS: capacity, priorities, topic coverage, separate-day reviews, selected weekdays, date bounds/leap/DST, deterministic generation, invalid plans, ICS escaping/UTF-8 folding/all-day dates/completion exclusion.');

for(const method of ['Build a summary or concept map','Recall from memory, then check','Practice questions and review mistakes','Explain it in your own words'])for(const minutes of [10,25,60,240]){const steps=E.instructions({method,minutes});assert.equal(steps.length,3);assert.equal(steps.reduce((n,s)=>n+s.minutes,0),minutes);assert(steps.every(s=>s.minutes>0&&s.text.length>30));}
const guided=E.calendar(E.generate(c,'guided')).replace(/\r\n /g,'');assert(guided.includes('Identify 3–5 key ideas'));assert(guided.includes('Retry one missed item'));console.log('PASS: all four activity guides, exact time totals, and exported directions.');
