const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),http=require('node:http'),path=require('node:path');
(async()=>{const server=http.createServer((req,res)=>{try{const p=path.join(__dirname,'..',new URL(req.url,'http://localhost').pathname==='/'?'index.html':new URL(req.url,'http://localhost').pathname);res.setHeader('Content-Type',p.endsWith('.js')?'text/javascript':p.endsWith('.css')?'text/css':'text/html');res.end(fs.readFileSync(p));}catch{res.statusCode=404;res.end();}});await new Promise(r=>server.listen(8789,'127.0.0.1',r));const browser=await chromium.launch({executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH,args:['--no-sandbox','--disable-gpu','--no-zygote']});try{const context=await browser.newContext({serviceWorkers:'block',timezoneId:'America/Chicago'});await context.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.fulfill({body:'{}'}));const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));const base='http://127.0.0.1:8789/';await page.goto(base);assert.match(await page.locator('#study-streak').innerText(),/0 consecutive/);assert.equal(await page.evaluate(()=>Object.keys(StudyStreak.getState().days).length),0);
const ids=await page.evaluate(()=>FIELD_NOTE_CARDS.filter(c=>c.kind==='clinical').slice(0,5).map(c=>c.id));for(const id of ids){await page.goto(base+'flashcards.html?card='+encodeURIComponent(id));await page.getByRole('button',{name:'Reveal / Hide Answer'}).click();await page.getByRole('button',{name:'Know',exact:true}).click();}await page.goto(base);assert.match(await page.locator('#study-streak').innerText(),/Daily goal completed/);assert.match(await page.locator('#study-streak').innerText(),/1 consecutive/);assert.equal(await page.locator('.streak-day.done').count(),1);
// Download contains only allowed student progress; importing rejects foreign app keys.
await page.evaluate(()=>localStorage.setItem('instructor-secret-test','keep'));const wait=page.waitForEvent('download');await page.getByRole('button',{name:'Download Backup',exact:true}).click();const download=await wait;const file=await download.path(),backup=JSON.parse(fs.readFileSync(file,'utf8'));assert.equal(backup.app,'eric-field-notes-progress');assert(backup.data.field_notes_streak_v1);assert.equal(backup.data['instructor-secret-test'],undefined);const before=await page.evaluate(()=>localStorage.getItem('field_notes_streak_v1'));
await page.locator('#progress-backup-file').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({app:'eric-field-notes-progress',version:1,data:{'instructor-secret-test':{version:1}}}))});assert.equal(await page.getByRole('button',{name:'Restore Backup'}).isDisabled(),true);assert.equal(await page.evaluate(()=>localStorage.getItem('field_notes_streak_v1')),before);
await page.evaluate(()=>localStorage.removeItem('field_notes_streak_v1'));await page.reload();await page.locator('#progress-backup-file').setInputFiles(file);page.once('dialog',d=>d.dismiss());await page.getByRole('button',{name:'Restore Backup'}).click();assert.equal(await page.evaluate(()=>localStorage.getItem('field_notes_streak_v1')),JSON.stringify({version:1,days:{},earned:{}}));page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'Restore Backup'}).click();await page.waitForFunction(()=>window.StudyStreak?.getState().days&&Object.keys(StudyStreak.getState().days).length>0);assert.match(await page.locator('#study-streak').innerText(),/Daily goal completed/);assert.equal(await page.evaluate(()=>localStorage.getItem('instructor-secret-test')),'keep');
for(const dark of [false,true]){await page.evaluate(d=>document.body.classList.toggle('dark-mode',d),dark);for(const width of [1440,390,320]){await page.setViewportSize({width,height:900});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.locator('#study-streak').screenshot({path:`/tmp/streak-${dark}-${width}.png`});}}
assert.deepEqual(errors,[]);console.log('PASS: site visits do not count, five actual card reviews qualify, saved day/progress, download and restore, invalid backup rejection, cancel, unrelated-key isolation, mobile and dark layout.');}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1});
