const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),http=require('node:http'),path=require('node:path');
(async()=>{const server=http.createServer((req,res)=>{try{const p=path.join(__dirname,'..',new URL(req.url,'http://localhost').pathname==='/'?'index.html':new URL(req.url,'http://localhost').pathname);res.setHeader('Content-Type',p.endsWith('.js')?'text/javascript':p.endsWith('.css')?'text/css':'text/html');res.end(fs.readFileSync(p));}catch{res.statusCode=404;res.end();}});await new Promise(r=>server.listen(8783,'127.0.0.1',r));const browser=await chromium.launch({executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH,args:['--no-sandbox','--disable-gpu','--no-zygote']});try{
 const context=await browser.newContext({serviceWorkers:'block'});await context.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.fulfill({body:'{}'}));const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));const base='http://127.0.0.1:8783/';await page.goto(base);assert.equal(await page.locator('.achievement').count(),8);assert.equal(await page.locator('.achievement.earned').count(),0);assert.equal(await page.locator('#badge-celebration').count(),0);
 // Historical credit without changing source data. Incomplete sessions do not count.
 const source=await page.evaluate(()=>{const now=Date.now(),path=FIELD_NOTE_CARDS.filter(c=>c.kind==='clinical'&&c.deck==='Pathophysiology'),records={},history=[];path.forEach((c,i)=>{records[c.id]={known:true,rating:'good',interval:1,due:now+86400000,reviewedAt:now};if(i<10)history.push({id:c.id,rating:'again',date:now-1000});history.push({id:c.id,rating:'good',date:now});});const finding={},order=[];CHANGE_FINDING_CASES.slice(0,5).forEach(c=>finding[c.id]={0:c.variants[0].correct,1:c.variants[1].correct});WHAT_FIRST_CASES.slice(0,5).forEach(c=>order.push({id:c.id,order:c.steps.map(s=>s.id),confidence:'unsure',date:now}));const quiz={version:1,history:Array.from({length:10},(_,i)=>({id:'old-'+i,date:new Date(now-(i%5)*86400000).toISOString(),total:3,completed:3,correct:2,graded:3})).concat({id:'incomplete',date:new Date(now).toISOString(),total:10,completed:1,graded:10,correct:1}),missed:[],bookmarks:[],session:null};const values={'field_notes_study_v1':quiz,'field_notes_cards_v1':{version:1,records,history,sessions:{},migrated:{clinical:true,terms:true}},'field_notes_finding_v1':{version:1,answers:finding},'field_notes_order_v1':{version:1,history:order},'field_notes_plan_v1':{version:1,plan:{tasks:Array.from({length:5},(_,i)=>({id:'block-'+i,done:true}))}}};for(const [key,value]of Object.entries(values))localStorage.setItem(key,JSON.stringify(value));return Object.fromEntries(Object.keys(values).map(key=>[key,localStorage.getItem(key)]));});
 await page.reload();assert.equal(await page.locator('.achievement.earned').count(),8);assert.match(await page.locator('#badge-celebration').innerText(),/earned/);assert.equal(await page.locator('#badge-celebration a').getAttribute('href'),'index.html#badge-case');let s=await page.evaluate(()=>StudyBadges.getState());assert.equal(Object.keys(s.sessions).length,10);const earned=s.earned;source.field_notes_cards_v1=await page.evaluate(()=>localStorage.getItem('field_notes_cards_v1'));await page.evaluate(()=>StudyBadges.refresh());for(const [key,value]of Object.entries(source))assert.equal(await page.evaluate(key=>localStorage.getItem(key),key),value);
 await page.getByRole('button',{name:'Dismiss',exact:true}).click();await page.reload();assert.equal(await page.locator('#badge-celebration').count(),0);assert.deepEqual((await page.evaluate(()=>StudyBadges.getState())).earned,earned);
 await page.evaluate(()=>{for(const key of ['field_notes_study_v1','field_notes_cards_v1','field_notes_finding_v1','field_notes_order_v1','field_notes_plan_v1'])localStorage.removeItem(key);});await page.reload();assert.equal(await page.locator('.achievement.earned').count(),8);
 for(const dark of [false,true]){await page.evaluate(d=>document.body.classList.toggle('dark-mode',d),dark);for(const width of [1440,390,320]){await page.setViewportSize({width,height:900});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.locator('#badge-case').screenshot({path:`/tmp/badges-${dark?'dark':'light'}-${width}.png`});}}
 // Actual flashcard completion triggers a session; single-card search views do not.
 await page.evaluate(()=>{localStorage.clear();const keys=FIELD_NOTE_CARDS.filter(c=>c.kind==='clinical').slice(0,3).map(c=>c.id);localStorage.setItem('field_notes_cards_v1',JSON.stringify({version:1,records:{},sessions:{clinical:{deck:'all',mode:'all',keys,index:0,flipped:false}},history:[],migrated:{clinical:true,terms:true}}));});await page.goto(base+'flashcards.html?resume=1');for(let i=0;i<3;i++){await page.getByRole('button',{name:'Reveal / Hide Answer'}).click();await page.getByRole('button',{name:i===0?'Don’t Know':'Know',exact:true}).click();}assert(Object.hasOwn((await page.evaluate(()=>StudyBadges.getState())).earned,'first-shift'));assert.equal(await page.locator('#badge-celebration').isVisible(),true);assert.equal(Object.keys((await page.evaluate(()=>StudyBadges.getState())).sessions).length,1);
 const card=await page.evaluate(()=>FIELD_NOTE_CARDS.find(c=>c.kind==='clinical').id);await page.goto(base+'flashcards.html?card='+encodeURIComponent(card));await page.getByRole('button',{name:'Reveal / Hide Answer'}).click();await page.getByRole('button',{name:'Know',exact:true}).click();s=await page.evaluate(()=>StudyBadges.getState());assert.equal(Object.keys(s.recovered).length,1);assert.equal(Object.keys(s.sessions).length,1);
 // Actual case actions credit both findings once, and don't credit wrong answers.
 await page.goto(base+'change-finding.html');const correct=await page.evaluate(()=>CHANGE_FINDING_CASES[0].variants.map(v=>v.correct));await page.locator('#challenge-choices button').nth((correct[0]+1)%4).click();assert.equal(Object.keys((await page.evaluate(()=>StudyBadges.getState())).findings).length,0);await page.locator('#challenge-choices button').nth(correct[0]).click();await page.locator('#finding-changed').click();await page.locator('#challenge-choices button').nth(correct[1]).click();assert.equal(Object.keys((await page.evaluate(()=>StudyBadges.getState())).findings).length,1);await page.locator('#challenge-choices button').nth(correct[1]).click();assert.equal(Object.keys((await page.evaluate(()=>StudyBadges.getState())).findings).length,1);
 // Cross-tab earned badges update without repeatedly writing/celebrating the same award.
 const other=await context.newPage();await other.goto(base);await other.evaluate(()=>{for(let i=0;i<9;i++)StudyBadges.record({type:'session',id:'new-'+i,date:Date.now()});});await page.waitForFunction(()=>Object.hasOwn(StudyBadges.getState().earned,'showing-up'));await other.close();
 await page.goto(base);await page.evaluate(()=>localStorage.setItem(StudyBadges.storageKey,'{invalid'));await page.reload();assert.equal(await page.locator('.achievement').count(),8);
 const blocked=await browser.newContext({serviceWorkers:'block'});await blocked.addInitScript(()=>{Storage.prototype.getItem=function(){throw new DOMException('Blocked','SecurityError')};Storage.prototype.setItem=function(){throw new DOMException('Blocked','SecurityError')};});await blocked.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.fulfill({body:'{}'}));const bp=await blocked.newPage();await bp.goto(base);assert.match(await bp.locator('.badge-storage').innerText(),/cannot save/);await bp.evaluate(()=>StudyBadges.record({type:'session',id:'blocked-session'}));assert.equal(await bp.locator('.achievement.earned').count(),1);
 const offline=await browser.newContext({serviceWorkers:'allow'});await offline.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.fulfill({body:'{}'}));const op=await offline.newPage();await op.goto(base);await op.evaluate(()=>navigator.serviceWorker.ready);await op.waitForFunction(()=>navigator.serviceWorker.controller);await offline.setOffline(true);await op.reload();await op.waitForFunction(()=>window.StudyBadges);assert.equal(await op.locator('.achievement').count(),8);
 assert.deepEqual(errors,[]);console.log('PASS: existing activity credit, eight badges, permanent dates, source isolation, actual card/case events, completion vs search views, celebration/dismiss/reload, cross-tab sync, mobile/dark layout, corrupt/blocked storage, offline.');
 }finally{await browser.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1});
