const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),http=require('node:http'),path=require('node:path');
(async()=>{const server=http.createServer((req,res)=>{try{const p=path.join(__dirname,'..',new URL(req.url,'http://localhost').pathname==='/'?'index.html':new URL(req.url,'http://localhost').pathname);res.setHeader('Content-Type',p.endsWith('.js')?'text/javascript':p.endsWith('.css')?'text/css':p.endsWith('.txt')?'text/plain':'text/html');res.end(fs.readFileSync(p));}catch{res.statusCode=404;res.end();}});await new Promise(r=>server.listen(8772,'127.0.0.1',r));const browser=await chromium.launch({executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH,args:['--no-sandbox','--disable-gpu','--no-zygote']});try{
const base='http://127.0.0.1:8772/',context=await browser.newContext({serviceWorkers:'block'});await context.route('**/*',r=>r.request().url().startsWith(base)?r.continue():r.fulfill({body:'{"items":[]}'}));const p=await context.newPage(),errors=[];p.on('pageerror',e=>{errors.push(e.message);console.error(e.message)});await p.goto(base);const colors=await p.locator('#setup-area .mode-btn').evaluateAll(nodes=>nodes.map(n=>({text:n.textContent,bg:getComputedStyle(n).backgroundColor,fg:getComputedStyle(n).color})));assert.equal(colors.find(n=>n.text.includes('Research')).bg,'rgb(37, 99, 235)');assert(colors.filter(n=>/Review Mode|Exam Mode/.test(n.text)).every(n=>n.bg==='rgb(138, 83, 6)'));assert(colors.filter(n=>!/Review Mode|Exam Mode|Research/.test(n.text)).every(n=>n.bg==='rgb(6, 64, 43)'));
await p.evaluate(()=>{localStorage.setItem('field_notes_study_v1','quiz-sentinel');localStorage.setItem('field_notes_cards_v1','cards-sentinel');});await p.getByRole('button',{name:'What Comes First?',exact:false}).click();await p.waitForFunction(()=>document.getElementById('order-case')?.options.length===2);assert.equal(await p.locator('#order-level option').count(),3);assert.equal(await p.locator('#order-case option').count(),2);await p.locator('#order-check').click();assert.match(await p.locator('#order-error').innerText(),/confidence/);assert.equal(await p.locator('#order-feedback').isVisible(),false);
const data=await p.evaluate(()=>WHAT_FIRST_CASES);assert.equal(data.length,12);assert(data.every(c=>c.sources.length&&c.scope.url.includes('/56917')&&c.steps.length===4&&c.checkedOn&&c.dependencies.length===3));
async function arrange(ids){for(let target=0;target<ids.length;target++){let current=(await p.locator('#order-list li').evaluateAll(ns=>ns.map(n=>n.dataset.id))).indexOf(ids[target]);while(current>target){await p.getByRole('button',{name:`Move step ${current+1} up`,exact:true}).click();current--;}}assert.deepEqual(await p.locator('#order-list li').evaluateAll(ns=>ns.map(n=>n.dataset.id)),ids);}
for(const level of ['EMT','AEMT','Paramedic']){await p.locator('#order-level').selectOption(level);assert.equal(await p.locator('#order-case option').count(),data.filter(c=>c.level===level).length);for(const c of data.filter(c=>c.level===level)){await p.locator('#order-case').selectOption(c.id);assert.match(await p.locator('#order-category').innerText(),new RegExp(level==='AEMT'?'Advanced EMT':level,'i'));await arrange(c.steps.map(s=>s.id).reverse());await p.getByLabel('Confident',{exact:true}).check();await p.reload();assert.equal(await p.locator('#order-level').inputValue(),level);assert.equal(await p.locator('#order-case').inputValue(),c.id);assert.equal(await p.getByLabel('Confident',{exact:true}).isChecked(),true);assert.deepEqual(await p.locator('#order-list li').evaluateAll(ns=>ns.map(n=>n.dataset.id)),c.steps.map(s=>s.id).reverse());await p.locator('#order-check').click();assert.match(await p.locator('#order-result').innerText(),/Review/);assert.match(await p.locator('#order-confidence-note').innerText(),/confident mistake/);assert.equal(await p.getByLabel('Confident',{exact:true}).isDisabled(),true);assert(await p.locator('#order-list button').evaluateAll(ns=>ns.every(n=>n.disabled)));assert(await p.locator('#order-sources a').count()>=2);await p.reload();assert.equal(await p.locator('#order-feedback').isVisible(),true);await p.locator('#order-retry').click();assert.equal(await p.getByLabel('Confident',{exact:true}).isChecked(),false);await arrange(c.steps.map(s=>s.id));await p.getByLabel('Unsure',{exact:true}).check();await p.locator('#order-check').click();assert.match(await p.locator('#order-result').innerText(),/respects/);assert.equal(await p.locator('#order-explanation li').count(),4);assert.match(await p.locator('#order-progress').innerText(),/latest orders/);}}
assert.equal(await p.evaluate(()=>JSON.parse(localStorage.getItem('field_notes_order_v1')).history.length),24);assert.equal(await p.evaluate(()=>localStorage.getItem('field_notes_study_v1')),'quiz-sentinel');assert.equal(await p.evaluate(()=>localStorage.getItem('field_notes_cards_v1')),'cards-sentinel');await p.locator('#order-level').selectOption('EMT');assert.match(await p.locator('#order-progress').innerText(),/2\/2/);await p.locator('#order-retry').click();
// A delayed-access PEA pathway accepts the independent scheduled rhythm check.
await p.locator('#order-level').selectOption('Paramedic');await p.locator('#order-case').selectOption('param-pea');await p.locator('#order-retry').click();await arrange(['0','3','1','2']);await p.getByLabel('Confident',{exact:true}).check();await p.locator('#order-check').click();assert.match(await p.locator('#order-result').innerText(),/respects/);await p.locator('#order-level').selectOption('EMT');if(await p.locator('#order-retry').isVisible())await p.locator('#order-retry').click();
// Real drag-and-drop persists the displayed order.
await p.setViewportSize({width:900,height:1000});const before=await p.locator('#order-list li').evaluateAll(ns=>ns.map(n=>n.dataset.id));const grip=await p.locator('#order-list li').last().locator('.order-grip').boundingBox(),first=await p.locator('#order-list li').first().boundingBox();await p.mouse.move(grip.x+grip.width/2,grip.y+grip.height/2);await p.mouse.down();await p.mouse.move(first.x+50,first.y+10,{steps:20});await p.mouse.up();await p.waitForFunction(old=>JSON.parse(localStorage.getItem('field_notes_order_v1')).drafts['emt-adult-arrest'].order.join()!==old,before.join());const dragged=await p.locator('#order-list li').evaluateAll(ns=>ns.map(n=>n.dataset.id));assert.deepEqual(await p.evaluate(()=>JSON.parse(localStorage.getItem('field_notes_order_v1')).drafts['emt-adult-arrest'].order),dragged);
for(const width of [1440,390,320]){await p.setViewportSize({width,height:1000});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);}await p.locator('#order-theme').click();assert.equal(await p.locator('body').evaluate(n=>n.classList.contains('dark-mode')),true);await p.reload();assert.equal(await p.locator('body').evaluate(n=>n.classList.contains('dark-mode')),true);
await p.goto(base);await p.evaluate(()=>{localStorage.setItem('field_notes_order_v1',JSON.stringify({version:1,level:'EMT',current:'param-vf',drafts:{'emt-adult-arrest':{order:['0','0','1','2'],confidence:'invalid',checked:true}},history:[{id:'no-case',date:1}]}));});await p.goto(base+'what-first.html');assert.equal(await p.locator('#order-case').inputValue(),'emt-adult-arrest');assert.equal(await p.locator('#order-feedback').isVisible(),false);assert.equal(new Set(await p.locator('#order-list li').evaluateAll(ns=>ns.map(n=>n.dataset.id))).size,4);
const blocked=await browser.newContext({serviceWorkers:'block'});await blocked.addInitScript(()=>{Storage.prototype.getItem=()=>{throw new DOMException('Blocked','SecurityError')};Storage.prototype.setItem=()=>{throw new DOMException('Blocked','SecurityError')};});const bp=await blocked.newPage();await bp.goto(base+'what-first.html');assert.match(await bp.locator('#order-storage').innerText(),/cannot save/);await bp.getByLabel('Unsure',{exact:true}).check();await bp.locator('#order-check').click();assert.equal(await bp.locator('#order-feedback').isVisible(),true);
const fallback=await browser.newContext({serviceWorkers:'block'});await fallback.route('**/Sortable.min.js',r=>r.abort());const fp=await fallback.newPage();await fp.goto(base+'what-first.html');const initial=await fp.locator('#order-list li').first().getAttribute('data-id');await fp.getByRole('button',{name:'Move step 1 down',exact:true}).click();assert.equal(await fp.locator('#order-list li').nth(1).getAttribute('data-id'),initial);
const offline=await browser.newContext({serviceWorkers:'allow'});await offline.route('**/*',r=>r.request().url().startsWith(base)?r.continue():r.fulfill({body:'{}'}));const op=await offline.newPage();await op.goto(base);await op.evaluate(()=>navigator.serviceWorker.ready);await op.waitForFunction(()=>navigator.serviceWorker.controller);await offline.setOffline(true);await op.goto(base+'what-first.html');await op.locator('#order-level').selectOption('AEMT');assert.equal(await op.locator('#order-list li').count(),4);assert.equal(await op.evaluate(()=>typeof Sortable),'function');
assert.deepEqual(errors,[]);console.log('PASS: twelve scoped cases, confidence gate, wrong/correct feedback, lock/retry, draft and feedback resume, isolated history, real dragging, keyboard arrows, mobile/dark theme, invalid/blocked storage, library fallback, offline, and homepage palette.');
}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1});
